### ISSUE TITLE
how to add a small image into a large image

### ISSUE THREAD

**Issue by NextGuido** [libvips/pyvips#105]
@jcupitt Hi, I have such python code below and I wanna rewrite it with pyvips. What should I do?

```python
import numpy as np

start_point_x, start_point_y = 500, 500

small_one = np.ones((2048, 2448, 3), np.uint8)
s_h, s_w, s_c = small_one.shape
big_one = np.zeros((10000, 10000, 3), np.uint8)

big_one[start_point_y: start_point_y+s_h, start_point_x: start_point_x+s_w, :] = small_one

print(np.sum(big_one), np.sum(small_one))
```

**Comment by jcupitt** [comment]
Hello @NextGuido,

Try:

```python
import pyvips

start_point_x, start_point_y = 500, 500

small_one = pyvips.Image.black(2048, 2448, bands=3) + 1
big_one = pyvips.Image.black(10000, 10000, bands=3)

big_one = big_one.insert(small_one,
        start_point_y + small_one.height, 
        start_point_x + small_one.width)

def total(image):
    return image.avg() * image.width * image.height * image.bands

print(total(big_one), total(small_one))
```

On this 2015 laptop, I see:

```
$ time python3 ones-np.py 
15040512 15040512
real	0m0.710s
user	0m0.761s
sys	0m0.267s
$ time python3 ones-vips.py 
15040512.0 15040512.0
real	0m0.553s
user	0m1.286s
sys	0m0.040s
```

That's computing with float. It'll run a little faster in 8-bit:

```
small_one = pyvips.Image.black(2048, 2448, bands=3).linear(1, 1, uchar=True)
```

Now I get:

```
$ time python3 ones-vips.py 
15040512.0 15040512.0
real	0m0.487s
user	0m1.059s
sys	0m0.044s
```

**Comment by jcupitt** [comment]
Docs for `black`:

https://libvips.github.io/libvips/API/current/libvips-create.html#vips-black

Docs for `insert`:

https://libvips.github.io/libvips/API/current/libvips-conversion.html#vips-insert

**Comment by NextGuido** [comment]
@jcupitt thx for quick answering! 
what about the small_one and big_one have different values(not only for zero and one)? cause the small_one and big_one are real pictures!

**Comment by jcupitt** [comment]
Use `new_from_file` to make a new image from a file. If you set `access='sequential'`, pyvips will stream the images.

For example:

```python
import pyvips

start_point_x, start_point_y = 500, 500

small_one = pyvips.Image.new_from_file('a.tif', access='sequential')
big_one = pyvips.Image.new_from_file('b.tif', access='sequential')

big_one = big_one.insert(small_one, 
        start_point_y + small_one.height,
        start_point_x + small_one.width)

def total(image):
    return image.avg() * image.width * image.height * image.bands
        
print(total(big_one))
```

Then:

```
$ vipsheader a.tif b.tif
a.tif: 2048x2448 uchar, 3 bands, srgb, tiffload
b.tif: 10000x10000 uchar, 3 bands, srgb, tiffload
$ time python3 ones-vips.py
50827196585.0
real	0m0.588s
user	0m0.905s
sys	0m0.155s
```

**Comment by NextGuido** [comment]
>

> Use `new_from_file` to make a new image from a file. If you set `access='sequential'`, pyvips will stream the images.
> 
> For example:
> 
> ```python
> import pyvips
> 
> start_point_x, start_point_y = 500, 500
> 
> small_one = pyvips.Image.new_from_file('a.tif', access='sequential')
> big_one = pyvips.Image.new_from_file('b.tif', access='sequential')
> 
> big_one = big_one.insert(small_one, 
>         start_point_y + small_one.height,
>         start_point_x + small_one.width)
> 
> def total(image):
>     return image.avg() * image.width * image.height * image.bands
>         
> print(total(big_one))
> ```
> 
> Then:
> 
> ```
> $ vipsheader a.tif b.tif
> a.tif: 2048x2448 uchar, 3 bands, srgb, tiffload
> b.tif: 10000x10000 uchar, 3 bands, srgb, tiffload
> $ time python3 ones-vips.py
> 50827196585.0
> real	0m0.588s
> user	0m0.905s
> sys	0m0.155s
> ```

My bad! I just made a mistake! What I really want to do is like below(add operation):
`
big_one[start_point_y: start_point_y+s_h, start_point_x: start_point_x+s_w, :] += small_one
`

**Comment by jcupitt** [comment]
Try crop / add / insert.

**Comment by NextGuido** [comment]
> Try crop / add / insert.

@jcupitt I just tried above operation and below is my code:
```
import numpy as np
import pyvips
from tqdm import trange


def compute_linear_blend_pixel_weights(size, alpha=1.5):
    d_min_mat_i = np.zeros([size[0], 1], dtype=np.float32)
    d_min_mat_j = np.zeros([1, size[1]], dtype=np.float32)
    for i in range(size[0]):
        d_min_mat_i[i, 0] = min(i + 1, size[0] - i)
    for j in range(size[1]):
        d_min_mat_j[0, j] = min(j + 1, size[1] - j)

    w_mat = d_min_mat_i * d_min_mat_j
    w_mat = w_mat * alpha
    return w_mat


height, width, channel = 2048, 2448, 3
color_mode = True
alpha = 1.5

sites = [[0, 497.0], [36, 2844.0], [70, 5218.0], [107, 7585.0], [144, 9952.0], [181, 12319.0], [218, 14686.0],
         [256, 17065.0], [293, 19432.0], [330, 21799.0], [367, 24166.0], [404, 26533.0], [441, 28900.0], [478, 31267.0],
         [515, 33634.0], [552, 36001.0], [589, 38368.0], [626, 40735.0], [663, 43102.0], [700, 45469.0],
         [2621., 45440.], [2584.0, 43073.0], [2547.0, 40706.0], [2510.0, 38339.0], [2473.0, 35972.0],
         [2436.0, 33605.0], [2399.0, 31238.0], [2362.0, 28871.0], [2325.0, 26504.0], [2288.0, 24137.0],
         [2251.0, 21770.0], [2215.0, 19405.0], [2178.0, 17044.0], [2140.0, 14664.0], [2103.0, 12297.0],
         [2066.0, 9930.0], [2029.0, 7563.0], [1992.0, 5196.0], [1955.0, 2829.0], [1918.0, 462.0]]

global_y_img_pos, global_x_img_pos = np.zeros(len(sites), dtype=np.uint32), \
                                     np.zeros(len(sites), dtype=np.uint32)
for i, (y, x) in enumerate(sites):
    global_y_img_pos[i] = y
    global_x_img_pos[i] = x

stitched_img_height = global_y_img_pos.max() + height
stitched_img_width = global_x_img_pos.max() + width

w_mat = compute_linear_blend_pixel_weights([height, width], alpha)
w_mat = np.stack([w_mat for _ in range(channel)], axis=-1)
w_mat = pyvips.Image.new_from_memory(w_mat.reshape(width * height * channel), width, height, bands=channel,
                                     format='float')

stitched_img = pyvips.Image.black(stitched_img_width, stitched_img_height, bands=3)
countsI = pyvips.Image.black(stitched_img_width, stitched_img_height, bands=3)

img = pyvips.Image.new_from_file('test.tif')            # shape is (2048, 2448, 3)

for img_idx in trange(len(sites)):
    current_image = img * w_mat

    x_st = global_x_img_pos[img_idx]
    y_st = global_y_img_pos[img_idx]

    roi_image = stitched_img.crop(x_st, y_st, width, height)
    roi_countsI = countsI.crop(x_st, y_st, width, height)
    roi_image += current_image
    roi_countsI += w_mat

    stitched_img = stitched_img.insert(roi_image, x_st, y_st, expand=True)
    countsI = countsI.insert(roi_countsI, x_st, y_st, expand=True)

```

when I run the code in ubuntu system, it works well and fast(about 200.03it/s)! But in my antother ubuntu system, it went very slow when the for loop goes... 
I don't know the reason, and the latter ubuntu system even has a higher configuration. please help me

**Comment by NextGuido** [comment]
ok! the problem is soved! It seems that the pyvips' version is the reason! When I downgrade the pyvips version into 2.1.3, the problem is solved!
thx @jcupitt

**Comment by jcupitt** [comment]
That's strange, it should be quicker with the latest version. I'll have a look.

**Comment by jcupitt** [comment]
I found a horrible problem in 2.1.6 -- some internal tables could grow exponentially in some cases.

I've fixed it, and your code should run quickly now. Thanks!

**Comment by jcupitt** [comment]
.... and I've pushed version 2.1.7 with this fix.

**Comment by NextGuido** [comment]
Thanks very much! version 2.1.7 worked!

**Comment by mrcolo** [comment]
it'd be nice if we could add label images as "associated images" - does pyvips have that capability?

**Comment by jcupitt** [comment]
Yes, you can set images as metadata on other images. But I don't think any of the writers will write subimages like this.
