### ISSUE TITLE
Faster way than IFTHENELSE

### ISSUE THREAD

**Issue by akaprasanga** [libvips/pyvips#112]
I am trying to add a different texture to each color present in the image. For that, I am using ifthenelse and my images are of usually 8000X10000. It takes about 8-9 seconds on my dual-core machine and my pvips is running in ABI mode. Is there any other way around that can perform the same task in less time? 
```
list_of_texture_names = ["A.jpg", "B.jpg", "C.jpg", "D.jpg"]
colors = [(232, 225, 199), (211, 167, 73), (210, 125, 60), (151, 189, 174)]
main_img = pyvips.Image.new_from_file("Original.png")
main_img = main_img.flatten()
texture_added_img = main_img.copy()
for i, each_color in enumerate(colors):
      texture_added_img = (main_img == each_color).ifthenelse(main_img - 100
                           +pyvips.Image.new_from_file(list_of_texture_names[i]), 
                                          texture_added_img)
texture_added_img.write_to_file("Textured.jpg")

```

**Comment by jcupitt** [comment]
Hello @akaprasanga,

If you do `image == (10, 20, 30)` you get a three band boolean image, with band 0 being the pixels in `image[0]` which equal 10, band 1 the pixels which equal 20, etc. You need to AND all the bands together to find pixels where all three values match.

You can get a nice speedup by turning on image streaming. libvips will be able to overlap the load and save.

Your `main_img - 100 + textures[i]` will make a float image (constants are always float), and then everything after that will also be float. Cast back to uchar for a small speedup.

Are your textures made from repeating patterns? It would be quicker to load the small pattern block and then replicate it with pyvips.

Try:

```python
list_of_texture_names = ["A.jpg", "B.jpg", "C.jpg", "D.jpg"]
textures = [pyvips.Image.new_from_file(filename, access="sequential")
            for filename in list_of_texture_names]
colors = [(232, 225, 199), (211, 167, 73), (210, 125, 60), (151, 189, 174)]
main_img = pyvips.Image.new_from_file("Original.png", access="sequential")
main_img = main_img.flatten()
texture_added_img = main_img
for i, each_color in enumerate(colors):
    texture_added_img = (main_img == each_color).bandand().ifthenelse(
        (main_img - 100 + textures[i]).cast("uchar"), texture_added_img)
texture_added_img.write_to_file("Textured.jpg")
```

**Comment by jcupitt** [comment]
Beyond that, I think we'd need to add a new operation to libvips. 

It has `map` to map an image through a lookup table (pixels select constant values from a table), but you need something like `map_image`, where pixels pick images (not constants) from an array of images.

It wouldn't be hard to write if you're OK with C.

**Comment by akaprasanga** [comment]
Yes changing the access mode to sequential gave me a significant speed gain. And also the image casting was helpful. It would be great to find map_image function in libvips.

Thank you very much for your meticulous observation and suggestion.

**Comment by jcupitt** [comment]
Let's leave this issue open as an enhancement.

**Comment by jcupitt** [comment]
Moved to main libvips issue.
