### ISSUE TITLE
Memory issue with draw_mask

### ISSUE THREAD

**Issue by aravind3134** [libvips/pyvips#113]
Hey John,

I am trying to write a pil image mask on to a blank pyvips image that I created.
**image** here is the pyvips image that I created using the following code:

```
    black_space = np.zeros((scalex, scaley), dtype=np.uint8)

    # reshape into a huge linear array
    linear = black_space.reshape(scalex * scaley) 

    image = pyvips.Image.new_from_memory(linear.data, \
           scalex, scaley, bands, format="uchar")
```
Now I need to draw PIL image at a specific location (top_left[0], top_left[1]). So, I converted the PIL image to a vips image to use draw_mask functionality of pyvips. 
```

    memory_area = io.BytesIO()
    pil_image.save(memory_area,'TIFF')
    pil_image = memory_area.getvalue()
            
    vips_image = pyvips.Image.new_from_buffer(pil_image, "", access = 'sequential')
```
And at last when I use 
```
    image = image.draw_mask((255.0, 255.0, 255.0), vips_image, top_left[0], top_left[1])
```

to draw on to the big image, it looks like the memory usage is increasing rapidly. I confirmed by printing the memory usage before and after executing the above statement.

Am I creating a copy of image here by assignment operation. If not, where am I going wrong with the usage of this line. If yes, is there a way to write into the same image as opposed to duplicationg the image in pyvips.

Thanks in advance.

**Comment by aravind3134** [comment]
vips warning: tiff2vips: no resolution information for TIFF image "memory buffer" -- defaulting to 1 pixel per mm
Before drawing:  13G
vips warning: tiff2vips: no resolution information for TIFF image "memory buffer" -- defaulting to 1 pixel per mm
After Drawing 17G
vips warning: tiff2vips: no resolution information for TIFF image "memory buffer" -- defaulting to 1 pixel per mm
Before drawing:  17G
vips warning: tiff2vips: no resolution information for TIFF image "memory buffer" -- defaulting to 1 pixel per mm
After Drawing 20G
vips warning: tiff2vips: no resolution information for TIFF image "memory buffer" -- defaulting to 1 pixel per mm
Before drawing:  20G
vips warning: tiff2vips: no resolution information for TIFF image "memory buffer" -- defaulting to 1 pixel per mm
After Drawing 23G
vips warning: tiff2vips: no resolution information for TIFF image "memory buffer" -- defaulting to 1 pixel per mm
Before drawing:  23G
vips warning: tiff2vips: no resolution information for TIFF image "memory buffer" -- defaulting to 1 pixel per mm
After Drawing 27G
vips warning: tiff2vips: no resolution information for TIFF image "memory buffer" -- defaulting to 1 pixel per mm
Before drawing:  27G
vips warning: tiff2vips: no resolution information for TIFF image "memory buffer" -- defaulting to 1 pixel per mm
After Drawing 30G

**Comment by jcupitt** [comment]
Hi, `draw_image` uses LOADS of memory, it's only for paintbox applications really, don't use it for general image processing.

Try `insert` instead.

**Comment by jcupitt** [comment]
... by paintbox, I mean things like the nip2 paint bar, which is what these functions were written for. If you're not writing something like that, they will not be useful.

http://www.rollthepotato.net/~john/nipguide.pdf

See page 18.

**Comment by aravind3134** [comment]
Thanks for your help! The insert worked fine without any problems. 

Have a great evening!
