### ISSUE TITLE
Cannot open heic file

### ISSUE THREAD

**Issue by mvbrn** [libvips/pyvips#117]
I have `vips-dev` and `libheif-dev` installed on docker container with `python:3.7-alpine`.
Trying to execute next:
```
>>> import pyvips
>>> image = pyvips.Image.new_from_file('example.heic', access='sequential')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/pyvips/vimage.py", line 217, in new_from_file
    raise Error('unable to load from file {0}'.format(vips_filename))
pyvips.error.Error: unable to load from file b'example.heic'
  VipsForeignLoad: "example.heic" is not a known file format
```

What am I doing wrong?

**Comment by jcupitt** [comment]
Hello, you need to build libvips from source against libheif-dev. 

Check the summary at the end of libvips configure carefully and make sure you have `yes` for libheif.

**Comment by SunnyWeiLucky** [comment]
hi ,I encountered a problem。I compile libvips from git, and add many dependencies,.
When I ./autogen.sh, I get 
![image](https://user-images.githubusercontent.com/30258429/70981822-dc63f680-20f0-11ea-97c4-8a91526ffad0.png),
When ./configure, also get it.But when I use api  VImage::new_from_file ,I'm so depressed to get Error
![image](https://user-images.githubusercontent.com/30258429/70982261-a8d59c00-20f1-11ea-93a0-3e405f549926.png)

Can you help me?

**Comment by jcupitt** [comment]
Hi, first double-check that heifload really is built:

```
$ vips heifload
load a HEIF image
usage:
   heifload filename out [--option-name option-value ...]
where:
   filename     - Filename to load from, input gchararray
   out          - Output image, output VipsImage
optional arguments:
... etc.
```

If that works, then try uploading your test file somewhere and I'll have a look.

**Comment by jcupitt** [comment]
You might need to check that your libheif has been built with libde265 (the decode library).

**Comment by SunnyWeiLucky** [comment]
sorry ,I check the vips heifload failed.
![image](https://user-images.githubusercontent.com/30258429/70984547-a5441400-20f5-11ea-92a8-c7cc5713b2a5.png)
What's the problem

**Comment by jcupitt** [comment]
Try:

```
$ pkg-config libheif --variable builtin_h265_decoder
yes
```

If you see "no", your libheif has been built without decode support.

**Comment by SunnyWeiLucky** [comment]
Thanks,I compile libheif that i do not configurate libde265 also from git .
First I Recompile libheif with libde265 ,then compile libvips and the vips open heic normally.
Thanks again for helping me solve this problem

**Comment by jcupitt** [comment]
Glad it's working!
