### ISSUE TITLE
dzsave_buffer()  VipsOperation: class "dzsave_buffer" not found

### ISSUE THREAD

**Issue by adoniscyp** [libvips/pyvips#119]
Hey :) 

I am trying to convert images to DZI format and then store them to S3. 
I have been using the dzsave which converts the image to DZI and saves the tiles to the drive but this proves to be too slow. 
If I understand correctly  dzsave_buffer() converts to DZI in memory? 
Unfortunately dzsave_buffer() fails with "VipsOperation: class "dzsave_buffer" not found". Dzsave works just fine. 

Python 3.6.8
pyvips==2.1.8 (i dont recall compiling it, most probably installed from package manager) 

1. Does dzsave_buffer converts to DZI and stores it to memory? 
2. any tips to get it to work?

**Comment by jcupitt** [comment]
Hello @adoniscyp,

Perhaps your libvips is too old? `dzsave_buffer` was added in 8.5. It won't be any faster than dzsave, however.

For speed, you need to give more information about what you are doing. What image source are you using, what platform are you running on, how are you writing to S3, etc. etc.

A simple speedup is to make a zip file rather than writing a directory tree. Experiment with:

```
vips dzsave huge.svs x.zip
```

For example. It will write a single uncompressed zip rather than a tree of 1000s of files. If file creation is slow (as it is on Windows, for example), you'll find making a zip is much more efficient.

**Comment by adoniscyp** [comment]
Hey John, 
Thank you for the prompt reply. 
What I was trying to do is to optimize the S3 put operation by converting the large SVS on memory and then streaming to S3, hence the need for the dzsave_buffer operation. 
You are correct, it seems that I was using the latest libvips from the ubuntu repo which is Libvips42 (8.4.5-1build1). I compiled from source following https://github.com/libvips/libvips/wiki/Build-for-Ubuntu and now  
Vips -v
vips-8.7.0-Mon Sep 10 13:35:49 UTC 2018
For some reason dzsave_buff could still not be found. 
In any case I focused my efforts to the real problem - that is S3 is not optimized for small files and on top of that S3 charges for get requests, so probably converting to DZI with default tile_size would be costly. 
I ended up using the max-tile-size of 8192 resulting in images of 7-9MB instead of 7-9KB. 
For 1GB SVS it used to take 1hour, now it takes 2 minutes and it can be further optimized later on. 
Thanks for your help. If you are curious or need more context please see: https://docs.google.com/spreadsheets/d/1ic9WEudnBOv9uNLwlUXmyWqP92sKhP_5jmzNflFeatA/edit#gid=0

**Comment by jcupitt** [comment]
That's good!

With such large tiles, will your users will now see relatively poor interactive performance? Or does the S3 latency make that unimportant?

Friends solve this problem with zips and then serving tiles from them, though I'm unsure if they are also using S3.

**Comment by adoniscyp** [comment]
The performance is pretty decent on our line. While you are browsing the slide, you get 10MB/s spikes. 
I still have some testing to do by throttling the download and checking the performance. Reducing the title size to 8192/2 or 8192/4 I think will offer comparatively good S3 upload while reducing the network pressure. CDN/extra cashing can also help. 

Curious to learn more about the ZIP approach. Assuming the  upload is a ZIP, does it get extracted on upload on S3 with lambda and then served as deepzoom image? 
From your discussion (https://github.com/openseadragon/openseadragon/issues/1420) i see that we will need to write our own openseadragon-zip option. 

I think for the time being, the larger tiles did the trick

**Comment by adoniscyp** [comment]
@jcupitt Hey, quick question and happy to open another thread if needed. 

As discussed above I am using dzsave with tile size 8192. 

For 1GB svs the memory spikes by ~3GB
For 3GB svs the memory spikes by ~8GB

The spikes are only observed when using the big tile sizes
Can you confirm this is the expected behavior?

**Comment by jcupitt** [comment]
dzsave has to buffer enough of the output image to be able to write two entire line of tiles (it generates one set while the other set renders), ie. 8192 * 2 = 16384 scanlines in this case, so yes, memory use should scale with tilesize.

You could try a few other sizes to test for linear behaviour.

**Comment by jcupitt** [comment]
<blockquote>Curious to learn more about the ZIP approach. Assuming the upload is a ZIP, does it get extracted on upload on S3 with lambda and then served as deepzoom image?</blockquote>

No, you leave it as a zip, and then JS in the client reads out the parts of the file it wants.
