### ISSUE TITLE
Cannot save image in HEIF format  

### ISSUE THREAD

**Issue by akaprasanga** [libvips/pyvips#120]
Hi, 
I am able to read heif file but cannot save to heif format.
python= 3.7
pyvips = 2.1.8
libvips binaries = vips-dev-w64-all-8.8.1
```
i = pyvips.Image.new_from_file('A.heif')
i.write_to_file('B.heif')
```
Traceback:
```
  File "D:/Work/PhotoRealistic/vips_photrealistic.py", line 145, in add_textures_vips
    i.write_to_file('B.heif')
  File "C:\Users\PC\AppData\Local\Programs\Python\Python37\lib\site-packages\pyvips\vimage.py", line 497, in write_to_file
    raise Error('unable to write to file {0}'.format(vips_filename))
pyvips.error.Error: unable to write to file b'B.heif'
  VipsForeignSave: "B.heif" is not a known file format
```

**Comment by kleisauke** [comment]
The official libvips Windows binaires doesn't include the libx265 dependency in the `-all` variant (so only decoding HEIC files works). See [here](https://github.com/libvips/build-win64/pull/26) for the motivation behind this.

If you want to save in HEIF format, you can try the MXE binaries here:
https://github.com/libvips/build-win64-mxe/releases

**Comment by akaprasanga** [comment]
Thanks a lot. I will close this issue!

**Comment by kleisauke** [comment]
Note that dependencies of the MXE binaries are regularly updated (using a "rolling release" model). Things might break, but in reality, it's quite stable.

If you have any problems with these binaries, please let me know.

**Comment by akaprasanga** [comment]
Thanks. Sure
