### ISSUE TITLE
Composite of Two Images Documentation and Enum Issues

### ISSUE THREAD

**Issue by John-P** [libvips/pyvips#121]
I am trying to use the composite function to combine a base image with an overlay. Looking at the docs there is a [composite2 method on Image](https://libvips.github.io/pyvips/vimage.html#pyvips.Image.composite2). However, when I try to call this as follows:

```python
composite = base.composite2(overlay, 'over')
```

I get the error: 

```
Error: no such operation composite2
  VipsOperation: class "composite2" not found
```

Instead I tried the composite method just above in the documentation (there is no link) which says it is a static method of `Image`:

```python
composite = pyvips.Image.composite([base, overlay], 'over')
```

```
TypeError: composite() missing 1 required positional argument: 'mode'
```

On reflection with `inspect.getsource` (or by looking at the [top of the same](https://libvips.github.io/pyvips/vimage.html#pyvips.Image.composite) page and then clicking source) I noticed that this is not the case.

```python
    def composite(self, other, mode, **kwargs):
        """Composite a set of images with a set of modes."""
        if not isinstance(other, list):
            other = [other]
        if not isinstance(mode, list):
            mode = [mode]

        # modes are VipsBlendMode enums, but we have to pass as array of int --
        # we need to map str->int by hand
        mode = [GValue.to_enum(GValue.blend_mode_type, x) for x in mode]

        return pyvips.Operation.call('composite', [self] + other, mode,
                                     **kwargs)
```

I then tried calling it as a method on the base image but this resulted in an enum error:

```python
composite = base.composite(overlay, 'over')
```

```
Error: no value over in gtype NULL (0)
  pyvips: no such enum type
```

I may be doing something wrong here but it looks to me like something isn't right here. Is it just a case of a missing mapping from strings to [the required enum](https://libvips.github.io/libvips/API/current/libvips-conversion.html#VipsBlendMode) integers?

**Comment by jcupitt** [comment]
Hello @John-P,

It sounds like your libvips is too old. `composite` was added in libvips 8.6, back in 2017. 

pyvips is a very "thin" binding -- all it does is expose the operations available in your libvips binary, so if your libvips does not have it, it won't be in pyvips either. There is a little extra help for `composite`, but not much.

What platform and libvips are you using?

**Comment by John-P** [comment]
Hello @jcupitt,

Thank you for your quick reply. I am using Ubuntu 18.04 and installed the latest version of libvips in apt which turn out is 8.4.5 and so would explain why I'm having issues here. I can try compiling from source instead.

**Comment by jcupitt** [comment]
There's a Dockerfile here that builds libvips 8.8.1 on Ubuntu 18.04. It might be helpful:

https://github.com/jcupitt/docker-builds/blob/master/ruby-vips-libvips-ubuntu18.04/Dockerfile

You could add some other packages: check the table at the end of configure and make sure the stuff you need has `yes` next to it.

**Comment by John-P** [comment]
I managed to compile from the tar ok with openslide support etc. However, I get two binaries: vips and vips-8.8. vips gives me and error but vips-8.8 does not:

```
(vips:11753): VIPS-WARNING **: 14:22:02.014: ABI mismatch

(vips:11753): VIPS-WARNING **: 14:22:02.014: library has ABI version 0

(vips:11753): VIPS-WARNING **: 14:22:02.014: application needs ABI version 42
vips_version: flag not 0, 1, 2
vips_version: flag not 0, 1, 2
vips_version: flag not 0, 1, 2
vips_version: flag not 0, 1, 2
vips_init: ABI mismatch
```

I am also unsure how to make sure that pyvips will use this new version. Is having it first in my PATH enough?

**Comment by John-P** [comment]
I reinstalled with apt in the end. Turns out I had just accidentally installed an old version and hadn't noticed that there was in fact a newer one in apt. Thank you for the help.

**Comment by jcupitt** [comment]
`vips-88.` is just a simple bash script that sets the environment variables for you.

To get the `vips` binary working, you need to make sure that `/usr/local/lib` is in your library search path. You can set `LD_LIBRARY_PATH` or `ld.so.conf`. You might need to set `PATH` too, it depends how you've set up your session.

Once `vips` is working, pyvips should be able to find the library.
