### ISSUE TITLE
Issue with openslideload

### ISSUE THREAD

**Issue by Richarizardd** [libvips/pyvips#122]
Hi,

I am interested in using pyvips for processing whole-slide images, and possibly using this package to replace openslide-python for patch generation, image mosaicing, etc..

I'm navigating the docs, but I am having issues with simply being able to load a WSI using openslideload. The WSI I am using for testing purposes is from the CAMELYON dataset.

```python
pyvips.Image.openslideload(filename='normal_091.tif', level=0)
```
You can download the TIFF example via this link:
ftp://parrot.genomics.cn/gigadb/pub/10.5524/100001_101000/100439/CAMELYON16/training/normal/normal_091.tif

**Comment by jcupitt** [comment]
Hello @Richarizardd,

What version and platform are you using? It seems to be working for me with libvips 8.8 on Ubuntu:

```
$ python3
Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvips
>>> x = pyvips.Image.openslideload("normal_091.tif", level=0)
>>> x.width
97792
>>> x.height
215552
>>> 
```

**Comment by Richarizardd** [comment]
Hi @jcupitt,

Thank you for getting back to me so soon. I'm using macOS, and installed libvips and pyvips using homebrew (version 8.8.1) and pip (version 2.1.8).

**Comment by jcupitt** [comment]
Could you be using the Apple Python? It's unfortunately rather limited now and you need to install the brew one.

On my mac I see:

```
john@katamata:~/pics/openslide$ which python3
/usr/local/bin/python3
john@katamata:~/pics/openslide$ python3
Python 3.7.4 (default, Jul  9 2019, 18:13:23) 
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvips
>>> pyvips.version(0)
8
>>> pyvips.version(1)
8
>>> pyvips.version(2)
1
>>> x = pyvips.Image.openslideload("normal_091.tif")
>>> x.width
97792
>>> x.height
215552
```

Alternatively, pyvips is now in conda, that might be a simpler install.

**Comment by NeelKanwal** [comment]
Hi,
Is it possible to go back from DZI filed to tiff?
I was looking to see whether we can combine jpeg images to pyramid shape files.

Thank you

**Comment by jcupitt** [comment]
Sure, see for example: https://stackoverflow.com/a/58927878/894763
