### ISSUE TITLE
Is it possible to profile (performance) this binding?

### ISSUE THREAD

**Issue by juona** [libvips/pyvips#127]
Hi! In the libvips blog I saw that one can turn on profiling using this flag: `--vips-profiling`. Is it possible to profile the VIPS Python binding? Basically, I'd like to know how much time my application spends loading files, then manipulating them and then saving them.

**Comment by jcupitt** [comment]
Hi, you can use the `VIPS_PROFILE` env var to turn on profiling, for example:

```
$ cd ~/GIT/pyvips/examples
$ VIPS_PROFILE=1 ./watermark.py ~/pics/k2.jpg x.jpg "hello world!"
recording profile in vips-profile.txt
```

Then load the profile data and analyze like this:

```
$ vipsprofile 
reading from vips-profile.txt
loaded 3290 events
total time = 0.198496
name		alive	wait%	work%	unkn%	memory	peakm
     worker 2	  0.07	 20	39.1	40.9	 2.13	 2.13	
     worker 3	  0.07	 27.5	32.9	39.6	 1.05	 1.05	
     worker 4	 0.071	 30.9	35.8	33.3	 1.07	 1.07	
     worker 5	 0.071	 20.3	37.9	41.8	 2.11	 2.11	
    wbuffer 6	 0.073	 84.9	15.1	0.0455	 0	 0	
    wbuffer 7	 0.073	 84.7	15.2	0.0427	 0	 0	
       main 8	   0.2	 35.8	0	64.2	 -4.05	 0.542	
peak memory = 6.89 MB
leak! final memory = 2.3 MB
writing to vips-profile.svg
```

And it renders:

![x](https://user-images.githubusercontent.com/580843/66473505-49bb3180-ea87-11e9-96ce-34bc792175d9.png)

**Comment by juona** [comment]
Brilliant, that answers the question, I believe : ]
