### ISSUE TITLE
Is it possible to define the pyramid level count when using tiffsave?

### ISSUE THREAD

**Issue by AGFoersch** [libvips/pyvips#128]
I'm a newcomer to vips / pyvips (and GitHub and Coding for that matter) so please excuse any blatant errors within my question. 

I'm working with whole slides images of histopathologic slides and was really happy to find that pyvips can actually **write / save** such files. Additionally, with `pyvips.Image.openslideload` one can make use of the OpenSlide library, which we utilize regularly. The problem is, that when I use `pyvips.tiffsave` and specify `pyramid=True` it changes the number of levels and I have not found a way out of this. The code I try to test this looks something like this:

```
import openslide
import pyvips

img_os = openslide.OpenSlide("SomeWSI.svs")
img_pv = pyvips.Image.openslideload("SomeWSI.svs")

save = "Test.svs"
img_pv.tiffsave(save, tile=True, compression='lzw', bigtiff=True, pyramid=True, Q=100)

img_new = openslide.OpenSlide("Test.svs")

print("Saved via pyvips: ", img_new.level_count)
print("Original file: ", img_os.level_count)
```
and the Output is: 

```
Saved via pyvips:  10
Original file:  3
```

I'm surely missing something so any help would be much appreciated.

**Comment by jcupitt** [comment]
Hello @AGFoersch,

Standard TIFF pyramids always have powers of two for level sizes, that is, for each level down the pyramid, you halve each dimension and round up.

With slide formats, it varies by manufacturer. Some use powers of two, but some use powers of 4. Or even odder systems. If you are reading one of these stranger systems and writing as a regular TIFF pyramid, the number of layers will change.

**Comment by AGFoersch** [comment]
Thank you very much for this detailed explanation @jcupitt . Is there a way to manually specify the number of levels when you use `pyvips.Image.tiffsafe`. Like with an additional argument or by changing the default? I tried different types manufacturers, but when I use `pyvips.Image.tiffsafe` it will always default to 10 levels.

**Comment by jcupitt** [comment]
The number of levels created by `tiffsave` is set by the size of the image. Larger images will need more levels.

**Comment by AGFoersch** [comment]
Okay, got it. I just saw that there were other files with more than 10 levels so 

> The number of levels created by `tiffsave` is set by the size of the image. Larger images will need more levels.

makes a lot of sense. Thank you so much. 

Last question if I may - what parameter of  `pyvips.Image.tiffsafe` then mainly determines the size of the image? Is it the type of compression? Is it the Q Factor? Something else? Let's say I have an image / array of 100.000 x 50.000 pixels, what do I need to change to get one pyramid tiff with 3 layers and another one with 10?

Sorry to bother you that immensely on a Sunday ...

**Comment by jcupitt** [comment]
By size, I mean number of pixels.

A 50,000 x 50,000 pixel image will have these layers:

0 = 50,000 
1 = 25,000
2 = 12,500
3 = 6,250
4 = 3,125
5 = etc.

**Comment by AGFoersch** [comment]
Okay, I think I understand. Thank you for your patience, support and everything else, John.
