### ISSUE TITLE
Instantiate pyvips.Image with pillow Image?

### ISSUE THREAD

**Issue by devlfm** [libvips/pyvips#137]
I have pil Image with some drawings, and I need to create an instance of pyvips Image with the content of pil Image. How to?

**Comment by devlfm** [comment]
Got it!

```
imgByteArr = io.BytesIO()
img.save(imgByteArr, format='PNG')

vipImg = pyvips.Image.new_from_buffer(imgByteArr.getvalue(), "")
```

**Comment by jcupitt** [comment]
That's going via a PNG image. You can simply transfer the pixels directly:

https://libvips.github.io/pyvips/intro.html#numpy-and-pil

It'll be much faster -- PNG encode and decode is glacial.

What are you using PIL for? There might be a pyvips equivalent.

**Comment by jcupitt** [comment]
There's a complete example in the pyvips `examples/` area:

https://github.com/libvips/pyvips/blob/master/examples/pil-numpy-pyvips.py

**Comment by devlfm** [comment]
I'm using to create one stripe with a barcode and some labels.
I'm using Libre Barcode 128 font and I'm drawing texts. Also getting the xres/yres of the target image to know the size of the stripe.

**Comment by jcupitt** [comment]
You can go via SVG as well:

```python
#!/usr/bin/python3
  
import sys
import barcode
import pyvips

ean = barcode.get_barcode_class('ean13')
svg = ean('5901234123457').render()
barcode = pyvips.Image.new_from_buffer(svg, "", dpi=200)

barcode.write_to_file(sys.argv[1])
```

Then:

```
$ pip3 install python-barcode
Collecting python-barcode
  Downloading https://files.pythonhosted.org/packages/10/aa/faaabf936994dc3457f25b2222e2feb8b1ba391df033ce94bc99f0ba17da/python_barcode-0.10.0-py3-none-any.whl (211kB)
    100% |████████████████████████████████| 215kB 1.8MB/s 
Installing collected packages: python-barcode
Successfully installed python-barcode-0.10.0
$ ./draw-barcode.py x.png
```

To make:

![x](https://user-images.githubusercontent.com/580843/69334929-9f245a00-0c53-11ea-9f41-56a5aba38805.png)

**Comment by devlfm** [comment]
I'm having troubles getting barcode installed on Python27. I tryed to install pyvips on Python3 because on Python38 but I'm having errors. Also on barcode I can't set options for the size in height of the barcode and removing label bellow. So with all those problems I end up using Python27 and the font. But if I get it to work I would prefer to just use pyvips and barcode svg indeed.. 
Thank you for all the advices, you have a lot of knowledge and very helpful.

**Comment by jcupitt** [comment]
Huh you're right, it's all broken on 2.7. That's a shame.

On 3.7 you can remove the label and border with:

```python
ean = barcode.get_barcode_class('ean13')
svg = ean('5901234123457').render({
    "human": " ", 
    "text_distance": -0.8,
    "quiet_zone": 0.2
})
barcode = pyvips.Image.new_from_buffer(svg, "", dpi=200)
```

To make:

![x](https://user-images.githubusercontent.com/580843/69345681-6e4f1f80-0c69-11ea-91af-79786ce9bd17.png)

I've not tried pyvips on Python 3.8, I should have a look.

**Comment by devlfm** [comment]
Nice! So to crop the height of the barcode I would then use the methods gravity on pyvips.. sounds doable 😀

**Comment by jcupitt** [comment]
Sure, or just `.crop()`.
