### ISSUE TITLE
Convert Adobe RGB to sRGB

### ISSUE THREAD

**Issue by devlfm** [libvips/pyvips#138]
Hi!
reading this https://github.com/libvips/ruby-vips/issues/146 I understand that is possible to convert, I just don't know how on pyvips. I did ```result = mainImage.colourspace(pyvips.Interpretation.SRGB)``` but opening the image on photoshop, it says the image is in AdobeRGB.

What are the steps? Do I need to have the AdobeRGB.icc path when calling colourspace? If mainImage.interpretation='srgb', how do I know what is the embedded icc on exif?

**Comment by jcupitt** [comment]
Most images will have their profile embedded (adobe98 in your case), so you just do:

```
srgb = a98.colourspace("srgb")
```

**Comment by jcupitt** [comment]
Thinking about it, that won't be enough.

You need:

```python
srgb = a98.icc_transform("srgb")
```

You can see what's happening like this. First, take an untagged JPG image:

```shell
$ vipsheader -f icc-profile-data k2.jpg
vipsheader: vips_image_get: field "icc-profile-data" not found
```

Untagged jpg images are assumed to be srgb. You can transform it to a98 and embed a profile like this:

```shell
$ vips icc_export k2.jpg x.jpg --output-profile /usr/share/color/icc/colord/AdobeRGB1998.icc 
$ vipsheader -a x.jpg | grep profile
icc-profile-data: 16340 bytes of binary data
```

You can view it and the original jpg in a web browser and they should look identical, even though the pixel values are different.

Now transform the a98 image to srgb like this:

```shell
$ vips icc_transform x.jpg y.jpg srgb
$ vipsheader -a y.jpg 
icc-profile-data: 6922 bytes of binary data
```

`y.jpg` is now an srgb image with an embedded srgb profile.

**Comment by devlfm** [comment]
Thank  you for the hint! I missed the  `icc_transform` method on the docs. I'll try that out and let you know the result.

**Comment by jcupitt** [comment]
You probably saw, there's an almost identical question here: https://github.com/libvips/pyvips/issues/140

**Comment by devlfm** [comment]
Indeed! Thank you for pointing me that.. was very helpful too because I wanted also to convert only when not present.
I ended up passing the path to the icc instead of default "srgb", because on photoshop it says that the color profile is "sRGB" and I wanted to keep the usual "sRGB IEC61966-2.1". Don't know if are different (I guess not), but for keeping the designers happy its better to show them a name that they are used.

**Comment by jcupitt** [comment]
Exactly, the magic `"srgb"` string just selects an sRGB profile that's built into libvips, but (as you say) you can use your own. 

There's a default built-in `"cmyk"` profile too, which can be handy.
