### ISSUE TITLE
VipsOperation: class "thumbnail" not found (pyvips 2.1.8)

### ISSUE THREAD

**Issue by mgebundy** [libvips/pyvips#146]
Similar to #46 but I'm definitely up to date. I see tons of examples of folks using `thumbnail` with pyvips, but I don't see it defined in this codebase at all, I'm stumped.

pyvips.error.Error: no such operation thumbnail
  VipsOperation: class "thumbnail" not found

`pip show pyvips`:

```
Name: pyvips
Version: 2.1.8
Summary: binding for the libvips image processing library, ABI mode
Home-page: https://github.com/libvips/pyvips
Author: John Cupitt
Author-email: jcupitt@gmail.com
License: MIT
Location: /home/mitch/.local/lib/python2.7/site-packages
Requires: cffi
```

**Comment by jcupitt** [comment]
Hello, `thumbnail` is called via `__getattr__` --- pyvips sees that the method is not defined and forwards the call to the underlying libvips library.

Yes, you'll need to build your own libvips if you're stuck on an old ubuntu. There's a dockerfile here that builds libvips on ubuntu 16.04:

https://github.com/jcupitt/docker-builds/blob/master/php-vips-ubuntu-16.04/Dockerfile

You'll want to skip the php stuff, obviously.
