### ISSUE TITLE
Memory leak with libvips 8.9

### ISSUE THREAD

**Issue by homm** [libvips/pyvips#147]
I have a very simple code:

```python
import pyvips
im = pyvips.Image.new_from_file('../imgs/anoir-chafik-37957.jpg')
while True:
    im.shrink(16, 16).write_to_file('_vips.16x.png')
```

It constantly consuming more and more memory until it hangs up.

<img width="800" alt="Screenshot 2020-01-02 at 16 23 48" src="https://user-images.githubusercontent.com/128982/71669007-4c72ad80-2d7c-11ea-8b35-eab238f3a55f.png">

**Comment by jcupitt** [comment]
Oh no! I'll have a look, thanks for the report,

**Comment by jcupitt** [comment]
I founf a couple of places where resources were being freed when images were disposed, rather than at the end of evaluation.

With this program:

```python
#!/usr/bin/python3

import sys
import pyvips

im = pyvips.Image.new_from_file(sys.argv[1])
for i in range(10000):
    print(f"loop {i} ..")
    im.shrink(16, 16).write_to_file(sys.argv[2])
```

I now see:

iterations | RES
---- | ----
500        | 55020
1000      | 55060
3500      | 55124
9600      | 55092

So perhaps just memory fragmentation now.

Thanks for pointing this out!

**Comment by homm** [comment]
> resources were being freed when images were disposed

Surprisingly, this also works:

```python
#!/usr/bin/python3

import sys
import pyvips

for i in range(10000):
    im = pyvips.Image.new_from_file(sys.argv[1])
    im.shrink(16, 16).write_to_file(sys.argv[2])
```

On each iteration, the old `im` is freed so memory shouldn't grow even without the fix, but it does.

**Comment by homm** [comment]
`.resize()` is also leaking, perhaps it uses `.shrink()` internally.

**Comment by jcupitt** [comment]
<blockquote>
On each iteration, the old im is freed so memory shouldn't grow even without the fix, but it does.
</blockquote>

That's the libvips operation cache. It'll keep the decoded image around in case it is needed again.

Try this:

```python
for i in range(10000):
    print(f"loop {i} ..")
    im = pyvips.Image.new_from_file(sys.argv[1], access="sequential")
    im.shrink(16, 16).write_to_file(sys.argv[2])
```

The `sequential` tag will prevent the image being cached and it'll be unreffed and decoded again each time. You shouldn't see memory growth, even without that patch.

**Comment by jcupitt** [comment]
It's not strictly a leak -- if you let the program run to the end, all memory was being be freed. 

Those patches just make libvips free earlier and more aggressively.

**Comment by jcupitt** [comment]
This is all released now, so I'll close.
