### ISSUE TITLE
Resize at a given width

### ISSUE THREAD

**Issue by celinede** [libvips/pyvips#149]
Hello,
Is there a way to resize a tiff at a given width?
I know `vips resize` with a scaling factor, however it is important for me that the images are rescaled with a width of 1000 pixels precisely.
Thanks for your help!
Céline

**Comment by jcupitt** [comment]
Hell @celinede,

Yes, `thumbnail` will size to a specific number of pixels.

```python
small = pyvips.Image.thumbnail("some/file/name", 1000)
```

https://libvips.github.io/libvips/API/current/libvips-resample.html#vips-thumbnail

`thumbnail_image` will do it from an image source:

```python
small = big.thumbnail_image(1000)
```

https://libvips.github.io/libvips/API/current/libvips-resample.html#vips-thumbnail-image

**Comment by celinede** [comment]
thank you very much !
