### ISSUE TITLE
How to create a tiled TIFF without requiring to keep the whole image in memory?

### ISSUE THREAD

**Issue by ebnertom** [libvips/pyvips#155]
Hi,
I have the following problem:
I want to create a tiled TIFF, which is rather large (>200000x100000) such that it doesn't fit into RAM memory.
I am creating individual tiles (1024x1024, numpy arrays) dynamically in python and want to add them to the resulting TIFF.
Is that possible with vips, without requiring to keep the whole image in memory?

I've tried lots of different approaches with vips, however, all of them resulted in allocating lots of RAM memory.

The following sourcecode is one example of an approach that I've tried.
1. create tiles, and write them to disk: (create_tiles() function)
2. fuse all the tiles together to a TIFF (combine_tiles_to_wsi() function)

```python
import cv2
import numpy as np
import pyvips


def create_tiles():
    w = 200
    h = 100

    im = np.zeros((1024, 1024, 3))
    for i in range(h*w):
        cv2.imwrite('tmp/tiles/{:07d}.jpg'.format(i), im)


def combine_tiles_to_wsi():
    w = 200
    h = 100

    print('creating images from array')
    vimgs = [pyvips.Image.new_from_file('tmp/tiles/{:07d}.jpg'.format(i), access='sequential') for i in range(h*w)]

    print('joining arrays')
    vimg = pyvips.Image.arrayjoin(vimgs, across=w)
    print('writing to files')
    vimg.write_to_file('test.tiff', tile=True, tile_width=1024, tile_height=1024,
                       pyramid=True,
                       compression='jpeg',
                       )

if __name__ == "__main__":
    create_tiles()
    combine_tiles_to_wsi()

```

When I run the code above vips starts eating up my RAM memory during the call to "vimg.write_to_file". At least more than 30GB of RAM are consumed by the program. (after that I had to kill it)
I am using "pyvips==2.1.11" with "vips-8.7.0-Mon Sep 10 13:35:49 UTC 2018" on Ubuntu.
I have also tried setting `pyvips.cache_set_max(0)` without success

**Comment by jcupitt** [comment]
Hello @ebnertom,

libvips will open all your jpg images during processing and won't free the cache linked to each one until the end of the write, so I'm afraid you will see high memory use. The next libvips might have an improvement here.

You could try using vips (`.v`) images for these intermediates. They take up lots of space on disc, but not much in memory.

You could also try reworking your numpy code in libvips, though of course I don't know if that's practical. What is the numpy code doing?

8.7 is a little old now. You could try 8.9, it has some improvements.

**Comment by jcupitt** [comment]
You could also assemble your image in sections, of course.

**Comment by ebnertom** [comment]
Thank you very much for your fast response.
Indeed, the approach using vips(`.v`) images for the intermediates requires significantly less memory and works for me.

What do you mean with reworking the numpy code in libvips?

Is directly writing to a tiff possible without creating intermediates? (and of course without keeping all intermediates in memory)
The intermediates (np.arrays) are created one after each other by inference of some machine learning algorithm.
The best thing would be for me to write those np.arrays directly to a tiff in a way, that they are written to disk and freed from memory.

so something like the following pseudo code:
`
for all tiles:
 tile = generate_tile()
 tifffile.append(tile)
`

**Comment by jcupitt** [comment]
Yes, that's something that's been talked about for the next version.

At the moment, pyvips lets you pull areas of pixels from an openslide image very quickly with `Region.fetch()` (we've used this for some ML work), but there's no easy way to do the inverse (write a large image from the output of a CNN).

Perhaps in 8.10.

**Comment by ebnertom** [comment]
Thank you very much for your answers!
I am looking forward for that feature :)

**Comment by cookmscott** [comment]
Hi folks! I checked through the 8.10 [release notes](https://github.com/libvips/libvips/releases/tag/v8.10.0) and nothing is jumping out to me for a better way to append tiles (aka individual images) to a TIFF without creating intermediaries and racking up memory usage for vips. Is above still the best option or did I miss a new feature? :) 

As an additional option.. if I save my intermediary files as TIFFs with equal compression, can I join/write them without reprocessing or reading the entire image into memory? 

(sorry for hijacking the thread, some folks don't like comments on closed issues but hoping this will help close the loop!)

**Comment by jonasteuwen** [comment]
+1 for the feature to write a tiff tile by tile without keeping the whole thing in memory.

**Comment by hubutui** [comment]
Maybe you could try [rasterio](https://github.com/rasterio/rasterio), which let you write the tiled tiff block by block. See also the doc [Windowed reading and writing](https://rasterio.readthedocs.io/en/stable/topics/windowed-rw.html#writing). You could write something like this:

```python
width = 200000
height = 200000
with rasterio.open(
        '/tmp/example.tif', 'w',
        driver='GTiff', width=width, height=height, count=3, compress="lzw",
        tiled=True) as dst:
    for tile_data in tile_data_generator:
        # create the window, (x, y) is the top-left coord
        # w, h = tile_data.shape[:2]
        window = Window(x, y, w, h)
        dst.write(tile_data, window=window)
    # if you need pyramid
    dst.build_overviews(factors=[2, 4, 8, 16])
```
You can adjust the window size according to your resources.
