### ISSUE TITLE
Character co-ordinates in the image

### ISSUE THREAD

**Issue by zabir-nabil** [libvips/pyvips#156]
Hello,
thanks for your amazing library.
Is it possible to get the coordinates (bounding box) of each character in the image using the library? I'm trying to make a synthetic scene-text dataset using your library.

**Comment by jcupitt** [comment]
Hello @zabir-nabil,

What do you mean by "character"? Is this an image of text? Post an example image.

**Comment by zabir-nabil** [comment]
```
image = pyvips.Image.text("""
<span font="URW Gothic" size="24000">Hello</span>
<span font="Times" size="48000">World!</span>
""", dpi=300)
image.write_to_file("x.png")
```

It will generate an image like this -> https://user-images.githubusercontent.com/580843/72679898-cb215780-3aab-11ea-8b4c-e3ebcbf9e1e4.png

I wanted to know the coordinates/bounding box/location information of H, e, l, l, o, ... in the image. Is it possible?

**Comment by jcupitt** [comment]
Sorry, no.

You could render the text a character at a time. Use `xoffset` and `yoffset` to line up the baseline.

**Comment by jcupitt** [comment]
Here's how to render a character at a time:

```python
#!/usr/bin/python3

import pyvips

text = "gry Ff!"

result = pyvips.Image.black(1, 1)
x = 0
y = 0

for i in range(len(text)):
    if text[i] == " ":
        x += 10
    else:
        char = pyvips.Image.text(text[i], dpi=300)
        print(f"char = {text[i]}")
        print(f"width = {char.width}")
        print(f"height = {char.height}")
        print(f"xoffset = {char.xoffset}")
        print(f"yoffset = {char.yoffset}")

        result = result.insert(char,
                               x + char.xoffset, y + char.yoffset,
                               expand=True)

        x += char.width + 3

result.write_to_file("x.png")
```

The program makes this:

![x](https://user-images.githubusercontent.com/580843/73859477-02c12b00-4832-11ea-9fe2-009f7e7b9494.png)

You can see the base of the characters lines up correctly, though the kerning isn't great.

**Comment by zabir-nabil** [comment]
Great! @jcupitt Thanks for the amazing support. I will be testing it on Unicode characters. Hope this works! Thanks again.
