### ISSUE TITLE
Create pyramid tiff from numpy  layers for pathology images

### ISSUE THREAD

**Issue by vankhoa21991** [libvips/pyvips#157]
Hello,

I'm trying to use the pyvips library to reconstruct a tiff/svs file from multiple numpy images of different magnification. The output tiff file could be read by openslide. Which function and parameters should I use for this task?

Thanks for your help.

**Comment by jcupitt** [comment]
Hello @vankhoa21991,

openslide is a read-only library, it can't write slide images. 

You could save as a pyramidal tiled TIFF, that's probably as close as you can get. Something like:

```python
image.write_to_file("x.tif", pyramid=True, tile=True, compression="jpeg")
```

It will create the lower-resolution layers for you.

**Comment by jcupitt** [comment]
Why do you want to create an SVS file? Perhaps there's some other approach.

**Comment by vankhoa21991** [comment]
Thanks for your quick answer, actually I want to create a tiff file that can be read with openslide. This tiff file is created from multiple level of another svs file, except the base. So my intention is to get the numpy array of each level of the source svs, then combine them back into a tiff file, but there are so many option in the pyvips api, e.g. merge join insert. Could you give me an example, with the inputs are 3 levels of numpy arrays with different dimension, to get the output is the tiff file of those images. Thanks

**Comment by vankhoa21991** [comment]
This is an attemp to remove the base from a svs file in fact.

**Comment by jcupitt** [comment]
You can do this at the command-line. Try:

```
$ vips copy CMU-1.svs[level=1] x.tif[pyramid,tile,compression=jpeg]
```

`level=1` means get the second-largest layer out of the image (the largest layer is always layer 0). The options to tiff mean write a pyramid, tile it, and use JPG compression.

It'll load into openslide, but it is just a regular pyramidal TIFF image.

**Comment by vankhoa21991** [comment]
Does the pyvips support this function, and is it possible to remove the largest layer?

**Comment by jcupitt** [comment]
Sure, I posted above ^^

```python
image = pyvips.Image.new_from_file("CMU-1.svs", level=1)
image.write_to_file("x.tif", pyramid=True, tile=True, compression="jpeg")
```

**Comment by vankhoa21991** [comment]
I tried the code and get error of level

image = pyvips.Image.new_from_file("../1_data/CMU-3.svs", level=1)
  File "C:\Users\ELHPC\AppData\Local\Continuum\anaconda3\lib\site-packages\pyvips\vimage.py", line 230, in new_from_file
    string_options=options, **kwargs)
  File "C:\Users\ELHPC\AppData\Local\Continuum\anaconda3\lib\site-packages\pyvips\voperation.py", line 265, in call
    details = intro.details[name]
KeyError: 'level'

**Comment by vankhoa21991** [comment]
> Sure, I posted above ^^
> 
> ```python
> image = pyvips.Image.new_from_file("CMU-1.svs", level=1)
> image.write_to_file("x.tif", pyramid=True, tile=True, compression="jpeg")
> ```

As I understand, this code get the level 1  out of the original svs, then create a new tiff file with only this level. What do I have to do to get more than 1 levels?

**Comment by vankhoa21991** [comment]
I also tried the openslideload, which is the only function that has level as argument, but get the error:

image = pyvips.Image.openslideload("../1_data/CMU-3.svs", level=1)
  File "C:\Users\ELHPC\AppData\Local\Continuum\anaconda3\lib\site-packages\pyvips\vimage.py", line 135, in call_function
    return pyvips.Operation.call(name, *args, **kwargs)
  File "C:\Users\ELHPC\AppData\Local\Continuum\anaconda3\lib\site-packages\pyvips\voperation.py", line 222, in call
    intro = Introspect.get(operation_name)
  File "C:\Users\ELHPC\AppData\Local\Continuum\anaconda3\lib\site-packages\pyvips\voperation.py", line 141, in get
    cls._introspect_cache[operation_name] = Introspect(operation_name)
  File "C:\Users\ELHPC\AppData\Local\Continuum\anaconda3\lib\site-packages\pyvips\voperation.py", line 38, in __init__
    op = Operation.new_from_name(operation_name)
  File "C:\Users\ELHPC\AppData\Local\Continuum\anaconda3\lib\site-packages\pyvips\voperation.py", line 181, in new_from_name
    raise Error('no such operation {0}'.format(operation_name))
pyvips.error.Error: no such operation openslideload
  VipsOperation: class "openslideload" not found

**Comment by jcupitt** [comment]
Ah, your libvips does not have openslide support.

If you are using Windows, you need to download the `-all` zip:

https://github.com/libvips/libvips/releases/tag/v8.9.1

Perhaps you downloaded `-web` by mistake?

**Comment by vankhoa21991** [comment]
Yes you are correct, I did that because I countered an error in conda, but it works now. What do I have to do to get more than 1 levels to the new tif?

**Comment by jcupitt** [comment]
If you set the `pyramid` option, libvips will create all the layers for you.

**Comment by vankhoa21991** [comment]
So I can do something like:

layer1 = pyvips.Image.new_from_file("CMU-1.svs", level=1)
layer2 = pyvips.Image.new_from_file("CMU-1.svs", level=2)

image = layer1 join layer2 vertically # Do you know how to do this?

image.write_to_file("x.tif", pyramid=True, tile=True, compression="jpeg")

**Comment by jcupitt** [comment]
You don't need to make any layers. libvips will do all of that for you.

Try running this:

```python
image = pyvips.Image.new_from_file("CMU-1.svs", level=1)
image.write_to_file("x.tif", pyramid=True, tile=True, compression="jpeg")
```

And examining the output. You will find it has all the layers.

**Comment by vankhoa21991** [comment]
Yes indeed, it's much more convenient than I imagine. Thanks alot for your support.

**Comment by jcupitt** [comment]
Glad it's working!
