### ISSUE TITLE
Update pyvips enums.py

### ISSUE THREAD

**Issue by tony612** [libvips/pyvips#158]
I can't find them in current enums https://libvips.github.io/pyvips/_modules/pyvips/enums.html#BandFormat

**Comment by jcupitt** [comment]
Hello, they are converted here:

https://github.com/libvips/pyvips/blob/master/pyvips/gvalue.py#L94

By introspecting the libvips binary.

**Comment by tony612** [comment]
@jcupitt Could you give me an example? Like how to get string(I think it should be "attention") of VIPS_INTERESTING_ATTENTION.

**Comment by jcupitt** [comment]
It's not really supported API, but yes that should work.

You don't need the extra gvalue, try:

```
>>> pyvips.GValue.from_enum(g, 3)
'attention'
```

Could you explain why you need to be able to turn numbers into strings? You can just use the string:

```
x = pyvips.Image.thumbnail("hello.jpg", 128, crop="attention")
```

**Comment by tony612** [comment]
@jcupitt I know I can use `"attention"`, but I don't know what are all valid strings I can use. And what if I passed a wrong string(maybe a typo). I think what I want is something like `pyvips.enums.BandFormat.CHAR`.

**Comment by jcupitt** [comment]
Ah, I see. Yes, `enums.py` hasn't been updated for a while. It's hand-written, so it's easy to forget.

The php binding has a script to generate the enums automatically. I'll port it to pyvips.

**Comment by jcupitt** [comment]
The enum generator from php-vips:

https://github.com/libvips/php-vips/blob/master/examples/generate_phpdoc.py#L295

**Comment by jcupitt** [comment]
OK, I added a `gen-enums.py` and generated `enums.py`. 

It's missing the docstrings, sadly, we should try to add them back.

**Comment by tony612** [comment]
Great! Thanks!

**Comment by tony612** [comment]
@jcupitt My issue is solved, so I closed this issue. If you want to keep it open for tracking the docstrings issue, please open it.

**Comment by jcupitt** [comment]
I had a quick look at docstrings, and we can't make them from simple introspection of the lib. We'd need to load the xml in `Vips-8.0.gir` and extract from that.

Let's shelve docstrings for now.

**Comment by tony612** [comment]
@jcupitt btw, the API doc https://libvips.github.io/pyvips/ seems not up to date. For example, the method `crop` is missing.

**Comment by jcupitt** [comment]
You're right, the docs hadn't been updated for a while, I've done them now.

Conda is tricky -- the package update is stuck on a broken dependency. Hopefully it'll be resolved soon.

**Comment by jcupitt** [comment]
I had a quick go at generating the enum docstrings:

https://libvips.github.io/pyvips/enums.html

Made by this ugly thing:

https://github.com/libvips/pyvips/blob/master/examples/gen-enums.py

It obviously needs a bit of formatting work.
