### ISSUE TITLE
How can I get thumbnail image faster from Openslide Image?

### ISSUE THREAD

**Issue by tand826** [libvips/pyvips#168]
Hi, I'm trying to get a thumbnail from "CMU-1.ndpi"(https://data.cytomine.coop/open/openslide/hamamatsu-ndpi/CMU-1.ndpi). But it takes more than 10 seconds. Is there any other way to get a thumbnail image faster?

# Sample Code
- takes 12 seconds in average on my PC
```
import pyvips
import timeit
def run():
    slide = pyvips.Image.new_from_file("CMU-1.ndpi")
    thumb = slide.thumbnail_image(500)
    thumb.write_to_file("tn_CMU-1.png")

timeit.timeit(lambda :run(), number=10)
```

# Tried 
- replace write_to_file to pngsave / jpegsave
- from command line `vipsthumbnail CMU-1.ndpi` finishes within a second, but I want to implement without subprocess.call()

# Environment
- macOS 10.14.4
- pyvips 2.1.8
- libvips 8.8.4-Thu Dec  5 16:24:34 UTC 2019 (from brew)

**Comment by jcupitt** [comment]
Hello @tand826,

Don't use `thumbnail_image`. Because the image has already been opened, it can't do any of the shrink-on-load tricks that help make thumbnail fast.

Try:

```python
import pyvips
import timeit
def run():
    slide = pyvips.Image.thumbnail("CMU-1.ndpi", 500)
    thumb.write_to_file("tn_CMU-1.png")

timeit.timeit(lambda :run(), number=10)
```

I would also consider updating to current libvips, 8.9.1. There have been some useful fixes.

**Comment by tand826** [comment]
@jcupitt
Thank you! It works super fast!
