### ISSUE TITLE
Saving pyramid for multidimentional tiff.

### ISSUE THREAD

**Issue by petoor** [libvips/pyvips#170]
Hi John.

The tiff format should be able to support saving pyramids, I've asked that question here : https://github.com/ome/design/issues/104

in pyvips, I am able to save a 2D image with a pyramid fine, and then get the layer of the pyramid with the page argument in tiffload.

But if I save a tiff image with just 2 dimentions (for instance, z =2 ) and save it with the pyramid=True argument, it doesnt seem to work.

Minimum working example. 
teststack.tif is here : 
[teststack.zip](https://github.com/libvips/pyvips/files/4453048/teststack.zip)

```
import pyvips

img2d = pyvips.Image.tiffload("teststack.tif")
img3d = pyvips.Image.tiffload("teststack.tif", n=2)

img2d.tiffsave("img2d.tif", pyramid=True, tile=True)
img3d.tiffsave("img3d.tif", pyramid=True, tile=True)

img2dback = pyvips.Image.tiffload("img2d.tif", page=1)
img3dback = pyvips.Image.tiffload("img3d.tif", page=1)

print(img2dback)
print(img3dback)

```

Which gives

```
<pyvips.Image 300x300 uchar, 3 bands, srgb>
<pyvips.Image 600x600 uchar, 3 bands, srgb>
```

Is there any way to retrieve the pyramid of the image which contains an image in the z dimension?

**Comment by jcupitt** [comment]
Hello @petoor,

Sorry, I don't think 3D volumes will pyramid with libvips.

libvips uses pages for pyramid layers, not subifds, so it can't store the extra dimension.

**Comment by petoor** [comment]
Alright. 

Is there any plan of implementing this since pyvips both support both dicom and tiff?
It would also be nice to get a warning / error if the user tries to save pyramid on multidimensional data.

**Comment by jcupitt** [comment]
It would not be easy to implement -- you'd need to change the way libvips represents pyramid layers, and it would break compatibility with other pyramid builders.

**Comment by jcupitt** [comment]
Or rather, you'd need to *not* break compatibility with other pyramid builders, so you couldn't easily add this as a feature of the tiff saver. You'd need a new pyramid build operation.

**Comment by petoor** [comment]
Yes. I guess i either need to loop though the z and t axis and save a pyramid tiff, or save each layer of the pyramid as a separate file. 

It would still be nice with a warning if the pyramid=True option is being called on multidimentional data.

**Comment by jcupitt** [comment]
It's to do with the structure of TIFF files. A file with one image looks like this:

```
dir1
    width
    height
    pixels
    etc.
```

It's a directory with a set of fields containing the image properties. A multi-page TIFF looks like this:

```
dir1
    width
    height
    pixels
    etc.
dir2
    width
    etc.
```

So you can put directories one after the other. libvips uses this dimension both for multi-page TIFFs (eg. a scanned document) and for pyramids (each page is the previous page shrunk by x2). The only difference with pyramids is that the `TIFFTAG_SUBFILETYPE` in the following directories is set to `FILETYPE_REDUCEDIMAGE`.

You want something more like this:

```
dir1 (highest res image of layer 0)
    width
    height
    pixels
    TIFFTAG_SUBIFD ->
        dir2 (x2 shrink of layer 0)
            width
            height
            pixels
            TIFFTAG_SUBFILETYPE FILETYPE_REDUCEDIMAGE
            TIFFTAG_SUBIFD ->
                dir3 (x4 shrink of layer 0)
                    width
                    etc.
dir4 (highest res image of layer 1)
    etc.
```

ie. represent the extra dimension for pyramid layers as nested directories rather than appended directories, and keep appended directories for your OME layers.

**Comment by jcupitt** [comment]
Update: libvips 8.11 now supports OME-style subifd tiff image pyramids.

The release notes have some background:

https://libvips.github.io/libvips/2020/06/18/What's-new-in-8.10.html#pyramids

Here's a sample script to convert to an OME-TIFF pyramid:

```python
#!/usr/bin/python3
  
import sys
import pyvips

im = pyvips.Image.new_from_file(sys.argv[1])

# openslide will add an alpha ... drop it
if im.hasalpha():
    im = im[:-1]

image_height = im.height
image_bands = im.bands

# split to separate image planes and stack vertically ready for OME 
im = pyvips.Image.arrayjoin(im.bandsplit(), across=1)

# set minimal OME metadata
# before we can modify an image (set metadata in this case), we must take a 
# private copy
im = im.copy()
im.set_type(pyvips.GValue.gint_type, "page-height", image_height)
im.set_type(pyvips.GValue.gstr_type, "image-description",
f"""<?xml version="1.0" encoding="UTF-8"?>
<OME xmlns="http://www.openmicroscopy.org/Schemas/OME/2016-06"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.openmicroscopy.org/Schemas/OME/2016-06 http://www.openmicroscopy.org/Schemas/OME/2016-06/ome.xsd">
    <Image ID="Image:0">
        <!-- Minimum required fields about image dimensions -->
        <Pixels DimensionOrder="XYCZT"
                ID="Pixels:0"
                SizeC="{image_bands}"
                SizeT="1"
                SizeX="{im.width}"
                SizeY="{image_height}"
                SizeZ="1"
                Type="uint8">
        </Pixels>
    </Image>
</OME>""")

im.tiffsave(sys.argv[2], compression="jpeg", tile=True,
            tile_width=512, tile_height=512,
            pyramid=True, subifd=True)
```

Convert like this:

```
$ ./convert.py CMU-1.svs CMU-1.tiff
```

Then load into QuPath:

```
$ ~/packages/bioformats/QuPath-0.2.3/bin/QuPath-0.2.3 CMU-1.tiff 
```

And you should see:

![image](https://user-images.githubusercontent.com/580843/114700556-8ff6ee00-9d19-11eb-861a-655cb99e285c.png)

**Comment by petoor** [comment]
For anyone finding this issue.
From @jcupitt's previous answer.

> Update: libvips 8.11 now supports OME-style subifd tiff image pyramids.
> The release notes have some background:
> https://libvips.github.io/libvips/2020/06/18/What's-new-in-8.10.html#pyramids

He specifies libvips 8.11, but links to the 8.10 documentation. 8.10 seems to work just fine.

In 8.11 jpeg2000 is added.
https://forum.image.sc/t/libvips-8-11-is-out-and-adds-support-for-ome-tiff-with-jpeg2000-compression/53787

In order to use jpeg2000 and not jpeg.
`change compression="jpeg" to compression="jp2k"`
However, it seems that "jp2k" is missing from https://libvips.github.io/pyvips/enums.html#pyvips.enums.ForeignTiffCompression

**Comment by jcupitt** [comment]
Ooop, sorry, you're right. As you say, 8.10 is subifd pyramids, 8.11 is jp2k.

I've added the doc updates to git master pyvips (will be 2.1.16), thanks for the reminder.
