### ISSUE TITLE
Error saving tiff file with n > 2

### ISSUE THREAD

**Issue by petoor** [libvips/pyvips#172]
Hi John.

I have a problem regarding loading a tiff file with 6 layers, and in its simplest version, just saving the image again (before we do manipulations)

Image is included here : [layer.zip](https://github.com/libvips/pyvips/files/4464397/layer.zip)
Minimum working code is a one liner.

`pyvips.Image.tiffload("layer.tif", n=6).tiffsave("layer1.tif")`
Which yields 

> pyvips.error.Error: unable to call tiffsave
  source input: 1024: Row out of range, max 599

but
`pyvips.Image.tiffload("layer.tif", n=2).tiffsave("layer1.tif")`
Works.

Do you have any ide how to fix this?

Best regards and happy easter.

**Comment by petoor** [comment]
Actually, n = 2 doesn't work either, it does save a second layer, however, that layer is wrong

**Comment by jcupitt** [comment]
Yes, I see this too, there's something odd about your image.

```
john@kiwi:~/pics/ome$ vips copy multi-channel-z-series.ome.tif[n=-1] x.tif
john@kiwi:~/pics/ome$ vips copy layer.tif[n=-1] x.tif

(vips:1818): VIPS-WARNING **: 11:27:24.136: error in tile 0 x 1024
source input: 1024: Row out of range, max 599
vips_region_generate: stop requested
```

I'll have a look.

**Comment by petoor** [comment]
The image is generated with image j, Image -> Hyperstacks -> New Hyperstack.

Creating a new hyperstack (that is, a new dummy image) it seems to work fine. 

Having a second look at the file i uploaded, it seems like c = 5 and z = 2 (so 4 c frames are missing)

I assume some metadata is wrong in the image I've uploaded. Right now im not sure how i managed to save it in the first place.

**Comment by petoor** [comment]
Hi again John.
This seems to reproduce the error. Disregard my former comment, it is not the metadata per se
HyperStack is added here : 
[HyperStack.zip](https://github.com/libvips/pyvips/files/4464440/HyperStack.zip)

```
import os
import pyvips

TILE_SIZE=512
file_name = "layer"
metadata = pyvips.Image.tiffload("HyperStack.tif", access="sequential")
height = metadata.get("height")
width = metadata.get("width")
n_pages = metadata.get("n-pages")
img2d = pyvips.Image.tiffload("HyperStack.tif", access="sequential", n=n_pages)
img2d.tiffsave(out_path + os.sep + "layer0.tif", compression="lzw", tile=True, tile_width=TILE_SIZE, tile_height=TILE_SIZE)
img2d = None # , access="sequential" should clear memory, test if we can remove this.

counter = 0
while height > TILE_SIZE or width > TILE_SIZE:
    im = pyvips.Image.tiffload(out_path + os.sep + f"{file_name}{counter}.tif", n=n_pages)
    im = im.reduce(2, 2)
    im.tiffsave(out_path + os.sep + f"{file_name}{counter+1}.tif",
                   compression="lzw", tile=True, tile_width=TILE_SIZE, tile_height=TILE_SIZE)
    height = im.get("height") // n_pages
    width = im.get("width")
    print(f"image {counter}")
    counter +=1

```

**Comment by jcupitt** [comment]
I think I might have fixed it. Could you test git master libvips?

**Comment by petoor** [comment]
Yes, I'll give it a go.

**Comment by petoor** [comment]
Hi John.

Thank you, it seems to work!
If i run

```
img = pyvips.Image.tiffload("layer0.tif",n=6)
img = img.reduce(2,2)
img.tiffsave("layer1.tif")

```
It seems that the page_height is off by a factor of 2. So it can be fixed with 
`height = img.get("height") // img.get("n-pages")
` in the tiffsave argument.
I wonder if there are any other manipulations that doesn't work straight out of the box.

**Comment by jcupitt** [comment]
Glad it works!

That's right, libvips doesn't try to update the `page-height` metadata item, that's up to users. Any kind of crop, rotate, resize etc. and you may need to change it.

Be a bit careful: `n-pages` is the number of pages in the original document, not the number of pages in the open image, so `image.height / image.get("n-pages")` won't always work.

**Comment by petoor** [comment]
Sure, it is not a problem to update it manually, it was just in case you weren't aware. 

I'll go ahead and close this issue. And thank you for your quick implementation! :smile:
