### ISSUE TITLE
When is it not accurate to calculate dzsave level count using log2?

### ISSUE THREAD

**Issue by hellowhistler** [libvips/pyvips#174]
In a previous issue (#89), the following was given as a method for calculating the number of levels when using dzsave:

> `log2(smaller-axis)` will mostly work, but will probably miss by one in some cases. If you need a 100% dependable answer, you'll need to reimplement the pyramid building code from dzsave

I was wondering, what's an example of a case where you would expect to see the off-by-one error? e.g. for a level count formula that looks something like `num_levels = 1 + ceil(log2(max(width, height)))`.

Thanks!

**Comment by jcupitt** [comment]
Hello @hellowhistler,

You're right, I'm probably being overcautious. I've been bitten in the past by logs failing to always exactly match iterated int arithmetic. Something like `max(1, ceil(log2(width) - log2(tile_size)))` is probably safe, where `tile_size` sets the termination size.

Though I think it's not a good thing for software to make assumptions about the number of layers in a dzsave pyramid -- it can change with factors like tile size, termination condition, or perhaps future bugfixes.

**Comment by hellowhistler** [comment]
Got it, thanks. I thought maybe I was missing something caused by a specific combination of image format and width/tile size/overlap.

It does make sense to make as few assumptions as possible.
