### ISSUE TITLE
arrayjoin  get a wrong result in vips8.8.3/8.9.1 and pyvips2.1.6/2.1.8/2.1.11

### ISSUE THREAD

**Issue by cihrenzai** [libvips/pyvips#175]
input imagelist to join
and get a wrong merged result
some item are joined in wrong order

**Comment by jcupitt** [comment]
Hello, it seems to work for me. 

For example, split an image into a grid of tiles:

```
$ vipsheader x.jpg 
x.jpg: 6048x8064 uchar, 3 bands, srgb, jpegload
$ vips dzsave x.jpg x
$ ls x_files/
0  1  10 11 12 13 2  3  4  5  6  7  8  9
$ cd x_files/13
$ ls
...
23_31.jpeg
```

There are a lot of tiles, but I can see that the highest numbered one is 23_31, so the image has 24 by 32 tiles. I rebuilt the image like this:

```
$ vips arrayjoin "$(ls *.jpeg | sort -t_ -k2g -k1g)" x.jpg --across 24
```

And I get back a copy of my original image.

Could you post an example which fails?

**Comment by cihrenzai** [comment]
I  have soleved the problem
thanks u!

**Comment by jcupitt** [comment]
OK, glad it's working.
