### ISSUE TITLE
Trouble with Orientation and autorot

### ISSUE THREAD

**Issue by vphill** [libvips/pyvips#176]
I'm a new user of both vips and pyvips so I might be missing something here. 

I am finding that `autorot()` doesn't seem to be resetting the orientation after it is performed on an image that needs to be rotated. 

Here is hopefully an example that displays what I mean.

```python
import sys
import pyvips

a = pyvips.Image.new_from_file(sys.argv[1])
print(a.get('orientation'))
a, angle = a.autorot(angle=True)
print(angle)
print(a.get('orientation'))
a.write_to_file(sys.argv[2])
```

I don't know if it is related but I've seen examples in other tickets about being able to use set to change the values (for example orientation) but I can't seem to make that work either. 

```
>>> import pyvips
>>> im = pyvips.Image.new_from_file('has-orientation-flag.jpg')
>>> im.get('orientation')
6
>>> im.set('orientation', 1)
>>> im.get('orientation')
6
```

I'm using pyvips 2.1.11 and libvips vips-8.9.1

I have attached an example image I've been using. 

![has-orientation-flag](https://user-images.githubusercontent.com/2053000/79804000-b792c080-8328-11ea-8641-6ea5665f3f6a.jpg)

**Comment by jcupitt** [comment]
Hello @vphill,

Yes, this was a bad regression that was fixed a couple of days ago: https://github.com/libvips/libvips/commit/1ef3594be122da22454b9e68eb8704b7d921df18

8.9.2 will have this. Thanks for reporting it.

**Comment by jcupitt** [comment]
8.9.2 should fix this:

https://github.com/libvips/libvips/releases/tag/v8.9.2
