### ISSUE TITLE
pypi package comes with no tests

### ISSUE THREAD

**Issue by lgbaldoni** [libvips/pyvips#181]
And yet it requires pytest-runner.

I'd use the github tarball, but latest versions haven't been tagged.

**Comment by jcupitt** [comment]
Hello @lgbaldoni,

You're right, we removed the tests from the pypi package, but forgot to remove pytest-runner. I think I've fixed it in git master, if you are able to test.

I always forget to tag releases. I've added a note about this to the README.

Thanks for pointing these problems out.

**Comment by lgbaldoni** [comment]
LGTM

**Comment by jcupitt** [comment]
Thanks for testing, I'll push out a new version (and tag it).
