### ISSUE TITLE
How to do anti-aliasing with pyvips

### ISSUE THREAD

**Issue by 2h4dl** [libvips/pyvips#184]
Read a svg and write it to png, but the edge is jagged.
Can pyvips make the edge smooth?

**Comment by jcupitt** [comment]
Hello @2h4dl ,

pyvips renders SVGs with smooth edges. If it's not working, post an sample SVG and the code you used to generated the jagged PNG.

**Comment by 2h4dl** [comment]
Yes, pyvips do smooth thing well. The jagged png caused by I forget to join the alpha channel.

**Comment by jcupitt** [comment]
ah OK. Glad it's working.
