### ISSUE TITLE
Seg Faults when Installing via Pip

### ISSUE THREAD

**Issue by simonwarchol** [libvips/pyvips#185]
I've successfully been using pyvips to create deep zoom pyramids of images. My package is used across platforms, and as such, I've been relying on pip to install pyvips, but conda for everything else.

Recently running the following code on my mac
```
import pyvips

image = pyvips.Image.new_from_file('/Users/Simon/Research/facetto/static/data/test/nucleiMask.png')
```
throws the following error
```
(process:22520): GLib-CRITICAL **: 09:59:50.347: g_datalist_id_set_data_full: assertion 'key_id > 0' failed

(process:22520): GLib-GObject-CRITICAL **: 09:59:50.347: g_param_spec_pool_lookup: assertion 'pool != NULL' failed

(process:22520): GLib-GObject-WARNING **: 09:59:50.347: g_object_set_is_valid_property: object class '(null)' has no property named 'filename'

(vipstest.py:22520): GLib-GObject-CRITICAL **: 09:59:50.347: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
Segmentation fault: 11
```

The solution I have in place is to use conda to install `imagemagick<7.0.9` and `pyvips`. However, given these packages aren't on conda-forge for windows, it isn't ideal, and I'd rather not have two different `requirements.yml` files. 

Any suggestions?

**Comment by jcupitt** [comment]
Hello Simon,

Sorry, this error doesn't ring a bell. It's working for me on my mac (I only use brew), so I guess there's some clash with conda. 

```
14:44 $ which python3
/usr/local/bin/python3
✔ ~/pics 
14:44 $ which vips 
✘-1 ~/pics 
14:44 $ vips --version
vips-8.9.2-Tue Apr 21 09:26:11 UTC 2020
✔ ~/pics 
14:45 $ which vips
/usr/local/bin/vips
✔ ~/pics 
14:45 $ pip3 install pyvips
Collecting pyvips
  Downloading pyvips-2.1.12.tar.gz (43 kB)
     |████████████████████████████████| 43 kB 2.2 MB/s 
Requirement already satisfied: cffi>=1.0.0 in /usr/local/lib/python3.7/site-packages (from pyvips) (1.12.3)
Requirement already satisfied: pkgconfig in /usr/local/lib/python3.7/site-packages (from pyvips) (1.5.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.7/site-packages (from cffi>=1.0.0->pyvips) (2.19)
Building wheels for collected packages: pyvips
  Building wheel for pyvips (setup.py) ... done
  Created wheel for pyvips: filename=pyvips-2.1.12-cp37-cp37m-macosx_10_15_x86_64.whl size=74129 sha256=1f1be31ddc307834d64cd9c3efe032fbae5193a2d04315de8682537798ac1997
  Stored in directory: /Users/john/Library/Caches/pip/wheels/a3/a5/62/efef640031f26ee457fc7f748e83b09ec1d6f220fbdf8c97f0
Successfully built pyvips
Installing collected packages: pyvips
Successfully installed pyvips-2.1.12
✔ ~/pics 
14:46 $ python3
Python 3.7.7 (default, Mar 10 2020, 15:43:33) 
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvips
>>> x = pyvips.Image.new_from_file("nina.jpg")
>>> 
```

Conda is its own separate world and you can't safely mix conda binaries with any others. It's especially bad for things like imagemagick, which brew builds with gcc and conda builds with clang. You probably need to only use homebrew, or only use conda.

There's a pyvips package for conda, which would probably fix your problems, but it's not in a great state, unfortunately.

**Comment by simonwarchol** [comment]
Hey John,
Thanks for the time. After a lot of debugging, I found out the issue was with my OpenCV installation, and moving from the conda `opencv` to the pip `opencv-python` seemed to fix things.

Thus, using pip pyvips and opencv over the conda versions seems to the be the preferred solution.

Perhaps this will be of assistance to others. Closing the issue.
