### ISSUE TITLE
skip_blanks in dzsave

### ISSUE THREAD

**Issue by acycliq** [libvips/pyvips#186]
Hi

I dont understand how the `skip_blanks` switch works in `dzsave`.  I am trying to divide an image into equal small squares, lets take for example this [image](https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Wac_nearside.jpg/1024px-Wac_nearside.jpg)
What I would like to end up with is to get all tiles, even the empty ones, and if a square covers area outside the bounds of the original image to fill it with black (transparent would be ideal but I dont think this is possible) 

Running 
`im = pyvips.Image.new_from_file('./1024px-Wac_nearside.jpg')`
`im.dzsave('./out', suffix='.tif', skip_blanks=0, background=0, depth='one', overlap=0, tile_size=123, layout='google')`

splits the image but does not produce any tiles if they are totally black. I tried different combinations for `skip_blanks` and `background` without any success whatsoever.

I am running `pyvips 2.1.8`  with `vips-dev-8.9` on `Python 3.8` and `Windows 10`
Any ideas please?

**Comment by jcupitt** [comment]
Hello @acycliq,

It removes tiles that have every pixel within `skip_blanks` of `background`. Try:

```
john@kiwi:~/pics$ vips dzsave 1024px-Wac_nearside.jpg x \
    --skip-blanks 100 --background 0 \
    --depth one --overlap 0 --tile-size 123 --layout google
john@kiwi:~/pics$ ls x/0/0/
2.jpg  3.jpg  4.jpg  5.jpg  6.jpg
```

You need quite a high value, since JPEG compression errors mean your moon has a large "fringe" of dark values around the edges.

![jpg-err](https://user-images.githubusercontent.com/580843/82745174-473cec00-9d79-11ea-9cb1-a89bab279431.png)

**Comment by jcupitt** [comment]
Would you like to detect the background and make it it transparent? That's easier to do in plain pyvips rather than dzsave. For example:

```python
#!/usr/bin/python3

import sys
import pyvips

image = pyvips.Image.new_from_file(sys.argv[1])

# blur to hide jpg compression artefacts, then threshold to get a mask
mask = image.gaussblur(2) > 20

# flood with 128 from the top left to find all background pixels, then 
# invert to get just the moon
mask = mask.draw_flood(128, 0, 0, equal=True) != 128

# blur again to soften the edge and make the alpha
alpha = mask.gaussblur(2)

image = image.bandjoin(alpha)

image.write_to_file(sys.argv[2])
```

Then:

```
./remove-background.py 1024px-Wac_nearside.jpg x.png
```

To make:

![x](https://user-images.githubusercontent.com/580843/82745459-81f45380-9d7c-11ea-9fdc-840cdc6e9531.png)

Feed that to `dzsave` to tile it.

**Comment by acycliq** [comment]
Ah ok! Many thanks John your help. So the `skip_blanks` value sets the upper bound of a range whose lower bound has been preset to zero.  If a tile has all its pixels lying within that range it will be skipped by `dzsave`. To disable this functionality `skip_blanks = -1`  would work.
In my case where I just want to slice the image to small squares and keep all of them, even if there is no content, running
`im.dzsave('./out', suffix='.tif', skip_blanks=-1, background=0, depth='one', overlap=0, tile_size=123, layout='google')`
seems to work fine

Many thanks again!

**Comment by jcupitt** [comment]
It's not an upper bound, it's the maximum difference, ie. `abs(a - b) < t`. Glad it's working.
