### ISSUE TITLE
dzsave; Image quality on pyramid tiles

### ISSUE THREAD

**Issue by acycliq** [libvips/pyvips#191]
Is there a way to control image quality of the pyramid tiles generated by `dzsave`? I am doing some image pyramids and the output directory is huge, around 50-60GB. No wonder since I am doing 10 zoom levels but I was wondering if I could reduce the quality of the `png` tiles and gain something on the file size side. 
Like setting the resampling method (average, cubic, lanczos etc) or otherwise. I am quite tolerant to image quality, it is not very crucial to me.  
Broadly speaking, this is how I am using `dzsave` (The imput image is typically a TIF with dimensions 25000px-by-20000px or even bigger)

```
    im = pyvips.Image.new_from_file(img_path, access='sequential')
    im.dzsave(out_dir, layout='google', suffix='.png', background=0, skip_blanks=0)
```

**Comment by jcupitt** [comment]
Hello @acycliq,

PNG tiles are huge, I'd use JPG if you can.

You can set options to the PNG saver with eg.:

```python
im.dzsave(out_dir, layout='google', suffix='.png[compression=9]')
```

You might be able to (for example) save an 8-bit palette image instead, depending on your image.

**Comment by acycliq** [comment]
Ah ok. Many thanks John! That was quick! I will play around with these and try to find something that works ok for my needs
