### ISSUE TITLE
add page argument to thumbnail

### ISSUE THREAD

**Issue by petoor** [libvips/pyvips#192]
Hi John.

Following https://github.com/libvips/pyvips/issues/190
I was wondering if it was possible to add a page argument to image.thumbnail ?
Right now the solution is to use new_from_file(..., page=page) and then use img.thumbnail_image, but as you stated it is not the optimal solution.

Best regards

**Comment by petoor** [comment]
I understand this probably isn't a small change as it would require the thumbnail reader / writer to understand tiffload.

For instance, this image.
tiffload understands it just fine, but thumbnail gives a "tiff2vips: no SUBIFD tag"
[2channels_flat.zip](https://github.com/libvips/pyvips/files/4778744/2channels_flat.zip)

**Comment by jcupitt** [comment]
Hi @petoor,

You're supposed to do something like:

```
thumb = pyvips.Image.thumbnail("something.tif[page=12]", 200)
```

The "no SUBIFD tag" error looks like a bug in libvips master, I'll have a look.

**Comment by jcupitt** [comment]
Yes, the recent addition of bioformats subifd pyramid support had broken multipage tiff thumbnailing. It should work now.

Thanks for reporting this!

**Comment by petoor** [comment]
I just tested your fix to libvips, and the subifd tag error is gone.

However, and you can test with the 2channels_flat image, setting the page argument in thumbnail doesnt seem to actually load the page.

```
def vips2numpy(vi):
    return np.ndarray(buffer=vi.write_to_memory(),
                      dtype=format_to_dtype[vi.format],
                      shape=[vi.height, vi.width, vi.bands])

a = pyvips.Image.thumbnail("2channels_flat.tif[page=0]", 500)
b = pyvips.Image.thumbnail("2channels_flat.tif[page=1]", 500)

print(vips2numpy(a).all() == vips2numpy(b).all())
True
```

Which should be False

**Comment by petoor** [comment]
Sorry, the numpy logic is wrong in that comment. The code should be 

```
a = pyvips.Image.new_from_file("2channels_flat.tif[page=0]")
b = pyvips.Image.new_from_file("2channels_flat.tif[page=1]")

print((vips2numpy(a)==vips2numpy(b)).all())
>>>False

a = pyvips.Image.thumbnail("2channels_flat.tif[page=0]",500)
b = pyvips.Image.thumbnail("2channels_flat.tif[page=1]",500)

print((vips2numpy(a)==vips2numpy(b)).all())
>>>True
```

**Comment by jcupitt** [comment]
You're right, many-page TIFF thumbnailing is not working, I'll have another look.

**Comment by jcupitt** [comment]
I think it's fixed. I'll add some more tests.

**Comment by petoor** [comment]
If it is pushed to libvips master i can test as well.

**Comment by jcupitt** [comment]
Yes, it's pushed, and I added some more tests too.

**Comment by petoor** [comment]
It seems to work great.
Thanks John.

**Comment by jcupitt** [comment]
Great! Thank you for testing it, I'll close.

**Comment by petoor** [comment]
If the vips-loader is openslideload it doesn't accept the page argument, however if this is by design or not i'm not sure. Iit seems like the other loaders just ignore it if page doesn't make sense for them

**Comment by jcupitt** [comment]
You must only supply the accepted arguments for all loaders. For example:

```
$ vipsheader k2.jpg[page=12]
vipsheader: jpegload: no property named `page'
```
