### ISSUE TITLE
thumbnail_buffer and option_string

### ISSUE THREAD

**Issue by juntatalor** [libvips/pyvips#193]
Hi!

I'm trying to create jpeg thumbnail from python bytes (it is a png or jpeg or tiff etc). I see the **option_string** argument in docs (https://libvips.github.io/pyvips/vimage.html#pyvips.Image.thumbnail_buffer), but it is not supported (no value in intro.details inside call(), so errors is raised).

There is a required **out** argument, but as i understand it is filled automatically.

So my question is - is it possible to generate thumbnail with this method? Something like this:
`
image = Image.thumbnail_buffer(
                image_bytes, IMAGE_MAX_WIDTH,
                option_string='.jpg[Q=85,background=255]',
                size='down',
                auto_rotate=True
            )
`

For now I perform all required operations with vips separate functions (new_from_buffer, resize, rotate, read exif etc). I think that thumbnail method could perform better.

**Comment by jcupitt** [comment]
Hi @juntatalor,

The `option_string` is passed to the loader, so you can use it to (for example) select which page of a large TIFF file you want to thumbnail.

You set save options when you save the image, something like:

```python
thumb = pyvips.Image.thumbnail_buffer(image_bytes, IMAGE_MAX_WIDTH, size="down")
thumb.write_to_file("something.jpg", Q=85, background=255)
```

**Comment by juntatalor** [comment]
@jcupitt Thank you for fast reply! Ok, now it is clear.
