### ISSUE TITLE
Where is pyvips.Image.grey implemented?

### ISSUE THREAD

**Issue by int-ua** [libvips/pyvips#199]
The only mention I see in the code is some docs and I don't see this method in the main libvips repository either. Related question: https://askubuntu.com/q/1264762/20275

**Comment by jcupitt** [comment]
Hello @int-ua,

It's defined here:

https://github.com/libvips/libvips/blob/master/libvips/create/grey.c

Docs here:

https://libvips.github.io/libvips/API/current/libvips-create.html#vips-grey

**Comment by jcupitt** [comment]
It's in `Vips-8.0.gir`, so I'd think it would be in the typelib too, but I've not tested it. I would use pyvips instead -- the g-o-i interface is slow and will crash frequently, especially under load.

**Comment by int-ua** [comment]
Thank you!
