### ISSUE TITLE
If I use “Pyvips”, the program does not exiton Windows 7.

### ISSUE THREAD

**Issue by weirman** [libvips/pyvips#201]
When I 'import pyvips', the program does not end automatically.
I executed the following code:
```python
#!/usr/bin/python3
import os
vipshome = 'F:\\vips-dev-8.10\\bin'
os.environ['PATH'] = vipshome + ';' + os.environ['PATH']
import pyvips
print("Program end!!!")
```
But the program output "Program end!!!" does not end there.The process still exists.

**Program output:
Program end!!!**

I can add `os._exit(0)` code to force the end of the program. 
**Program output:Program end!!!
Process finished with exit code 0**

So I would like to know what causes the program not to end normally.

I want to know what caused the program to end normally by executing the following code.
```python3
#!/usr/bin/python3
import os

vipshome = 'F:\\vips-dev-8.10\\bin'
os.environ['PATH'] = vipshome + ';' + os.environ['PATH']

import logging

logging.basicConfig(level=logging.DEBUG)
import pyvips
```
**Program output:
DEBUG:pyvips:Binary module load failed: No module named '_libvips'
DEBUG:pyvips:Falling back to ABI mode
DEBUG:pyvips:Loaded lib <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x000000000AEA1898>
DEBUG:pyvips:Loaded lib <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x000000000AE7AF28>
DEBUG:pyvips:Inited libvips**

Could you please help me analyze what causes this problem.Thaks.

My environment variables are as follows:
> OS: Windows 7.
> Python 3.6.4.
> pyvips 2.1.12.
> vips-dev-8.10.

**Comment by jcupitt** [comment]
Hello @weirman,

Sorry, I have no easy way of testing on win7.

libvips uses `atexit()` to hook into process end and free resources, so perhaps that that is not working correctly on win7 due to bugs in the Windows C runtime.

I would try building libvips with more debugging enabled to try to gain insight into the lockup. This is not easy, unfortunately.

**Comment by jcupitt** [comment]
pyvips also uses Python's `atexit`, see `__init__.py`. You could try adding some prints to that to see if it is succeeding.

**Comment by weirman** [comment]
I added a print at line 172 of the int `__init__.py`, as follows:
```python3
# we must remove the handler on exit or libvips may try to run the callback
# during shutdown
def _remove_log_handler():
    global _log_handler_id
    global _remove_handler

    if _log_handler_id:
        _remove_handler(_to_bytes('VIPS'), _log_handler_id)
        _log_handler_id = None

atexit.register(_remove_log_handler)
print("register")
```
The program will output **`register`**. Does this mean that **`atexit`** does not work

**Comment by jcupitt** [comment]
Sounds like the handler is running, so that's good.

It's more complex than just installing gcc, unfortunately. I think you'd need to study the docs for setuptools.

Sorry, I don't think I can debug this. At least you have a workaround.

**Comment by weirman** [comment]
Thank you for your concern. For now, I can modify the source code to avoid this error. It's not clear why this is a problem(it could be the system or python version), but thank you very much. Later I will experiment in different Python versions and Windows systems, and then open this issue.
