### ISSUE TITLE
Generating text over transparent background

### ISSUE THREAD

**Issue by int-ua** [libvips/pyvips#204]
It looks like one of the most basic tasks and yet it seems quite hard to do at least without reading through all of the documentation and looking at only the related methods and classes. 
```python
def output(filename, text, color):
    image, feedback = pyvips.Image.text(
        text, font='Liberation-Sans-Narrow', width=32, height=32,
        autofit_dpi=True)
    image = image.colourspace('srgb')
    image = image.addalpha()
    image = image.ifthenelse([0, 0, 0, 255], [255, 255, 255, 0], blend=True)
    image.write_to_file(f'{DIR}/{filename}.png')
```
I guess I'm not working correctly with ifthenelse. But what are the right values to make the image transparent? Where is the alpha channel supposed to be?

Also, the resulting image is not 32x32, it may be good to add hints on how to make it the required size somewhere around [here](https://libvips.github.io/pyvips/vimage.html#pyvips.Image.text).

**Additional context**
#203
https://github.com/libvips/libvips/issues/1208

**Comment by jcupitt** [comment]
Hello again, you could make this a little simpler: use the text for the alpha and have a solid colour in RGB.

For example:

```python
alpha, feedback = pyvips.Image.text('Hello World!', 
        font='Liberation-Sans-Narrow', width=32, height=32,
        autofit_dpi=True)
alpha = alpha.gravity('centre', 32, 32)
image = alpha.new_from_image([0, 0, 255]).bandjoin(alpha)
```

The `gravity` will expand the alpha up to 32x32 if it's smaller.

`text` uses 0 - 255 for black - white. If you want to make the text semi-transparent, you'll need to set a smaller range, perhaps 0 - 64? You could write:

```python
image = alpha.new_from_image([0, 0, 255]).bandjoin(alpha * 0.25)
```

**Comment by int-ua** [comment]
Thank you! This code finally works
```python
def output(filename, text):
    alpha, feedback = pyvips.Image.text(
        text, font='Liberation-Sans-Narrow', width=32, height=32,
        autofit_dpi=True)
    alpha = alpha.gravity('centre', 32, 32)
    image = alpha.new_from_image([0, 0, 0]).bandjoin(alpha)
    image.write_to_file(f'{DIR}/{filename}.png')
```
I'll read the docs you've referenced in the other two issues and try to implement color support now.

**Comment by int-ua** [comment]
Adding a shadow: spent quite a lot of time trying to move a second image that I've generated with a different color:
```python
    shadow = rendered_text.copy()
    shadow_color = shadow.new_from_image([0, 0, 0])
    shadow_image = shadow_color.bandjoin(shadow)
```
And nothing worked. Trying to find something about "offset" and "move" didn't yield any results. The only way I've found to "move" the shadow is when overlaying with `composite2`:
```python
result = image.composite2(shadow_image, mode, x=1, y=2)
```

**Comment by jcupitt** [comment]
Could you post a sample image showing the effect you want?

**Comment by int-ua** [comment]
I've made it with CSS on the text of this page to make it more visible:
![Screenshot_20200825_171648](https://user-images.githubusercontent.com/1585431/91185640-c504f080-e6f6-11ea-92a4-04e1a2a1bc02.png)
I've already achieved it with the code above. I've posted the code to help anyone who will be searching for similar things and to demonstrate how docs are not helpful.

**Comment by int-ua** [comment]
What I wanted before I've used the `composite2` is just move the shadow image, like with `-page +1+1 -background none` when using ImageMagick CLI.

**Comment by jcupitt** [comment]
Ah OK. You can use `embed` to place an image within a canvas. If you scale the mask you get from `text` to 0 - 1, you can just do the obvious `mask * a + (1 - mask) * b` to fade between two things.

So this:

```python
#!/usr/bin/python
  
import sys
import pyvips

target_width = 500
target_height = 500
text_colour = [128, 255, 255, 255]
shadow_colour = [0, 0, 255, 255]
shadow_offset_x = 10
shadow_offset_y = 20

text_mask, results = pyvips.Image.text("Hello, World!",
        width=target_width, height=target_height, autofit_dpi=True)
text_mask = text_mask.gravity('centre', target_width, target_height)
# use 0 - 1 for the masks
text_mask /= 255
shadow_mask = text_mask.embed(shadow_offset_x, shadow_offset_y,
        target_width, target_height)

image = text_mask * text_colour + (1 - text_mask) * shadow_mask * shadow_colour

image.write_to_file(sys.argv[1])
```

Makes:

![x](https://user-images.githubusercontent.com/580843/91196088-9e908680-e6f1-11ea-8947-433cd4b115c6.png)

**Comment by jcupitt** [comment]
You can do lots of other text effects. For example, blur the shadow with `shadow_mask = shadow_mask.gaussblur(4)` to make:

![x](https://user-images.githubusercontent.com/580843/91196551-32625280-e6f2-11ea-838d-4e46b5f1696a.png)

Or a large blur and remove the offset to make a centred shadow:

![x](https://user-images.githubusercontent.com/580843/91196691-5de53d00-e6f2-11ea-9ee1-89a5b372858e.png)

The morphological operators work well with text -- you could add extra outlines, or skeletonize, or add a ringing border etc. etc. You can use the text body to mask a texture too.

**Comment by int-ua** [comment]
I'm tired. Is there a **one-line** addition to my code above assuming image is in `shadow_image` that will move that image +1+1?

> the obvious

no.

Anyway, this is all just theoretical, the problem is solved now.

**Comment by jcupitt** [comment]
`a.embed(x, y, width, height)` will position `a` at (x, y) within an image of size (width, height).
