### ISSUE TITLE
Ultra-confusing filename system with dzsave

### ISSUE THREAD

**Issue by jcpayne** [libvips/pyvips#205]
I am a new user so may be missing something/everything.  However, I had massive problems in trying to use dzsave(), which has the following format in the documentation: `input_image.dzsave(filename, dirname=str, basename=str, etc.)`.  Here is what I found:
- The first argument must be a filename, but you can't write `filename=<filename>` and it can't be a path. Pyvips will create a directory called `<filename>_files` in your root directory (wherever `pwd` points to).
- If you include dirname but not basename, pyvips will create a directory called 'dirname_files' one level down, and filename will be ignored.
- If you include basename, then both dirname and filename are ignored.

In addition, Pyvips is crashing repeatedly and seems to be incapable of making two calls in a row.  I'm running pyvips in Ubuntu 18.04 from a Jupyter Notebook.  When I translate the same commands to libvips, everything works fine.

**Comment by jcupitt** [comment]
Hi @jcpayne,

It seems to work for me, if I understand what you mean. For example:

```
john@kiwi:~/pics$ mkdir ~/x
john@kiwi:~/pics$ vips dzsave k2.jpg ~/x/banana
john@kiwi:~/pics$ ls ~/x
banana.dzi  banana_files
```

So I can use a path as the argument to dzsave. It works from Python too:

```
john@kiwi:~/pics$ mkdir ~/x
john@kiwi:~/pics$ python
Python 2.7.18rc1 (default, Apr  7 2020, 12:05:55) 
[GCC 9.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvips
>>> x = pyvips.Image.new_from_file("k2.jpg")
>>> x.dzsave("/home/john/x/banana")
>>> 
[1]+  Stopped                 python
john@kiwi:~/pics$ ls ~/x
banana.dzi  banana_files
```

I'm probably misunderstanding you. Could you post a specific example?

pyvips should be stable. Perhaps it's something to do with the way you installed either libvips or pyvips, or the way you are running jupyter notebook, or the version you are using? Are you using conda, for example? You'd need to explain what you did.

**Comment by jcpayne** [comment]
Thanks for the quick response John, I am about to travel but will circle back to this in a few days and see if I can follow your example and get it working.  Might well be some sort of Jupyter or installation issue.

**Comment by jcupitt** [comment]
I should have said: I'm using libvips 8.10 and pyvips 2.1.13 on ubuntu 20.04 using Ubuntu's Python, with pyvips installed locally by pip.

**Comment by jcpayne** [comment]
Hi John, I'm finally looking at this again.  In the following command, `targetdir` works as expected but the `basename` parameter is ignored (and doesn't throw a warning or error).  Could that be because I'm using Google layout?  I was hoping that instead of naming the files `1.jpg`, `2.jpg`... I could name them `basename_1.jpg`, `basename2.jpg`, and so on.  But now that I understand it better, I can work with the system as is; I'll just use the image name as the targetdir. 
```python
commstring = f'vips dzsave {sourceimg_path} {targetdir} --basename {sourceimg_filename} --layout google --tile-size 500 --depth one --overlap 100 --background 0 --suffix .jpg[Q=100]'
!commstring #execute
```

**Comment by jcupitt** [comment]
`basename` sets the name of the object that dzsave writes. It defaults to the last part of the `targetdir`. You probaly don't need to set it. It can be useful if you are writing zip objects.

I guess you found the main docs for `dzsave`?

https://libvips.github.io/libvips/API/current/VipsForeignSave.html#vips-dzsave

There's a tutorial-style guide as well:

https://libvips.github.io/libvips/API/current/Making-image-pyramids.md.html
