### ISSUE TITLE
How to create an image from an array [(1,2,3,1), (1,2,4,5), (255,255,0,0),(0,0,0,0), ...]?

### ISSUE THREAD

**Issue by www-YM** [libvips/pyvips#207]
Hi,

Hello everyone, I am a newbie to libvips and need to create an image, which comes from an array of colors, for example "[(1,2,3,1), (1,2,4,5), (255,255,0,0),(0,0,0,0)....]". 

I tried for a long time but couldn't achieve it.

This is the implementation with the PIL package below, but when I try to generate a 4000x4000 png file, it takes about 3 seconds to put data, and 1.3 seconds to save it as png.  This takes too long.

How does libvips realize this function?

Thank you very much.

```
from PIL import Image

colors = [(1,2,3,1), (1,2,4,5), (255,255,0,0),(0,0,0,0)....]

img = Image.new('RGBA', 1000, 1000)

img.putdata(list(colors))

img.save('./out.png')
```

**Comment by jcupitt** [comment]
Hello @www-YM, what does your program do? Do you really have a huge constant array?

If you post a complete, runnable program, I could try making a pyvips version.

**Comment by www-YM** [comment]
> Hello @www-YM, what does your program do? Do you really have a huge constant array?
> 
> If you post a complete, runnable program, I could try making a pyvips version.

Hi @jcupitt ,

Thank you for your quick reply, please wait a moment, I will write a simple example now.

**Comment by www-YM** [comment]
> Hello @www-YM, what does your program do? Do you really have a huge constant array?
> 
> If you post a complete, runnable program, I could try making a pyvips version.


This example requires additional images, I have packed them up, please click the link to download. 

http://wow-assets-us.oss-accelerate.aliyuncs.com/tmp/example%20code.zip

```
import _pickle
from PIL import Image


# load mapping dict
f = open('./mapping.pkl', 'rb')
mapping = _pickle.load(f)

# load source image
im = Image.open('./source.png')

distorted = Image.new('RGBA', (4000, 4000))

im_data = im.getdata()

pixels_count = 4000*4000

# get color from source
# if the index is the key of mapping dict, then get color from im_data, else set as (0, 0, 0, 0)
colors = (im_data[mapping[idx]] if idx in mapping else (0, 0, 0, 0) for idx in range(pixels_count))

distorted.putdata(list(colors))

distorted.save('./out.png')
```

Thank you.

**Comment by jcupitt** [comment]
How is `mapping.pkl` created, and what is it? Just a big dictionary? What do the values mean? Is it some sort of geometric transform?

It's probably an inefficient way to do what you want. Could you make a small, complete program that shows what you need to do.

**Comment by www-YM** [comment]
Thanks @jcupitt . Your suggestions are very helpful.

**Comment by jcupitt** [comment]
This issue was resolved over email.
