### ISSUE TITLE
Suppress vips warnings being logged

### ISSUE THREAD

**Issue by dthiagarajan** [libvips/pyvips#208]
Hello,

I'm opening several .tif files in OpenSlide and encountering a large amount of warnings logged, all like the following:

```
vips warning: Auto-corrected former TIFF subsampling values [2,2] to match subsampling values inside JPEG compressed data [2,1]
```

Is there any way that I can suppress these in `pyvips`?

**Comment by jcupitt** [comment]
Hello @dthiagarajan,

You can define the env var `VIPS_WARNING` to suppress warning messages. For example:

```
VIPS_WARNING=1 python3 myprog.py
```

**Comment by dthiagarajan** [comment]
Perfect, thanks!
