### ISSUE TITLE
Version mismatch Pyvips/Vips

### ISSUE THREAD

**Issue by imgifty** [libvips/pyvips#209]
Hello,
I am having issues pointing pyvips to the correct vips version.
So I built vips 8.10.1 by following the build guide: https://libvips.github.io/libvips/install.html . It seems to be installed, as I can check with vips --version, which yields that exact version.

Then I tried uninstalling pyvips: **pip uninstall pyvips**
Then I tried reinstalling pyvips using following command: **pip install --no-cache-dir pyvips** in my virtualenv.

When I try to use features only present in 8.10.1, e.g. shrink on load, I get vips errors.

Can you pinpoint, where I have to change the vips version or libraries that are included when installing pyvips? Thanks a lot!

**Comment by jcupitt** [comment]
Hello @imgifty,

pyvips uses `pkg-config` to find the libvips headers and library, so try:

```
$ pkg-config vips --modversion
8.10.2
```

To see which headers it is finding. If it's finding the wrong version, you'll need to update your `PKG_CONFIG_PATH`, eg. I have:

```
$ echo $PKG_CONFIG_PATH 
/home/john/vips/lib/pkgconfig:
$ pkg-config vips --libs
-L/home/john/vips/lib -lvips -lgobject-2.0 -lglib-2.0
```

**Comment by imgifty** [comment]
Hello @jcupitt ,
I tried the suggested changes, but there doesn't seem to be any changes.
Following commands give me output:

 `(venv) alexander@xubuntupc:~/Desktop$ echo $PKG_CONFIG_PATH \(not set)
`

 `(venv) alexander@xubuntupc:~/Desktop$ export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
`

`(venv) alexander@xubuntupc:~/Desktop$ pkg-config vips --modversion`

`8.10.1`

`(venv) alexander@xubuntupc:~/Desktop$ pkg-config vips --libs`

`-L/usr/local/lib -lvips -lgobject-2.0 -lglib-2.0
`

When I try installing with `pip install --no-cache-dir pyvips --verbose`, and try to `pyvips.Image.new_from_file(image, shrink=10)`, I still get KeyErrors, due to having the wrong vips version linked.

Is there another way to verify, I'm using the correct lib file during pip installation? Could there be issues occuring, due to building the libvips from my external harddrive?

**Comment by jcupitt** [comment]
Maybe run `ldconfig`? If you've installed to `/usr/local/lib`, some linuxes need to have the library cache rebuilt.

You can try this to see what library pyvips is picking up at runtime:

```
$ python3
Python 3.8.2 (default, Jul 16 2020, 14:00:26) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvips
>>> pyvips.API_mode
True
>>> pyvips.__version__
'2.1.12'
>>> pyvips.version(0)
8
>>> pyvips.version(1)
10
>>> pyvips.version(2)
2
```

**Comment by imgifty** [comment]
Hmm, very weird, running ldconfig again seemed to fix the problem. Okay, it did work, when checking the pyvips version from python.
Another question, is shrink on load possible for tiled tif files?
Thanks a lot!

**Comment by jcupitt** [comment]
Not for plain tiled TIFF, no. libvips will spot pyramidal TIFFs and shrink-on-load for them.
