### ISSUE TITLE
Corrupted pixels when using list comprehension in arrayjoin call

### ISSUE THREAD

**Issue by aspadm** [libvips/pyvips#212]
**Preamble**
I wrote a small script that loads images and mixes them using a special numpy algorithm. Next, the tiles are collected in a tileset.
At some point, I discovered that some of the tiles in the tileset end up with broken pixels in the upper-left part. After some inspection, I found that the problem only affects matching tiles (i.e. that have identical construction process).
By gradually dropping lines of code, I got the following minimally reproducible example.
If I take out list comprehension from call params to dedicated variable, it works as required. Otherwise some memory corruption occurs.

**System data**
`Ubuntu 20.04.1 LTS`
`Python 3.8.5`
`vips-8.9.1-Sun Feb 23 08:51:26 UTC 2020`
`pyvips version: 2.1.12 API mode`

**What I expect to get**
![correct](https://user-images.githubusercontent.com/7457530/98305953-da8a7680-1fd3-11eb-96b9-317d0973c071.png)

**What I got**
![memory_mess](https://user-images.githubusercontent.com/7457530/98305426-e32e7d00-1fd2-11eb-97af-67f135ebbd2b.png)

**How to reproduce**
```python3
import pyvips as ps
import numpy as np

TILE_RES = 50

def prepare_tile():
    vs_black_tile = ps.Image.black(TILE_RES, TILE_RES, bands=3)
    np_black_tile = np.ndarray(buffer=vs_black_tile.write_to_memory(),
                               dtype=np.uint8,
                               shape=[TILE_RES, TILE_RES, 3])
    linear = np_black_tile.reshape(TILE_RES * TILE_RES * 3)
    result_black_tile = ps.Image.new_from_memory(
        linear.data, TILE_RES, TILE_RES, 3, "uchar")

    return result_black_tile

if __name__ == "__main__":
    ### ERROR
    res = ps.Image.arrayjoin([prepare_tile() for i in range(16)], across=4)
    res.write_to_file("memory_mess.tif")

    ### Correct
    tile_array = [prepare_tile() for i in range(16)]
    res = ps.Image.arrayjoin(tile_array, across=4)
    res.write_to_file("correct.tif")
```

**Comment by jcupitt** [comment]
That's a really interesting error @aspadm, thank you for reporting this.

I suppose arrayjoin is not holding a reference to the image array correctly, but I'm not sure if the problem is in pyvips or libvips. I'll investigate.

**Comment by jcupitt** [comment]
I found the problem -- it's to do with the way Python implements equality for memoryview objects.

```
>>> v = memoryview(b'abcefg')
>>> v2 = memoryview(b'abcefg')
>>> v
<memory at 0x7fd92c4771c0>
>>> v2
<memory at 0x7fd92c477280>
>>> v == v2
True
```

Although v and v2 point to different areas of memory, their contents are the same, therefore they are declared to be equal. Python hashes memory and compares the hashes.

I assumed that == on memoryview meant pointer equality :-( too much time with C. This error stops arrayjoin keeping a reference to all the input images, since it thinks they are all equal. You'll notice the top-left tile in your example is OK.

We need to find a way to implement pointer equality. It's not obvious from the memoryview docs.

https://docs.python.org/3/library/stdtypes.html#memoryview

**Comment by koteyur** [comment]
> We need to find a way to implement pointer equality. It's not obvious from the memoryview docs.

Perhaps you just need to use `is` operation here: `v is v2`.

**Comment by jcupitt** [comment]
Ah, good idea!

I've pushed a patch to git master which seems to fix it for me, could you test?

**Comment by aspadm** [comment]
> I assumed that == on memoryview meant pointer equality :-( too much time with C. This error stops arrayjoin keeping a reference to all the input images, since it thinks they are all equal. You'll notice the top-left tile in your example is OK.
> 
> We need to find a way to implement pointer equality. It's not obvious from the memoryview docs.
> 
> https://docs.python.org/3/library/stdtypes.html#memoryview

There is way to get some analog of C-pointers: `id(variable)`

As I understand correctly, you want something like `v.obj is v2.obj`.
Explanation:
```python3
# Different source data with identical content
a = b"abc"
b = b"abc"
# `am` and `am_alt` shares one data buffer
am = memoryview(a)
am_alt = memoryview(a)
bm = memoryview(b)

# `==` compares memory, `is` compares if this is the one instance
am == bm # True, because memory equal (but stored in different places)
am is bm # False, because there is two different memoryviews objects

am is am_alt # False, because there is two different memoryviews objects
am.obj is am_alt.obj # True, because they points to one memory
am.obj is bm.obj # False, because they points to different memory (but with the same data)

id(am.obj) # 140607418282464
id(am_alt.obj) # 140607418282464
id(bm.obj) # 140607418282512
```

**Comment by aspadm** [comment]
Look like d06cc81 will be work, but now it allows two memoryview objects that share data (because `v.obj is v2.obj` can be True when `v is v2` is False).

**Comment by jcupitt** [comment]
I'm not sure it matters in this case, but I agree comparing `id()` seems clearer.

**Comment by jcupitt** [comment]
( https://github.com/libvips/pyvips/commit/5988ebd8466179ba7d2975baf10f53614274e18c uses id() rather than "is")

**Comment by aspadm** [comment]
> I'm not sure it matters in this case, but I agree comparing `id()` seems clearer.

Basically, `id(v) == id(v2)` equals to `v is v2`.

But I worry that you compare memoryviews instead of `arg`. It means that in most cases memoryviews are differs, but they can points to one memory.

**Comment by jcupitt** [comment]
I fixed the append/extend thing too (I always get that one wrong)

**Comment by jcupitt** [comment]
I think it's OK -- we want to keep references to memory objects to stop them being GCd. We don't need to worry what bit of memory they in turn refer to, or how many times the memory is aliased.

**Comment by aspadm** [comment]
I just tested fix with my scripts and it works well.
Thanks for your work!

**Comment by jcupitt** [comment]
Thanks for testing -- I'll push 2.1.13 with this fix.

**Comment by jcupitt** [comment]
... 2.1.13 is now out.
