### ISSUE TITLE
Unable to write to memory

### ISSUE THREAD

**Issue by telemachor** [libvips/pyvips#213]
Hello, 
I use pyvips for reading big ndpi files. I am facing memory probem in the following simple situation:

```
import pyvips

img = pyvips.Image.openslideload('file.ndpi', level=0, access='sequential')
#img has (164864, 112896) shape

#some code for example
img = img + 1

img.write_to_file('1.tiff')


tmp = img.crop(0, 0, 2048, 2048)
#vips2numpy is function from docs
res1 = vips2numpy(tmp)

img2 = pyvips.Image.new_from_file('1.tiff', access='sequential')
tmp = img2.crop(0, 0, 2048, 2048)
res2= vips2numpy(tmp) 

```
On the last line I'm getting the following error:
Error: unable to write to memory
  TIFFFillStrip: Invalid strip byte count 0, strip 12
tiff2vips: read error
vips_region_prepare: unable to input from a (null) image

If I set level=1 everything works fine. If I set level=1 and access='random' in the end it crashes again and starts work from level=2 or 3.

Could you tell me what this is connected with and how to avoid it?
Thank you.

**Comment by jcupitt** [comment]
Hi @telemachor,

Your code:

```python
img = pyvips.Image.openslideload'file.ndpi', level=0, access='sequential')
#img has (164864, 112896) shape
#some code for example
img = img + 1
img.write_to_file('1.tiff')
```

Will write a float TIFF and it'll be *enormous*, perhaps 300gb. 

I would make sure you cast down to 8-bit (if that's correct), I would remove the alpha channel, and I would consider writing a tiled, compressed TIFF. Something like:

```python
img.cast("uchar")[0:3].write_to_file('1.tiff', tile=True, compression="jpeg", Q=90)
```

Is this for ML training? You could consider using `fetch` instead of `crop`, it can give a large speedup.

https://github.com/libvips/pyvips/issues/100#issuecomment-493960943

**Comment by telemachor** [comment]
Thank you @jcupitt for the quick answer.

> Will write a float TIFF and it'll be enormous, perhaps 300gb.

It's histology image. Source ndpi image is ~3.5Gb.  
After writing '1.tiff' image is ~4.5 with my code. I didn't know about casting image to float. Thanks for this.

I tried your code step by step.
Using cast("uchar") writing was 1.5 times faster. But the error still remains.
When I cut alpha channel problem shifted a little. It raised when i tried access center of image.

Using tiled copressed TIFF i got following error:

Error: unable to call VipsForeignSaveTiff
  TIFFAppendToStrip: Maximum TIFF file size exceeded
vips2tiff: TIFF write tile failed
wbuffer_write: write failed
unix error: Unknown error -1
TIFFWriteDirectoryTagData: Maximum TIFF file size exceeded

And suddenly I think I understood the problem. I add bigtiff=True flag while writing. I think it solves the problem. As soon as my file (considering > 70GB) was 4GB writer fill end of image with zeros. I checked it using tiffile.
![photo_2020-11-26_15-22-12](https://user-images.githubusercontent.com/24947123/100350764-6a33ab80-2ffb-11eb-83ab-d19c7d1fa5aa.jpg)
![photo_2020-11-26_15-22-02](https://user-images.githubusercontent.com/24947123/100350766-6b64d880-2ffb-11eb-8c3f-8a2284da4fbe.jpg)

As I understand the option fail should raise some error while writing? I tried to set it up but got KeyError: 'fail' for openslideload.
Is it possible to add some extra check for writing?

Thanks for the help. I really appreciate it.

> Is this for ML training? You could consider using fetch instead of crop, it can give a large speedup.

Not at the moment. But in the future, perhaps yes. Thank you. Will keep in mind.  
For now I want to use pyvips for applying affine transform for large images.

**Comment by jcupitt** [comment]
openslide doesn't really support warnings -- it either reads, or does not.

Yes, you need to enable bigtiff by hand if you are writing large, compressed images.

**Comment by jeremyEudaric** [comment]
hello l got the same error :
 import pyvips as pv
pv = pv.Image.new_from_file("/Users/eudari01/..../test/1.jpg", level=0, access="sequential")
pv.tiffsave('1.tif')
Error: VipsForeignLoadJpegFile does not support optional argument level
could you help me ?

**Comment by jcupitt** [comment]
Please open a new issue for a new question.

In your case, JPEG images don't have levels. You'd need to explain what you are trying to do.

**Comment by SadeghNasr** [comment]
> fetch

@jcupitt Would you please elaborate on how to use `fetch` instead of `crop`.
