### ISSUE TITLE
Problem-related to stacked ndpi image and downsampling

### ISSUE THREAD

**Issue by Yuvi-416** [libvips/pyvips#215]
Hi there,
I have a stacked ndpi image, each series has 11 images. I can read first stack by using 
pyvips.Image.openslideload(filename='1.ndpi’, level=0)
But I want also want to read second, third, fourth, ...., eleven stack.
How can I achieve that?
And one another question, how can I downsample level=0, 40x image into a smaller size and what should  be the correct value of the downsample, 
For an example: 
Level 0 shows : Image Width: 186496 Image Length: 36608
I want to downsample it into 93248x18304.
Is there any easy way to do it?
I want to perform all these steps in python.
Any suggestion🙂

**Comment by jcupitt** [comment]
Hi @Yuvi-416, the `level` argument sets the level you'd like to read from the image, so eg.:

```
$ python3
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvips
>>> x = pyvips.Image.new_from_file("Mirax2.2-1.mrxs")
>>> x.width
101832
>>> x.height
219976
>>> x = pyvips.Image.new_from_file("Mirax2.2-1.mrxs", level=1)
>>> x.width
50916
>>> x.height
109988
```

**Comment by jcupitt** [comment]
If you need a specific size, I would use `thumbnail`. It should efficiently pick the correct layer for you.

For example:

```
$ python3
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvips
>>> x = pyvips.Image.thumbnail("Mirax2.2-1.mrxs", 1000, height = 800)
>>> x.width
370
>>> x.height
800
```

It's selected and resized a layer to fit inside a 1000 x 800 area.

**Comment by Yuvi-416** [comment]
Hi,
Thanks for your reply,
With the help of thumbnail, yeah now I can resize the image as in the desired choice. Thanks for that.
and,
As you have mentioned in the first comment,
x = pyvips.Image.new_from_file("Mirax2.2-1.mrxs", level=1)
I guess it only shows series or pyramid levels height and weight. 
I  have an image in a .ndpi format, and inside it, there are five series and in each series, there are 11 images. 
When i run this below code;
x = pyvips.Image.new_from_file("Mirax2.2-1.mrxs", level=1).....level: 0 to 8 (it only read first stack: i mean first 9 pyramid).
But I also want to read the second pyramid which also has five series with 11 images. How can I select a second stack from that image?
Any thought

**Comment by jcupitt** [comment]
Ah gotcha. I don't know if openslide supports slides with more than one series. Do you have a sample multi-series slide anywhere? Not too big, ideally.

**Comment by Yuvi-416** [comment]
so it means pyvips.new_from_series use openslide function. I know openslide doesn't support focal length images.
Yeah, I have but it's size is around 4.85GB.
Currently, I am using bioformats to read it but I am having trouble to downsample over there.
I don't know I can use the pyvips.image.thumbnail() function to downsample bioformats read function.
https://github.com/ome/bioformats/issues/3641
If you have any experience on this, then any little suggestion might help me to downsample the input.

**Comment by jcupitt** [comment]
If it can be read as an OME-TIFF, pyvips would be able to get other series. Post a link to a sample image and I'll have a look.

**Comment by Yuvi-416** [comment]
Here is the data:
https://uapt33090-my.sharepoint.com/:u:/g/personal/ygupta_ua_pt/EUELGq1xuQ5Eu3jewAB04NkBn_B5gZUwmHd8hP_D2U4lSQ?e=1nAG9r

**Comment by jcupitt** [comment]
Sorry @Yuvi-416, I missed your link :( Would you mind posting again?

**Comment by Yuvi-416** [comment]
Thanks for your concern, but luckily I found the solution for it.
Anyway, once again thank you!
