### ISSUE TITLE
How to extract one channel from mrxs?

### ISSUE THREAD

**Issue by gmh1033286494** [libvips/pyvips#216]
Hi @jcupitt
Fantastic work, really helped a lot.

My goal is to do the image registration for 2 mrxs image. So my workflow is 1: extract 2 Dapi channels of a lower level, usually level 4 or 5 to do the image registration and get the transformation matrix. This way it is much faster; 2: use the transformation matrix to  transform all channels of level 1 of the target mrxs.  3 put all channels of both image into 1 tiff. 4 If possible convert the tiff into mrxs. 

I am wondering if I can do the extract job and the put all channels togerther job with pyvips. Currently I am using 3Dhistech slide  converter to do the extract job. I find the way to extract certain level of mrxs with pyvips and rotate the image but I did not find a way to extract the channel. Besides is is possible to convert the tiff to mrxs with pyvips?

Thank you very much. Looking forward to your advice. 
Here is the five channels in my Mrxs
![image](https://user-images.githubusercontent.com/62314485/101736349-375edc80-3afe-11eb-9941-d2c6d3cc3b94.png)

**Comment by jcupitt** [comment]
Hello @gmh1033286494, 

You can use `[]` to extract bands, for example `a[0]` gets the first one. You can slice ranges too, so `a[1:]` is all bands except the first. Use `bandjoin` to join bands together, eg. `a[0].bandjoin(a[2:])` removes band 1.

You can use `affine` to apply a transform to an image, you've probably found it.

openslide can only load mrxs images, not save them, so you'll need to use a different format. Tiled pyramidal JPEG-compressed TIFF is probably the best.

**Comment by gmh1033286494** [comment]
Thank you for your super fast reply! 
I found an example to extract level
vips copy xxx.mrxs[level=5] testvipmrxs2tif.tif[pyramid,tile,compression=jpeg]
Could you give me a python example of the usage you just showed? I am a beginner.
Thank you very much.

Also do you have any advice for image registration for large WSI image. I am using pathflow-mixmatch but I am wondering if there is a faster or better way.

**Comment by jcupitt** [comment]
Sure:


```python
#!/usr/bin/python3

import pyvips

image = pyvips.Image.new_from_file("something.mrxs", level=5)
dapi = image[0]
dapi.write_to_file("dapi.tiff", pyramid=True, tile=True, compression="jpeg")
```

There are many, many ways of doing registration -- it depends what kind of transform you want to estimate, how much time you have, what your accuracy requirements are, etc. etc.

pyvips can apply affine transforms (`affine`) and grid transforms (an array of vectors, see `mapim`). I would estimate the transform on level 5 and apply on level 0 after scaling. You'll need to rescale the transform, of course.

**Comment by mhguo1993** [comment]
Thank you for your advice. 
I just want to do some rotate and move of the image. But usually the WSI is huge and I got stucked at getting the transformation matrix. Pathflow-mixmatch only returns 2 registrated image which is half way of my goal.

**Comment by gmh1033286494** [comment]
A quick update. 
I tried the python code and it worked but something wired happened. When I tried to load it with QuPath, QuPath told me that it not a pyramid and could not properly show it. However, I checked with openslide. There were 8 level in it and I could read it properly with a normal image reader. Besides, when I used the same code without the channel part'dapi = image[0] 'just extract the level 5 image, everything seems fine in QuPath but it seems to lost 2channels. I guess maybe it's something wrong with QuPath.


About the image registration, I tried the pathflow-mixmatch (https://github.com/jlevy44/PathFlow-MixMatch). It seems to work fine but I just can get the transformation matrix. Is there other ways to do the job and get the transformation matrix. I don't think I can ignore the transformation matrix since the size of my WSI is 80000*120000. This level could not support registration due to the lack of memory.  

Thank you. Look forward to learning from you.
Level 5 Dapi is not recognized as  pyramid by Qupath
![image](https://user-images.githubusercontent.com/62314485/101871057-d4cd1580-3bbd-11eb-8ee7-6c0ca1e8dd89.png)

Not being properly showed in QuPath, the pyramid is auto generated by QuPath
![image](https://user-images.githubusercontent.com/62314485/101871187-19f14780-3bbe-11eb-85c7-85296cf06d09.png)

can be properly read with a reader
![image](https://user-images.githubusercontent.com/62314485/101871000-b6671a00-3bbd-11eb-8a22-f54f74ea08a0.png)

image of level 5 with 3 channels instead of 5 in QuPath
![image](https://user-images.githubusercontent.com/62314485/101871366-676db480-3bbe-11eb-9abc-ae5902ed71ca.png)

The code I used:
image = pyvips.Image.new_from_file("/home/chixing/test/正式实验芯片.mrxs", level=4)
dapi = image[0]
dapi.write_to_file("dapi4.tiff", pyramid=True, tile=True, compression="jpeg")
image.write_to_file("image4.tiff", pyramid=True, tile=True, compression="jpeg")

**Comment by jcupitt** [comment]
QuPath only loads subifd sypramids. Try saving with `subifd=True`.

**Comment by gmh1033286494** [comment]
dapi.write_to_file("dapi4.tiff",pyramid=True,subifd=True,tile=True,compression="jpeg")
Where should I put it? I tried 4 places and it seems all errors.

**Comment by jcupitt** [comment]
Perhaps you have an old libvips? You need 8.10.

**Comment by gmh1033286494** [comment]
Can I use sudo apt install libvips to get the latest libvips? It seems that I can only get libvips42:amd64 (8.9.1-2). 
I also tried to install from a source tarball. I don't think I succeeded. 
![Screenshot from 2020-12-11 16-23-03](https://user-images.githubusercontent.com/62314485/101880307-a5bea000-3bcd-11eb-95d5-9b637baa1198.png)
Besides, how to add optional dependency like file import with openslide. I think I have openslide in my ubuntu 
![Screenshot from 2020-12-11 16-28-13](https://user-images.githubusercontent.com/62314485/101880455-e9b1a500-3bcd-11eb-8285-dd9bb2ef1d0d.png)

**Comment by gmh1033286494** [comment]
A quick update 
(base) chixing@chixing:~$ vips --version
vips-8.10.2-Mon Oct 12 16:43:59 UTC 202

I think I got 8.10. I tried again.

unable to load from file b'/home/chixing/test/\xe6\xad\xa3\xe5\xbc\x8f\xe5\xae\x9e\xe9\xaa\x8c\xe8\x8a\xaf\xe7\x89\x87.mrxs'
  VipsForeignLoad: "/home/chixing/test/正式实验芯片.mrxs" is not a known file format 

It seems that new libvips does not have the dependency of OpenSlide.

**Comment by jcupitt** [comment]
You need to install the `-dev` versions of the various packages before configuring libvips, for example `libopenslide-dev`.

The website has some notes:

https://libvips.github.io/libvips/install.html#building-libvips-from-a-source-tarball

**Comment by gmh1033286494** [comment]
Hi, I installed packages I wanted. But I still get the same error telling me that it can open the this mrxs. But I could open it when using 8.9.2.
x-special/nautilus-clipboard
copy
file:///home/chixing/Pictures/Screenshot%20from%202020-12-15%2014-54-17.png
x-special/nautilus-clipboard
copy
file:///home/chixing/Pictures/Screenshot%20from%202020-12-15%2014-55-04.png

The code
image = pyvips.Image.new_from_file("/home/chixing/test/zssy.mrxs", level=4)

The error message
<ipython-input-21-f27d58e35c48> in <module>
----> 1 image = pyvips.Image.new_from_file("/home/chixing/test/zssy.mrxs", level=4)

~/miniconda3/lib/python3.8/site-packages/pyvips/vimage.py in new_from_file(vips_filename, **kwargs)
    226         pointer = vips_lib.vips_foreign_find_load(vips_filename)
    227         if pointer == ffi.NULL:
--> 228             raise Error('unable to load from file {0}'.format(vips_filename))
    229         name = _to_string(pointer)
    230 

Error: unable to load from file b'/home/chixing/test/zssy.mrxs'
  VipsForeignLoad: "/home/chixing/test/zssy.mrxs" is not a known file format

Thank you.

**Comment by gmh1033286494** [comment]
A quick upate
problem solved. I need to restarted.
