### ISSUE TITLE
ModuleNotFoundError when importing in Colab

### ISSUE THREAD

**Issue by gamesMum** [libvips/pyvips#217]
I'm trying to use the package, but I'm having a module not found an error even though I have pip installed the package
`!pip install pyvips`
`import pyvips`

And here is the error message

```ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-25-d4dafbf99536> in <module>()
----> 1 import pyvips
      2 import hub
      3 from hub import Dataset, features
      4 import numpy as np
      5 from hub.collections import dataset, tensor

ModuleNotFoundError: No module named 'pyvips'
```

**Comment by jcupitt** [comment]
Try this:

```
%%capture
!apt-get update
!apt-get upgrade
!apt-get install libvips
!pip install pyvips
!pip install cffi
!pip show pyvips
```

Then this should work:

```
import numpy as np
import matplotlib.pyplot as plt
import pyvips
import skimage.transform
```

I'm not sure why the cffi is necessary -- you'd think pip would install that automatically.

**Comment by gamesMum** [comment]
Thanks this resolved the issue

**Comment by jcupitt** [comment]
Demo colab project: https://colab.research.google.com/drive/1W5RIdk-F6YOynOx-LNJFWSCzLyxFY8F5?usp=sharing

That's using a rather old libvips (8.4.5). You can build your own libvips and run that within colab with eg.:

https://colab.research.google.com/drive/1z6SxNwHZxyCj-OMZ5Ic2sytp9zFon-T2?usp=sharing
