### ISSUE TITLE
Trouble creating custom source (CFFI AttributeError)

### ISSUE THREAD

**Issue by NickWer** [libvips/pyvips#218]
Hi. I'm using a python docker container that runs on alpine (`python:3.8.1-alpine`) and trying to create a custom source, bur it crashes every time:

```python
>>> src = pyvips.SourceCustom()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/pyvips/vsourcecustom.py", line 24, in __init__
    source = ffi.cast('VipsSource*', vips_lib.vips_source_custom_new())
AttributeError: cffi library '_libvips' has no function, constant or global variable named 'vips_source_custom_new'
```

Some debugging output:
```
$ pip show pyvips
Creating nucleo_django_run ... done
PostgreSQL is available
sh: show: unknown operand
Name: pyvips
Version: 2.1.12
Summary: binding for the libvips image processing library, API mode
Home-page: https://github.com/libvips/pyvips
Author: John Cupitt
Author-email: jcupitt@gmail.com
License: MIT
Location: /usr/local/lib/python3.8/site-packages
Requires: pkgconfig, cffi
```

```python
>>> _libvips.lib.VIPS_MAJOR_VERSION
8
>>> _libvips.lib.VIPS_MINOR_VERSION
8
>>> _libvips.lib.VIPS_MICRO_VERSION
4
```

in our compose:
<img width="671" alt="Screen Shot 2020-12-14 at 5 18 34 PM" src="https://user-images.githubusercontent.com/3439382/102142505-81aec900-3e30-11eb-8050-72274a79a499.png">
<img width="334" alt="Screen Shot 2020-12-14 at 5 18 50 PM" src="https://user-images.githubusercontent.com/3439382/102142502-81163280-3e30-11eb-826a-071b28e70d2b.png">

and finally, our pipfile has`pyvips==2.1.12` required

With this setup i've been able to do some other operations using`pyvips`, but creating the custom source hasn't been successful. Please let me know if there's something I'm overlooking or if there's more information that could be helpful. I can also try setting up a full repository to reproduce the issue if needed. All ideas are welcome and appreciated 🙂

**Comment by jcupitt** [comment]
Hi @NickWer,

Your libvips is too old -- the new source / target system was added in libvips 8.9. Current stable is 8.10.4.

**Comment by NickWer** [comment]
Hi! Sorry, I've been out of the office for a few days. I'll give that a try and see if that resolves things. I really appreciate your help!

**Comment by NickWer** [comment]
It worked! I submitted a PR but the immediate problem is resolved. I'll leave you to decide if you'd like to close this now or once the PR is merged. Thanks a bunch 🙂
