### ISSUE TITLE
How to convert format of Image class?

### ISSUE THREAD

**Issue by soomiles** [libvips/pyvips#219]
Hi, I'm trying to overlay a mask on an large histopathology image.

```
# read & generate mask
image = pyvips.Image.new_from_file(img_path)
width, height = image.width, image.height

mask = read_mask_file(mask_path, (height, width))
linear = mask.reshape(width * height)
mask = pyvips.Image.new_from_memory(linear.data, width, height, 1,
                                    dtype_to_format[str(mask.dtype)])

# overlay
out = (image * 0.8 + mask * 0.2)

# save as tiff
out.tiffsave('view.tiff', tile=True, pyramid=True, bigtiff=True)
```

However, the result's format is float, so every pixels are saved as white. (because the all pixel values are over 1.)
If I do rescale this image as
```
out = out / 255
```
then, it is saved as float, so file size is too huge.

How to convert Image format from float to uchar?

**Comment by jcupitt** [comment]
Hello @soomiles, just do:

```python
y = x.cast("uchar")
```

What format is your mask file in?

**Comment by soomiles** [comment]
@jcupitt Thanks a lot!!
It's 'char'!
