### ISSUE TITLE
How to apply affine matrix using .affine()

### ISSUE THREAD

**Issue by gmh1033286494** [libvips/pyvips#220]
Hi, @jcupitt.
Here I am again. I am still working my image registration. I finally get my transformation matrix. My goal is to apply this matrix to level 0 of my orginal WSI.
[ 1.0020902  -0.00375375 -0.00611446]
 [ 0.00388862  0.9673335   0.00906466]
I try to apply this matrix using .affine()

_image_affined = image.affine(matrix)_  

it tells me: expected new array length or list/tuple/str, not numpy.ndarray

When I turned it into list

_image_affined = image.affine(matrix.tolist())_

it tells me:must be real number, not list

Could you give me an example of how to use .affine()? Which of these arguments I musht input? 

out = in.affine(matrix, interpolate=GObject, oarea=list[int], odx=float, ody=float, idx=float, idy=float, background=list[float], extend=str)

Thank you very much.

**Comment by jcupitt** [comment]
Hi @gmh1033286494,

Something like:

```python
y = x.affine([a, b, c, d])
```

Where the four numbers are the 2x2 matrix:

```
a b 
c d
```

See:

https://libvips.github.io/libvips/API/current/libvips-resample.html#vips-affine

What are the other two numbers in your 2x3 matrix?

**Comment by gmh1033286494** [comment]
I think it is the displacement or the delta of ax+by+displacement = 0

**Comment by gmh1033286494** [comment]
I think it is the translation

**Comment by jcupitt** [comment]
Ah OK, then use those two to set `idx` and `idy` I think.

**Comment by gmh1033286494** [comment]
It worked. But I don't think I can apply the transformation matrix I got from 2 smaller level directly to the level 0. Instead I need to rescale the matrix. Could you give me some advice on how to rescale it?

**Comment by gmh1033286494** [comment]
I made a mistake by input a wrong parameter into the affine(). I think I got it for now. Thank you.
