### ISSUE TITLE
How to affine a image without additional pading?

### ISSUE THREAD

**Issue by gmh1033286494** [libvips/pyvips#226]
Hi @jcupitt. Happy New Year.
Here I am again.
I did some experiment on the Affine function. I applied the transformation matrix I got from Air-lab to moving image with skimage, opencv and vips. Can Vips achieve the same result as the other two? I think vips did a lot pading for the result image. But I just need the type of pading like the other two.  Vips is supper fast dealing with large WSIs. I don't think cv or skimage can do it as fast as vips.

_vips_image = moving_image_vips.affine((T[0][0],T[0][1],T[1][0],T[1][1]),idx = T[0][2], idy = T[1][2])
warped_sk_image = skimage.transform.warp(np_moving_image.numpy(), inverse_map=Tinv)
warped_cv2_image = cv2.warpAffine(moving_image.numpy(), T[0:2, :], (fixed_image.size[1], fixed_image.size[0]))_

![image](https://user-images.githubusercontent.com/62314485/103507203-96173c00-4e99-11eb-933b-b04af50a613e.png)

Thank you very much!  

This is the WSI result I manually resized and merge into a multi-paged image, showing in HALO 
![image](https://user-images.githubusercontent.com/62314485/103476173-6828ed80-4dee-11eb-85f9-d775951ddd7a.png)

**Comment by jcupitt** [comment]
Hello again,

By default, libvips outputs the entire transformed image, ie. it transforms the four corners of the input, then outputs the bounding box. You can set **oarea** to output some other rect.

For example, given:

![astronauts](https://user-images.githubusercontent.com/580843/103544167-91518880-4e97-11eb-9c71-6a09847b26db.png)

Running: 

```
vips similarity astronauts.png x.png --scale 1 --angle 10
```

Gives:

![x](https://user-images.githubusercontent.com/580843/103544218-a7f7df80-4e97-11eb-8988-81bbab797279.png)

In that output image, the point (0,0) in the input has moved to (156, 0) in the output. In other words, **oarea** has defaulted to left = -156, top = 0, width == 1043, height = 1043.

For your case, you need to look carefully at the transform you want and think about where the transform origin should be and what pixels from the input you want to throw away.

**Comment by gmh1033286494** [comment]
How do you generate your bounding box? I notice the that there is a Union argument in Affine function. How does it work? 
Is there any thing like warpaffine of cv2 in vips? I am trying to figure out if I can reproduce the process of warpaffine of cv2 with vips.

**Comment by jcupitt** [comment]
You just transform the four input coordinates and take the bounding box.

Yes, you can duplicate warpaffine, you'll just need to compute oarea.

**Comment by gmh1033286494** [comment]
After some thinking I find that I do not really need to calculate the new coordinates in order to match the moving image with the fixed image because their  coordinate systems are the same before moving image being affined and I believe vips affine calculate the oarea based on the old coordinate system. So I do not need to do anything to match the two images. Here are codes and results.

vips_image = moving_image_vips.affine((T[0][0],T[0][1],T[1][0],T[1][1]),odx = T[0][2], ody = T[1][2],oarea = (0,0,np_moving_image.shape[1],np_moving_image.shape[0]))

![image](https://user-images.githubusercontent.com/62314485/103753556-24302580-5046-11eb-9d96-6224edce671a.png)
