### ISSUE TITLE
dzsave: Controlling the number of zoom levels when doing map tiles

### ISSUE THREAD

**Issue by acycliq** [libvips/pyvips#232]
I guess that will sound a bit awkward but I would like to ask if there is any way to control the number of zoom levels you get when you create an pyramid of tiles with `im.dzsave`. More specifically if the image is  lets say `262144px-by-262144px` then running `dzsave` will create 10 zoom levels (and the relevant directory structure on the disk). 

Can I tell dzsave to give only 8 levels while keeping the image size the same? I could downscale the image to  `65,536-by-65,536` but I was wondering if there is a way without having to do this please.

many thanks!

**Comment by jcupitt** [comment]
Hi @acycliq ,

Do you mean you want to skip the two largest pyramid layers when writing? Yes, you'll need to downsample by 4x before calling dzsave.

If you are using a slide image as a source, you could just tell libvips to start with a level other than 0 (the highest res -one). For example:

```
$ vips dzsave CMU-1.svs[level=2] x
```

**Comment by acycliq** [comment]
Ok, thanks a lot John!
