### ISSUE TITLE
Openslideload Miraxis Fetch

### ISSUE THREAD

**Issue by imgifty** [libvips/pyvips#233]
Hello,
I'm trying to speed up my patch sampling procedure from whole slide images in 'miraxis' format. As it seems, my sampling procedure spends the most time while fetching patches using openslide.
To improve the speed, I tried replacing the openslide calls using vips:

```python

 # the patch sampling fetch
def get_region(image, box, level):
    x0, y0, x1, y1 = box
    width = x1 - x0
    height = y1 - y0
    tile = image[level].fetch(x0, y0, width, height)
    np_3d = np.ndarray(buffer=tile,
                       dtype=np.uint8,
                       shape=(height, width, 3))
    return np_3d

 # initialization code
levels = 3
images = {}
for level in range(levels):
      image = pyvips.Image.new_from_file(filename, level=level)
      # image = pyvips.Image.openslideload(filename, level=level) # alternatively

      images[level] = pyvips.Region.new(image)

get_region(images, box, 0)
```

This code works for my 'label' images, which are tiled '.tiff' images. When I try to use the `get_region` function using vips, I get images looking as follows: 

![example](https://user-images.githubusercontent.com/6561496/106401774-2d829700-6426-11eb-833f-71635ef6298f.png)

On a side note, will the fetch even improve the performance on 'mrxs' slides opposed to using crop?

Thanks a lot!

**Comment by jcupitt** [comment]
HI @imgifty,

openslide main images have four bands (RGBA). I'd drop the fourth after load, eg.:

```python
      image = pyvips.Image.new_from_file(filename, level=level)
      image = image[0:3]
      images[level] = pyvips.Region.new(image)
```

Yes, fetch can be quicker than crop -- it depends on the patch size. At 512x512, crop might be faster, but at 32x32, fetch should win.

**Comment by imgifty** [comment]
> HI @imgifty,
> 
> openslide main images have four bands (RGBA). I'd drop the fourth after load, eg.:
> 
> ```python
>       image = pyvips.Image.new_from_file(filename, level=level)
>       image = image[0:3]
>       images[level] = pyvips.Region.new(image)
> ```
> 
> Yes, fetch can be quicker than crop -- it depends on the patch size. At 512x512, crop might be faster, but at 32x32, fetch should win.

Thanks a lot, that seems to have fixed the problem.
It seems, as though crop still seems to perform faster for me.
