### ISSUE TITLE
WSI downscaling

### ISSUE THREAD

**Issue by karray** [libvips/pyvips#235]
I have a bunch of WSIs  (svs, ndpi, mrxs) that were produced by different scanners and hence have different Microns per Pixel. I want to scale them to the same MPP and after that create tissue map using PyHIST.

Is there a way to resize (a single level of) a WSI and save it with the same compression and format?

**Comment by jcupitt** [comment]
Hi @karray,

You can't always save with the same compression, since many slide images use jp2k, and that's not widely supported in TIFF.

I would save as jpeg-compressed tiled tiff with a high Q. For example:

```
vips copy someslide.svs[level=2] x.tif[tile,compression=jpeg,Q=85]
```

**Comment by karray** [comment]
Hi @jcupitt, thanx for you fast replay. I managed to resize an svs slide using openslide and PIL (which is inefficient since the whole image is loaded into RAM)

Now, I have a bunch of tiles (png) with coordinates in xml. What I want to do is reassemble these tiles back into the slide (e.g. tiff). Can I achieve this with the vips/pyvips?

**Comment by jcupitt** [comment]
Could you explain how you made these tiles? I'm not sure I understand how or why the image became chopped up.

**Comment by karray** [comment]
Sorry, the question is not related to the OP. I just wonder if it is possible to merge a bunch of image into a WSI

I used the [PyHIST](https://github.com/manuel-munoz-aguirre/PyHIST) lib to split an WSI into patches. I need this step in order to train my style transfer model. Now, I processed all these patches and want to reassemble them back into WSI. I have a file with a name of a patch and its row and column in the WSI. Basically, I have to go through all records in that file and append each patch to a numpy array, but I'm looking for an alternative approach

**Comment by jcupitt** [comment]
Ah gotcha. 

Yes, you can use `arrayjoin` to join up large arrays of images:

https://libvips.github.io/pyvips/vimage.html#pyvips.Image.arrayjoin

It'll (probably) need a file descriptor per patch, so you may need to raise your per-process fd limit. I have mine set to 65536.
