### ISSUE TITLE
tiffsave large numpy array

### ISSUE THREAD

**Issue by karray** [libvips/pyvips#236]
I'm trying to save a large image  (which is `ndarray` of size 49664x38656x3)  as `tiff` using `Image.new_from_memory` as follows:

```py
wsi= np.full((49664, 38656, 3), 255, dtype=np.ubyte)

# processing ....

slide = pyvips.Image.new_from_memory(wsi, wsi.shape[0], wsi.shape[1], wsi.shape[2], 'uchar')
slide.tiffsave('test.tiff'), compression='jpeg', Q=80, tile=True, tile_width=128, tile_height=128, pyramid=True)
``` 

if I plot `ndarray` everything is ok:
![image](https://user-images.githubusercontent.com/1911342/107129951-89876880-68c9-11eb-82cd-2196e4dc8c84.png)

but after `tiffsave` I get this:
```
from openslide import open_slide

wsi_test = open_slide('test.tiff')
plt.imshow(wsi_test.read_region((10000, 10000), 0, (13000, 13000)))
```

![image](https://user-images.githubusercontent.com/1911342/107130156-239be080-68cb-11eb-927a-a33d6b0f37c9.png)

Any hints?

**Comment by jcupitt** [comment]
Hi @karray,

At a guess, openslide will return a four band image (RGBA), not three. Could there be a mixup? You'd need to post a complete, runnable program plus a sample image before I could do any checking.

**Comment by karray** [comment]
Hi @jcupitt 

if I do the same but with a small image, everything works as expected

```py
from PIL import Image as PImage
import pyvips
import numpy as np
from openslide import open_slide

patch_size = 128
n = 4

img = np.full((patch_size*n, patch_size*n, 3), 255, dtype=np.ubyte)

for i in range(0,n):
    for j in range(0,n):
        img[i*patch_size:i*patch_size+patch_size, j*patch_size:j*patch_size+patch_size] = np.array(PImage.open(path_tiles[i*n+j]), dtype=np.ubyte)

slide = pyvips.Image.new_from_memory(img, img.shape[0], img.shape[1], img.shape[2], 'uchar')
slide.tiffsave( 'test.tiff', compression='jpeg', Q=80, tile=True, tile_width=128, tile_height=128, pyramid=True)

wsi = open_slide('test.tiff')
wsi.read_region((0, 0), 0, wsi.dimensions)
```
![image](https://user-images.githubusercontent.com/1911342/107377012-cd0ced00-6aea-11eb-8828-6b2402c290ca.png)

**Comment by karray** [comment]
I found what cause the problem. This happens if the resolution is not NxN. Here is an example of a white image with a black rectangle in the middle

```py
m = 1024
n = 512
a = np.full((m, n, 3), 255, dtype=np.ubyte)
a[m//2-m//4:m//2+m//4, n//2-n//4:n//2+n//4] = 0
slide = pyvips.Image.new_from_memory(a, a.shape[0], a.shape[1], a.shape[2], 'uchar')
slide.tiffsave('test.tiff', compression='jpeg', Q=80, tile=True, tile_width=128, tile_height=128, pyramid=True)
wsi = open_slide('test.tiff')
wsi.read_region((0, 0), 0, wsi.dimensions)
```
Here is the plot of numpy array `a`:
![image](https://user-images.githubusercontent.com/1911342/107384700-7f947e00-6af2-11eb-8a56-2a6d01520ac3.png)

Here is the resulting `tiff`:
![image](https://user-images.githubusercontent.com/1911342/107384811-9935c580-6af2-11eb-85af-e8356d660ca5.png)

**Comment by jcupitt** [comment]
Ah OK. Yes sometimes it's rows and columns instead :( I always get confused.
