### ISSUE TITLE
pngsave: how to cancel quantizing when there are more than 256 colors in the image?

### ISSUE THREAD

**Issue by int-ua** [libvips/pyvips#239]
When `pngsave()` is used with `palette=True` and an image with more than 256 colors the save process becomes lossy without any warnings.

It can be workarounded by counting number of colors prior to saving but I haven't found a way to do that with `pyvips` directly yet, any suggestions? The closest thing I've found is https://github.com/libvips/php-vips/issues/65 but it's not the precise count that is required here.

I can imagine a solution to this problem being a new pngsave parameter that signifies that only a lossless conversion is acceptable. When it is set to true simultaneously with `palette` the palette will not be used when there are more than 256 colors in the image.

Do the alpha channel limitations mentioned in http://www.libpng.org/pub/png/book/chapter08.html#png.ch08.div.5.2 make the conversion lossy in any case?

**Comment by jcupitt** [comment]
Hi @int-ua, sorry, I missed this issue :(

I think PNG palettisation is almost always lossy. I think you're right, the alpha is included.

The safest way to tell would probably be to load the image back again and test for equality.

**Comment by int-ua** [comment]
What's the proper way to loop over all pixels of the image in `pyvips`? Or is there a quicker way to count the number of distinct colors?

**Comment by jcupitt** [comment]
You can just do `image(x, y)` to read out a pixel, but it's incredibly slow. I think you'd need to write something in C to get reasonable speed.

Save, reload and test for equality would be a lot quicker than a loop in python.

**Comment by int-ua** [comment]
```py
>>> import pyvips
>>> f = pyvips.Image.new_from_file('1.png')
>>> f.pngsave('2.png', palette=True)
>>> f2 = pyvips.Image.new_from_file('2.png')
>>> f == f2
<pyvips.Image 1920x1080 uchar, 3 bands, srgb>
>>> bool(f == f2)
True
```
but they are not the same, what's the proper way to test for equality?

**Comment by jcupitt** [comment]
`a == b` gives an image with 255 for TRUE and 0 for FALSE, so this will test all pixels for equality:

```python
(a == b).min() == 255
```

**Comment by int-ua** [comment]
Can `pyvips` override the `__bool__` method and return `True` and `False`?

**Comment by jcupitt** [comment]
Oh, interesting idea, I'd never thought of that. Something like this, I guess?

```python3
def __bool__(self):
    return self.min() != 0
```

ie. we're `True` if all elements are non-zero. Does that sound right?

**Comment by int-ua** [comment]
Maybe it can be optimized but it looks like working :)

```py
>>> c = (f == f2)
>>> c2 = (f2 == f2)
>>> (c != 0).min() != 0
False
>>> (c2 != 0).min() != 0
True
```
