### ISSUE TITLE
Saving As  a Pyramidal Tiff Damages the Image Data

### ISSUE THREAD

**Issue by Aiosa** [libvips/pyvips#247]
I have been trying to create pyramidal tiffs from several images, and I've been testing many scenarios - at first, I thought that I can take as many bands as I like and it will create the tiles correctly. Later, I discovered that for 2 banded data only one specific setup worked: DEFLATION compression, one dummy band (black image) to round up to three bands. Since I was expecting to have three-banded data so I was satisfied. Now when I tried to put into third band some real data instead of dummy black image, it stopped working. So I tried to add one dummy band (go RGBA) but that did not work either.

I was using one RGBA (32 bit depth) and two grayscale (8 bit) png's, stitching them together in the following manner:

```
    vis = load(a).copy(interpretation="srgb")[0]  # 1-band png image
    ano = load(b).copy(interpretation="srgb")[0]  # 1-band png image
    decision = load(c).copy(interpretation="srgb")  # RGB png image

    # map decision.R to 128-255 (positive scale), and decision.G to 0-127 reversed (negative scale)
    # this code block was not employed in the testing described below
    dec1 = decision[0].linear(0.5, 128) # 0-255 ---> 128-255
    dec2 = decision[1].linear(0.5, 0) # 0-255 ---> 0-127  
    dec_res = dec1.subtract(dec2).resize(2.0)  #the third image is twice as small as first two

    empty = pyvips.Image.black(vis.width, vis.height, bands=1)
    # number of bands varies
    out = vis.bandjoin([ano, dec_res, empty])

    out.tiffsave(output, compression=pyvips.enums.ForeignTiffCompression.DEFLATE,
                 tile=True, tile_width=width, tile_height=width, #rgbjpeg=True,
                 pyramid=True,  bigtiff=True) 
```
for two bands, 

![image](https://user-images.githubusercontent.com/34658867/115764151-81f23e80-a3a5-11eb-8faf-b021fb4f2ce3.png)

I tried the following scenarios [COMPRESSION | TILE WIDTH | #BANDS] with only two grayscale PNGs (populating the first two bands with real data, filling up the other with empty/black image):

![asd](https://user-images.githubusercontent.com/34658867/115764166-874f8900-a3a5-11eb-8a48-0b86477dfe7f.png)

When I tried similar things with all three images, none worked for me. Either all bands were black (no, not a transparency=0 problem), or all bands except one (green) were set to 255, and I am at my wit's end. I tried then the previous scenarios with other than a black image, white for example:

``` 
empty = pyvips.Image.black(vis.width, vis.height, bands=1).linear(0, 255)
```

which resulted in the same problem as using the last png image to fill the third band. Only a three-banded image, where the last band was set to "empty" produced the expected result.

Saving instead as "png" worked fine. What I am doing wrong?

 Any help would be much appreciated!

**Comment by Aiosa** [comment]
Tried it also using vips tool:

> vips tiffsave image.png image.tif --tile --pyramid --compression=deflate --tile-width 512 --tile-height 512 --bigtiff

the result is a black image...

**Comment by jcupitt** [comment]
Hello again, it should all work.

Could you upload some sample input images, and the full program that produces the error? I need to be able to reproduce the problem.

**Comment by Aiosa** [comment]
Hello, you can find an example at my drive: https://drive.google.com/drive/folders/1f3T_yX7otJlVomMZA3MZULCStFANtRn3?usp=sharing

**Comment by jcupitt** [comment]
I had a quick look at your program.

You can use sequential mode. I would change your `load` def to be:

```python
# load an image and drop the alpha, if present
def load(filename):
    image = pyvips.Image.new_from_file(filename, access="sequential")

    if image.hasalpha():
        image = image[:-1]

    return image
```

In this line:

```python
    vis = load(a).copy(interpretation="srgb")[0]
```

The `copy` is not correct. Your images are mono + alpha and will already have the right interpretation set. Just do:

```python
    vis = load(a)[0]
```

Though it might be better to build this into your `load()` function.

pyvips has a full set of operator overloads, so instead of:

```python
    dec1 = decision[0].linear(0.5, 128) # 0-255 ---> 128-255
    dec2 = decision[1].linear(0.5, 0) # 0-255 ---> 0-127  

    dec_res = dec1.subtract(dec2).resize(2.0)  # reverse dec2, never overlapping with dec1 --> OK to subtract
```

You can just write:

```python
    dec1 = decision[0] / 2 + 128    # red 0-255 -> 128-255
    dec2 = decision[1] / 2          # green 0-255 -> 0-128
    dec_res = (dec1 - dec2).resize(2)
```

Though I'm not sure this is correct --- you'll only have pixels in the range 0-128. Perhaps you meant to OR the pixels together?

You have:

```python
    imgs = [ano, dec_res]
    empty = pyvips.Image.black(vis.width, vis.height, bands=1) 
    for i in range(len(imgs)+1, channels):
        imgs.append(empty)
    out = vis.bandjoin(imgs)
```

You can just use:

```python
    out = vis.bandjoin([ano, dec_res, 0])
```

Though this sets 0 as the alpha channel, which means transparent. You probably want 255 rather than 0. There's also:

```python
    out = vis.bandjoin([ano, dec_res]).addalpha()
```

Which will add 255 or 65535, depending on your images.

You can use strings instead of enums, so for example:

```python
out.tiffsave(output, compression=pyvips.enums.ForeignTiffCompression.DEFLATE,
                 tile=True, tile_width=width, tile_height=width,
                 pyramid=True,  bigtiff=True)
```

Can be written as:

```python
out.tiffsave(output, compression="deflate",
                 tile=True, tile_width=width, tile_height=width,
                 pyramid=True,  bigtiff=True)
```

`output` is a float image, so pyvips is saving it as a float TIFF. Add a cast back to 8-bit before the save, eg.:

```python
out = out.cast("uchar")
```

pyvips is creating the file correctly, but very few viewer programs will be able to display it. The corruption you are seeing is your image viewer having a fit, not an error in the image file. If I run your original program and view in nip2, I see:

![x](https://user-images.githubusercontent.com/580843/115849597-eef4eb00-a41c-11eb-9a61-c0211cd07118.png)

**Comment by jcupitt** [comment]
Revised program:

```python
#!/usr/bin/python3
  
import pyvips


# load an image and drop the alpha, if present
def load(filename):
    image = pyvips.Image.new_from_file(filename, access="sequential")

    if image.hasalpha():
        image = image[:-1]

    return image
    
    
# 3 layered pyramid with 3+ channel output
# use:  pyramid("t1.png", "t2.png", "t5.png", "out.tif", channels=3, width=32)
def pyramid(a, b, c, output, channels=4, width=512, tif=True):
    # one-band images
    vis = load(a)
    ano = load(b)

    decision = load(c)
    dec1 = decision[0] / 2 + 128    # red 0-255 -> 128-255
    dec2 = decision[1] / 2          # green 0-255 -> 128-255
    dec_res = (dec1 - dec2).resize(2)
    
    out = vis.bandjoin([ano, dec_res]).cast("uchar")
    if channels == 4:
        out = out.addalpha()
    
    if tif:
        out.tiffsave(output, compression="deflate",
                 tile=True, tile_width=width, tile_height=width,
                 pyramid=True,  bigtiff=True)
    else:
        out.write_to_file(output)         
    

pyramid("t1.png", "t2.png", "t5.png", "out.tif", channels=3, width=32)
```

**Comment by Aiosa** [comment]
Thanks a lot! I used the interpretation copying in order to make it append the bands rather than merge them into one band (which it did if I left it out), but probably this is resolved by the interpretation change after `bandjoin`. I don't really care about the alpha channel, it was there to just test various bands, I don't display the resulting image but use the RGB values in the shader to decide on the final color.

Again, thank you very much. This looks like it's gonna work.

**Comment by Aiosa** [comment]
On testing image, it looks fine. The crucial was probably to cast the output to unsigned char and to change the interpretation after bandjoin.
![image](https://user-images.githubusercontent.com/34658867/115856830-4307cb80-a42d-11eb-8d19-46f525b8a00c.png)
