### ISSUE TITLE
libvips doesn't properly release file

### ISSUE THREAD

**Issue by peterroelants** [libvips/pyvips#249]
I have a long-running service that uses pyvips underneath. I noticed that pyvips does not properly release the files it accesses. This became apparent when reading files from a [FUSE filesystem](https://en.wikipedia.org/wiki/Filesystem_in_Userspace), where upon after deleting the accessed files, the file inodes where still being kept by the FUSE filesystem because pyvips was still referencing them (see my issue here: https://github.com/Alluxio/alluxio/issues/13324).

I used `lsof` to get the PID of the process holding reference to the file, and `ps` to see what this process was, to figure out that the issue was with pyvips/libvips.

I found a temporary solution my wrapping my code as such:
```python
    try:
        # <Original code that was keeping a reference>
        vips_img = pyvips.Image.new_from_file(input_img_path)
        vips_img_cropped = vips_img.crop(*crop_args)
        cm_res = region.pixel_size_as_cm()
        vips_img_cropped.tiffsave(
            output_img_path,
            resunit=pyvips.enums.ForeignTiffResunit.CM,
            xres=cm_res,
            yres=cm_res,
            depth=pyvips.enums.ForeignDzDepth.ONETILE,
            pyramid=True,
            tile=True,
            properties=True,
            compression=pyvips.enums.ForeignTiffCompression.JPEG,
        )
        # </Original code that was keeping a reference>
    finally:
        # Delete and cleanup files because LibVips seems to keep holding a reference
        try:
            del vips_img
        except NameError:
            pass
        try:
            del vips_img_cropped
        except NameError:
            pass
        gc.collect()
```

I have been using:
- pyvips version 2.1.14
- libvips version 8.10.6

**Comment by jcupitt** [comment]
Hi @peterroelants,

I'd guess you are seeing libvips caching. If you have a large (more than 100mb when uncompressed) image, then your line:

```python
        vips_img = pyvips.Image.new_from_file(input_img_path)
```

Will decompress to a temporary file, open the file, and then delete it. The file descriptor is kept in the libvips operation cache and if later on your code tries to open `input_img_path` again, libvips will skip the decode and reuse the already-decompressed image. The cache is usually harmless and can give a good speedup, but perhaps in this case it's not appropriate. 

The simplest change would be to use sequential mode. Try:

```python
        vips_img = pyvips.Image.new_from_file(input_img_path, access="sequential")
```

This hints to libvips that you will only be reading pixels from this file sequentially (no random access), so it can stream pixels directly from the file. It'll no longer decompress to a temp object and you'll save a file descriptor. You should see a speedup too. 

There's a chapter in the docs explaining how libvips opens files which might be helpful:

https://libvips.github.io/libvips/API/current/How-it-opens-files.md.html

**Comment by jcupitt** [comment]
BTW, you can use strings instead of enums if you like, for example:

```python
            compression="jpeg",
```

I find strings make code easier to read, but YMMV of course.

**Comment by peterroelants** [comment]
I see, and so by explicitly deleting the image object I guess the cache was also cleared. Thank you for this information!

**Comment by jcupitt** [comment]
Actually, libvips will keep the cache entry even after the image has gone. You can try it out at the py prompt:

```
john@banana ~/pics $ python3
Python 3.8.6 (default, Jan 27 2021, 15:42:20) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvips
>>> pyvips.cache_set_trace(True)
>>> a = pyvips.Image.new_from_file("wtc.jpg")
vips cache+: jpegload filename="wtc.jpg" out=((VipsImage*) 0x1007000) flags=((VipsForeignFlags) VIPS_FOREIGN_SEQUENTIAL) -
```

That's the jpegload operation going into the cache (the '+' character). The image hasn't been decoded yet, that only happens when you demand pixels from it:

```
>>> a.avg()
vips cache : copy in=((VipsImage*) 0x1007000) out=((VipsImage*) 0x1007190) -
vips cache+: linecache in=((VipsImage*) 0x10077d0) out=((VipsImage*) 0x1007af0) tile-height=8 access=((VipsAccess) VIPS_ACCESS_SEQUENTIAL) persistent=TRUE -
vips cache+: sequential in=((VipsImage*) 0x10077d0) out=((VipsImage*) 0x1007960) tile-height=8 -
vips cache+: extract_area input=((VipsImage*) 0x1007960) out=((VipsImage*) 0x1007c80) left=0 top=0 width=9372 height=9372 -
vips cache+: avg in=((VipsImage*) 0x1007000) out=117.853995 -
117.85399474082952
```

Now the limage is copied to a temporary file and the `avg` operation is executed. Everything is kept in cache (the '+' signs again).

Now delete the image and try again:

```
>>> del a
>>> a = pyvips.Image.new_from_file("wtc.jpg")
vips cache*: jpegload filename="wtc.jpg" -
>>> a.avg()
vips cache*: avg in=((VipsImage*) 0x1007000) -
117.85399474082952
>>> 
```

It's not computing anything, just fetching from cache (the '*' characters).

The cache gives you things like common-subexpression elimination. pyvips will evaluate expressions like:

```
y = (x - 2) * (x - 2)
```

As one subtract and one multiply.

**Comment by peterroelants** [comment]
Thank you for illustrating the pyvips cache.

This cache is a temporary file that is saved somewhere else right? How long would it be kept for?

I guess the pyvips cache would not necessarily keep a reference to the original image?
My original problem was that a reference to the original image was being kept in the filesystem. The filesystem thought that the image was still opened through its inode reference, so it decided to keep the file inode upon deletion. Deleting the pyvips Image object and running a garbage collection step removed this reference to the original file, and seemed to solve the issue of the file reference being kept. I'm not sure if it would have been the cache in this case keeping the reference.

**Comment by jcupitt** [comment]
The cache is just a big hashtable in memory. By default it's sized to 100MB, 100 operations, or 100 open files, whichever is smaller.

I don't think the del / gc would have knocked the load out of cache, that's puzzling.

Anyway, use `access="sequential"`, it won't be cached and it'll run faster.

**Comment by peterroelants** [comment]
I just tested this and either setting `pyvips.cache_set_max(0)` or using `access="sequential"` prevented my issue. Thanks :+1:

**Comment by jcupitt** [comment]
I tried a tiny benchmark:

```python3
#!/usr/bin/python3
  
import sys
import time
import pyvips

start = time.time()

im = pyvips.Image.new_from_file(sys.argv[1])
im.write_to_file(sys.argv[2])

print(f"took {(time.time() - start) * 1000:.2f}ms")

start = time.time()

im = pyvips.Image.new_from_file(sys.argv[1], access="sequential")
im.write_to_file(sys.argv[2])

print(f"took {(time.time() - start) * 1000:.2f}ms")
```

I see:

```
 $ ./bench.py ~/pics/wtc.png x.tif[tile,pyramid,compression=jpeg]
took 4120.20ms
took 3574.24ms
```

So you could expect perhaps a 15% speedup with sequential access, though it depends on your image size.
