### ISSUE TITLE
Error with new_from_file, fail=True and PNG

### ISSUE THREAD

**Issue by mzur** [libvips/pyvips#257]
Thanks for your great work here, @jcupitt! vips has been a reliable core component of one of my projects for the last few years.

I believe I found an error with PNG files and [`fail=True`](https://github.com/libvips/pyvips/blob/caceec98fa7f63ae6bc7bcb991c2ec946b16554a/pyvips/vimage.py#L208-L210). If I run this script with pyvips 2.1.14:

```python
from pyvips import Image
Image.new_from_file('test.png', fail=True)
```
I get:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/pyvips/vimage.py", line 232, in new_from_file
    string_options=options, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pyvips/voperation.py", line 275, in call
    details = intro.details[name]
KeyError: 'fail'
```
It works with:
```python
Image.new_from_file('test.jpg', fail=True)
```
Images are attached. I haven't checked other file formats.

- [test.jpg](https://user-images.githubusercontent.com/2457311/121143414-52a46d80-c83d-11eb-99e9-73d9cb61277e.jpg)
- [test.png](https://user-images.githubusercontent.com/2457311/121143417-533d0400-c83d-11eb-92ee-709de4ccbf6b.png)

**Comment by jcupitt** [comment]
Hi @mzur, thank you for your kind words.

I think you probably have a rather old libvips, perhaps 8.4.x? We moved the `fail` parameter into the base class in 2016, so all loaders support it now.

**Comment by jcupitt** [comment]
I should have explained: pyvips doesn't really have an API -- it uses introspection to expose the API of the underlying libvips binary. Missing features are almost always because the libvips binary it is linking to is missing the feature.

**Comment by mzur** [comment]
> I think you probably have a rather old libvips, perhaps 8.4.x?

Thanks for the hint! Indeed I use version 8.4.5 which is provided by Ubuntu 20.04. Which newer version should fix this error?

**Comment by jcupitt** [comment]
`fail` was moved to the base class in 8.5, so anything more modern, really. 8.11 is due out in a week, fwiw.

**Comment by mzur** [comment]
Thanks! :+1:
