### ISSUE TITLE
Unable to write to memory when multiprocessing

### ISSUE THREAD

**Issue by Tasaddar12** [libvips/pyvips#258]
I get an error of not able to write to memory. I am trying to select individual pixels from a list of images and I have it multiprocessed to be faster. 
```python
def GetMultiData(self, img):
        #start = time.perf_counter()
        image = pyvips.Image.new_from_file(img, access="sequential")
        data = {count : np.frombuffer((image.crop(int(i[0]), (image.height - int(i[1])), 1, 1)).write_to_memory(), dtype=np.uint8).reshape(1,1,image.bands)[0][0].tolist() for count,i in enumerate(self.point) }
        #print(time.perf_counter() - start)
        return ( os.path.splitext(os.path.basename(img))[0], data )
```
The img is our image path for the process. self.point is a list of lists for our points. [[x,y], [x2,y2]...]
Here is where we start our processes:
```python
with Pool(multiprocessing.cpu_count()) as p:
                self.response = p.map(self.GetMultiData, images)
            self.response = {items[0] : items[1] for items in self.response}
```
Then my exact error is:
```
File "/var/www/app/app/lib/dataOverTime.py", line 41, in <dictcomp>
web_1  |     data = {count : np.frombuffer((image.crop(int(i[0]), (image.height - int(i[1])), 1, 1)).write_to_memory(), dtype=np.uint8).reshape(1,1,image.bands)[0][0].tolist() for count,i in enumerate(self.point) }
web_1  |   File "/usr/local/lib/python3.8/site-packages/pyvips/vimage.py", line 621, in write_to_memory
web_1  |     raise Error('unable to write to memory')
web_1  | pyvips.error.Error: unable to write to memory
web_1  |   VipsJpeg: out of order read at line 1040
```

**Comment by jcupitt** [comment]
Hi @Tasaddar12,

The message means more than one process is reading from the source image, but I can't really see what that might be happening from the sample you've given. I think you'll need to make a complete program I can run.

**Comment by Tasaddar12** [comment]
My program is running on flask its a web app. I have found a solution around this issue. 
```python
start = time.perf_counter()
        image = pyvips.Image.new_from_file(img, access="sequential")
        
        images = [image.crop(int(x[0]), image.height - int(x[1]), 1, 1) for x in self.point]
        full = images[0]
        images.pop(0)
        for im in images:
            full = full.join(im, 'horizontal')

        mem_buf = full.write_to_memory()

        dump = np.frombuffer(mem_buf, dtype=np.uint8).reshape(full.width,full.height,full.bands)
        data = {i : dump[i][0].tolist() for i in range(len(dump))}
        print(time.perf_counter() - start)
        return ( os.path.splitext(os.path.basename(img))[0], data )
```
The solution actually seems to run faster than when I grab a single pixel. this ran about 4 ms per img while getting single pixel took about 8 ms per image.

**Comment by Tasaddar12** [comment]
Here is an example piece I put together to show the error.
Images are in what ever folder dir you make. 
pixels can be any you want just more than 1 set
```python
import pyvips
from multiprocessing import Pool
import multiprocessing
import os
import numpy as np

def absoluteFiles(directory):
    for dirpath,_,filenames in os.walk(directory):
        for f in filenames:
            yield os.path.abspath(os.path.join(dirpath, f))

point = ["100x100", "100x300", "323x356"] # Set points to grab
point = [i.split('x') for i in point]
images = [img for img in absoluteFiles('images')] # set dir where images are

def GetMultiData(img):
    image = pyvips.Image.new_from_file(img, access="sequential")
    data = {count : np.frombuffer((image.crop(int(i[0]), (image.height - int(i[1])), 1, 1)).write_to_memory(), dtype=np.uint8).reshape(1,1,image.bands)[0][0].tolist() for count,i in enumerate(point) }
    return ( os.path.splitext(os.path.basename(img))[0], data ) # return tuple

with Pool(multiprocessing.cpu_count()) as p:
    response = p.map(GetMultiData, images)
response = {items[0] : items[1] for items in response} # remap return as dict probable could have been done with dict()
print(response)
```

**Comment by jcupitt** [comment]
Thanks! I'll have a look.

**Comment by jcupitt** [comment]
Your program works for me with 100 JPGs and 32 threads. 

I can see it would fail for some sets of coordinates -- `access="sequential"` means you will only read from the image strictly top-to-bottom, so it you fetch (300, 300) before (100, 100), you'll get an out of order error. If you want to read random pixels from an image, I would remove the `access=`.

`crop` then `write_to_memory` is quite a slow way to read pixels. You can just do:

```
$ python3
Python 3.9.5 (default, May 11 2021, 08:20:37) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvips
>>> x = pyvips.Image.new_from_file("/home/john/pics/k2.jpg")
>>> x(10, 10)
[10.0, 0.0, 1.0]
>>> 
```

To read pixel (10, 10). This is an overload that calls `getpoint` for you.

`getpoint` is slow because each time you call it, it'll build and execute an entire image pipeline just to render a single pixel. It's much faster to create a region on an image and then fetch pixels with that -- the pipeline will be built once and then reused.

For example:

```python
#!/usr/bin/python3

import random
import time
import sys
import pyvips

image = pyvips.Image.new_from_file(sys.argv[1])
n_points = 10000

start = time.time()
for _ in range(n_points):
    x = random.randint(0, image.width - 1)
    y = random.randint(0, image.height - 1)
    p = image(x, y)
end = time.time()
print(f"read {n_points} points in {end - start:.2f}s")

start = time.time()
region = pyvips.Region.new(image)
for _ in range(n_points):
    x = random.randint(0, image.width - 1)
    y = random.randint(0, image.height - 1)
    p = region.fetch(x, y, 1, 1)
end = time.time()
print(f"read {n_points} points in {end - start:.2f}s")
```

I see:

```
$ ./fetch-vs-crop.py ~/pics/k2.jpg
read 10000 points in 5.07s
read 10000 points in 0.21s
```

**Comment by Tasaddar12** [comment]
thank you much! I was noticing lots of slowdown with Pillow when I increased my image count so I found this lib and did some quick testing for image load time and was impressed.

**Comment by Tasaddar12** [comment]
I tried to use your solution and I got this error:
```

**Comment by Tasaddar12** [comment]
Here are my results:
PNG
```
Load full image pyvips into mem and load to numpy buffer
0.1355203608982265
Open full image with pyvips and load into numpy ndarray
0.23005165299400687
Open full image with pyvips then crop out the pixel and load that into numpy buffer
0.029002952156588435
Open image with pyvips then use region to get data
0.552292738109827
Open full image with Pillow and load the image
0.15430997707881033
```
JPG
```
Load full image pyvips into mem and load to numpy buffer
0.05013861716724932
Open full image with pyvips and load into numpy ndarray
0.04580715112388134
Open full image with pyvips then crop out the pixel and load that into numpy buffer
0.0041737789288163185
Open image with pyvips then use region to get data
0.047253078781068325
Open full image with Pillow and load the image
0.06947784498333931
```
I updated the libvips and such so that is working now. I also ran another time test and I was getting slower results after updating the libvips version to latest.
here is my python code to generate the above using libvips version 8.12.0
using pyvips version 2.1.14
```python
from PIL import Image
import numpy as np
import time
import pyvips

print("Load full image pyvips into mem and load to numpy buffer")
start = time.perf_counter()
image = pyvips.Image.new_from_file('1963.jpg', access="sequential")
imgnp = np.frombuffer(image.write_to_memory(), dtype=np.uint8).reshape(image.height, image.width, image.bands)
print(time.perf_counter() - start)

print("Open full image with pyvips and load into numpy ndarray")
start = time.perf_counter()
image = pyvips.Image.new_from_file('1963.jpg', access="sequential")
imgnp = np.ndarray(buffer=image.write_to_memory(), dtype=np.uint8, shape=[image.height, image.width, image.bands])
print(time.perf_counter() - start)

print("Open full image with pyvips then crop out the pixel and load that into numpy buffer")
start = time.perf_counter()
image = pyvips.Image.new_from_file('1963.jpg', access="sequential")
image = image.crop(100,100,1,1)
imgnp = np.frombuffer(image.write_to_memory(), dtype=np.uint8).reshape(1,1,image.bands)
print(time.perf_counter() - start)

print("Open image with pyvips then use region to get data")
start = time.perf_counter()
image = pyvips.Image.new_from_file('1963.jpg')
region = pyvips.Region.new(image)
p = region.fetch(100, 100, 1, 1)
print(time.perf_counter() - start)

print("Open full image with Pillow and load the image")
start = time.perf_counter()
im = Image.open('1963.jpg')
px = im.load()
print(time.perf_counter() - start)
```
I used image magic to convert the image between jpg and png. 
I imagine with a large amount of pixels to choose from yes it will be longer but when I only need maybe a maximum of 10 at any given moment 

(docker using 8.11.0)
in docker was averaging ~6ms jpg ~15ms png with regions on multiple pixels 
~8ms jpg ~15ms png with crop multiple pixels. 
(using 8.4)
Prior to updating I was averaging ~7ms png ~4ms jpg with crop on multiple points.

I think I am gonna rebuild my docker image to use the old version if you want my docker file feel free to ask.

**Comment by jcupitt** [comment]
Phew, I was worried, it shouldn't have become slower. 

Yes, if you're only reading a few points then crop vs fetch probably doesn't matter.

**Comment by Rasaa84** [comment]
Hi @jcupitt 

I am getting the same error while employing multiprocessing. Here is my code: 

`
image = pyvips.Image.new_from_file(/path/to/image/image.svs)
if image.hasalpha():
    image = image[0:3]
patch_size = 512
patch = image.crop(10000,10000, patch_size, patch_size)
patch = np.frombuffer(patch.write_to_memory(), dtype=np.uint8).reshape(patch_size,patch_size,patch.bands)`

and this is the error:

`patch = np.frombuffer(patch.write_to_memory(), dtype=np.uint8).reshape(patch_size,patch_size,patch.bands)
  File "/home/.pyenv/versions/3.9.10/lib/python3.9/site-packages/pyvips/vimage.py", line 944, in write_to_memory
    raise Error('unable to write to memory')
pyvips.error.Error: unable to write to memory`

Is there any solution for this? Your help is much appreciated.

**Comment by jcupitt** [comment]
Your code should be:

```python
# load as RGB
image = pyvips.Image.new_from_file("/path/to/image/image.svs", rgb=True)
patch = image.crop(10000, 10000, 512, 512)
numpy_array = patch.numpy()
```

But you need to post a complete, runnable example.

**Comment by Rasaa84** [comment]
Thanks for your response. I had tried this before but got the same error. My code is running on flask its a web app. It runs without error locally but am getting error on server.

**Comment by jcupitt** [comment]
Sorry, if I can't reproduce the error, I can't help.
