### ISSUE TITLE
quickest way to convert pdf to image

### ISSUE THREAD

**Issue by kbrajwani** [libvips/pyvips#261]
There is any way to convert pdf all pages into images with speed and less memory.
```
%%time
import pyvips
import numpy as np

# map vips formats to np dtypes
format_to_dtype = {
    'uchar': np.uint8,
    'char': np.int8,
    'ushort': np.uint16,
    'short': np.int16,
    'uint': np.uint32,
    'int': np.int32,
    'float': np.float32,
    'double': np.float64,
    'complex': np.complex64,
    'dpcomplex': np.complex128,
}

imgs = []
i = 0
while True:
    try:
        x = pyvips.Image.new_from_file(filename, dpi=300, page=i)
        img = np.ndarray(buffer=x.write_to_memory(),
                      dtype=format_to_dtype[x.format],
                      shape=[x.height, x.width, x.bands])
        imgs.append(img)
    except:
        break
    i += 1
```

Currently i am using this code.

**Comment by jcupitt** [comment]
That's probably the best you can do for speed. You could try building libvips against PDFium rather than poppler, that might help, depending on the PDF.

You could use a list comprehension to make your code a little neater, of course:

```python
def vips_to_numpy(vips_image):
    ...
    return np_array

pdf = pyvips.Image.new_from_file(filename)
n_pages = pdf.get("n-pages")
imgs = [vips_to_numpy(pyvips.Image.new_from_file(filename, dpi=300, page=i)) for i in range(n_pages)]
```

**Comment by kbrajwani** [comment]
Can you guide me how can i install pdfium. i read the readme but not know where to untar the pdfium-linux.tgz. 
Should i install libvips like this.
```
!sudo apt-get update
!sudo apt-get install  -y libvips libvips-dev 
```
and untar the pdfium in /usr/include/vips folder.

**Comment by jcupitt** [comment]
There are some notes in the source:

https://github.com/libvips/libvips/blob/master/libvips/foreign/pdfiumload.c#L50

You need to untar the pdfium binary to your install prefix, then reconfigure and rebuild libvips.

**Comment by kbrajwani** [comment]
i have tried to install but it not able to basic command line copy command.
can you please tell me where i am wrong?

```
!apt-get update && apt-get install -y \
	build-essential \
	autoconf \
	automake \
	libtool \
	nasm \
	unzip \
	wget \
	git \
	pkg-config \
	unzip \
	gtk-doc-tools 

!apt-get update \
	&& apt-get install -y 

%%bash
PREFIX=/usr/local/vips

PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig \
	LD_LIBRARY_PATH=$PREFIX/lib \
	PATH=$PATH:$PREFIX/bin \
	WORKDIR=/content/

PDFIUM_VERSION=4290 

PDFIUM_URL=https://github.com/bblanchon/pdfium-binaries/releases/download/chromium

mkdir pdfium-$PDFIUM_VERSION \
	&& cd pdfium-$PDFIUM_VERSION \
	&& wget $PDFIUM_URL/$PDFIUM_VERSION/pdfium-linux.tgz

mkdir -p $PREFIX/lib/pkgconfig \
	&& cd $PREFIX \
	&& tar xf $WORKDIR/pdfium-$PDFIUM_VERSION/pdfium-linux.tgz \
	&& echo "prefix=$PREFIX" >> lib/pkgconfig/pdfium.pc \
	&& echo "exec_prefix=\${prefix}" >> lib/pkgconfig/pdfium.pc \
	&& echo "libdir=\${exec_prefix}/lib" >> lib/pkgconfig/pdfium.pc \
	&& echo "includedir=\${prefix}/include" >> lib/pkgconfig/pdfium.pc \
	&& echo "Name: pdfium" >> lib/pkgconfig/pdfium.pc \
	&& echo "Description: pdfium" >> lib/pkgconfig/pdfium.pc \
	&& echo "Version: $PDFIUM_VERSION" >> lib/pkgconfig/pdfium.pc \
	&& echo "Requires: " >> lib/pkgconfig/pdfium.pc \
	&& echo "Libs: -L\${libdir} -lpdfium" >> lib/pkgconfig/pdfium.pc \
	&& echo "Cflags: -I\${includedir}" >> lib/pkgconfig/pdfium.pc

%%bash
apt-get install -y \
	libicu-dev \
	libc++-dev \
	libc++abi-dev \
	glib-2.0-dev \
	libexpat-dev \
	librsvg2-dev \
	libpng-dev \
	libgif-dev \
	libjpeg-dev \
	libexif-dev \
	liblcms2-dev \
	libheif-dev \
	liborc-dev 

!apt-get install gtk-doc-tools
!apt-get install libgtk-3-dev
!apt-get install libmutter-dev
!apt-get install libwnck-3-dev
!apt-get install libgnome-menu-3-dev
!apt-get install libupower-glib-dev
!apt-get install gobject-introspection

%%bash
PREFIX=/usr/local/vips

VIPS_VERSION=master
VIPS_URL=https://github.com/libvips/libvips.git

git clone $VIPS_URL \
	&& cd libvips \
	&& git checkout $VIPS_VERSION \
	&& ./autogen.sh --prefix $PREFIX \
	&& make V=0 \
	&& make install

vips -l pdfload_base
```

This is my installation steps as per the docker file for ubuntu 20.04 given.
[libvips logs.txt](https://github.com/libvips/pyvips/files/6831972/libvips.logs.txt)

**Comment by jcupitt** [comment]
Sorry, I don't know what system you are using. What does `%%bash` mean? Is this a buildpack?

You don't say what the output of libvips configure was, but if it can't find pdfium, it's probably because you've not set `PKG_CONFIG_PATH`.

**Comment by kbrajwani** [comment]
%%bash is for bash script. I am using https://colab.research.google.com/ with ubuntu os. If current version is taking 16 second if it will load pdfium how much time it can reduce the document have 69 pages.

**Comment by jcupitt** [comment]
If you paste a link to a demo colab workspace, I'll have a look.

PDFium might be faster, or it might be slower. It depends on the PDF.

**Comment by kbrajwani** [comment]
Here is the link of colab workspace https://colab.research.google.com/drive/1TNkVe-xneAaKWb5DVZKzVbU4WK_KmMc3?usp=sharing

**Comment by jcupitt** [comment]
Yes, it's not detecting PDFium, if you look at the output of `configure`. I think you just need to export `PKG_CONFIG_PATH`, ie.:

```
export PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig \
	LD_LIBRARY_PATH=$PREFIX/lib \
	PATH=$PATH:$PREFIX/bin \
	WORKDIR=/content/
```

**Comment by kbrajwani** [comment]
Thanks it's been solved. Just i was missing export.

**Comment by kbrajwani** [comment]
But still it's not the fastest i am using pymupdf currently which takes 3.5 seconds and 2.8 gb ram for convert the pdf with 69 page in 300 dpi. The libvips also takes same ram but it takes 7 seconds.

**Comment by jcupitt** [comment]
MuPDF has a very difficult licence: it's AGPL. If you convert PDFs with it, your whole application becomes open source, even if you don't try to distribute the source.

You can get a commercial licence for MuPDF, but it's expensive. You can't use it for free in closed-source products.

The terrible licence is why google have invested in PDFium. They bought the foxit PDF renderer, made a library out of it, and used the Apache licence so it's free for everyone. It's the PDF renderer in Chrome.

**Comment by jcupitt** [comment]
See https://mupdf.com/license.html

**Comment by kbrajwani** [comment]
in pyvips there is any options like pymupdf https://github.com/pymupdf/PyMuPDF/issues/322#issuecomment-512561756 where we direct use of vips image object to  create a pillow image?

**Comment by jcupitt** [comment]
Sure, see: https://libvips.github.io/pyvips/intro.html#numpy-and-pil

**Comment by kbrajwani** [comment]
I am using that example but i am asking for something like Image.frombytes(mode, [pix.width, pix.height], pix.samples) . currently we have to write file into memory then we are converting numpy array.

**Comment by jcupitt** [comment]
That code is passing the array directly from libvips to PIL. It's not encoding and decoding, there's no copy operation, and no conversion.
