### ISSUE TITLE
How to overlay two or more huge .png files one over another with pyvips?

### ISSUE THREAD

**Issue by CopotronicRifat** [libvips/pyvips#263]
As windows cannot read more than 2000 files at once, I have created 3 different huge png files. I need to join these 3 images into one image. Is it possible to create an image, overlaying 3 images without any image loss due to transparency?

**Comment by jcupitt** [comment]
Hi @CopotronicRifat, sure it should be simple. 

Post a couple of (small!) sample images showing exactly how you want to join them. I suppose you want a vertical join, is that right?

**Comment by CopotronicRifat** [comment]
Thanks, @jcupitt for the response.

Suppose I have 2 transparent images. DEMO1.png and DEMO2.png, both images have a resolution of 600 * 600. 


![DEMO1](https://user-images.githubusercontent.com/9729244/126895657-f7d42b8f-b7ac-4ad9-994f-a4aac2be65d3.png)
![DEMO2](https://user-images.githubusercontent.com/9729244/126895683-39a25700-0f7d-4692-adb1-6ebc84025bf1.png)


I want to overlay these two images one over another without losing any sub-images in these images, e.g. the output image will contain all three sub-images (2 sub-images from DEMO1.png and 1 sub-image from DEMO2.png) and the output image resolution will be 600 * 600 as well.

Does that make sense?

**Comment by jcupitt** [comment]
Ah I see. Try:

```python
d1 = pyvips.Image.new_from_file("demo1.png", access="sequential")
d2 = pyvips.Image.new_from_file("demo2.png", access="sequential")
result = d1.composite(d2, "over")
result.write_to_file("out.png")
```

Though this will be pretty slow. How did you make these huge PNGs? It might be better to build them without overlaps, if possible.

**Comment by CopotronicRifat** [comment]
Yeah, I am thinking of another way. Divide the huge image into 9 parts and then join them across 3 in a row. That should be better than this overlaying approach.

@jcupitt Thanks, anyway.

**Comment by jcupitt** [comment]
Yes, a 3x3 grid would be quite a bit quicker.

I often use a set of strips -- so each strip is as wide as the final output, but only a few thousand pixels high. At the end, you can join them all vertically in a single operation.
