### ISSUE TITLE
Metadata writing when saving tiffs

### ISSUE THREAD

**Issue by TheHuessy** [libvips/pyvips#265]
I've been working on generating pyramidal tiffs, adding metada, and saving the resulting image object as a tiff file. When I add the metadata via `set_teype()` and then use `get_fields()` to display/QC that the metadata has been written, it shows my newly added fields and if I run the following code I get what look like expected results:

```
for i in test_im.get_fields():
    print("{}: {}".format(i, test_im.get(i)))
```

```
width: 13440
height: 14336
bands: 3
format: uchar
coding: none
interpretation: srgb
xoffset: 0
yoffset: 0
xres: 1.0
yres: 1.0
filename: temp-0
testmeta_int: 42
testmeta_str: wow, what a life!
testmeta_bool: True
testmeta_float: 3.14
```

With the `testmeta_...` variables being my added metadata.

When I go to save the file and then reload it, I notice that most of my added fields (all but the boolean, but I'm not as worried about that) have been saved to the metadata variable `image-description` as an XML string:

```image-description: <?xml version="1.0"?>
<image xmlns="http://www.vips.ecs.soton.ac.uk//dzsave" date="2021-07-27T20:55:21.269176Z" version="8.11.1">
  <properties>
    <property>
      <name>width</name>
      <value type="gint">13440</value>
    </property>
    <property>
      <name>height</name>
      <value type="gint">14336</value>
    </property>
    <property>
      <name>bands</name>
      <value type="gint">3</value>
    </property>
    <property>
      <name>xoffset</name>
      <value type="gint">0</value>
    </property>
    <property>
      <name>yoffset</name>
      <value type="gint">0</value>
    </property>
    <property>
      <name>xres</name>
      <value type="gdouble">1</value>
    </property>
    <property>
      <name>yres</name>
      <value type="gdouble">1</value>
    </property>
    <property>
      <name>testmeta_int</name>
      <value type="gint">42</value>
    </property>
    <property>
      <name>testmeta_str</name>
      <value type="VipsRefString">wow, what a life!</value>
    </property>
    <property>
      <name>testmeta_float</name>
      <value type="gdouble">3.1400000000000001</value>
    </property>
  </properties>
</image>
```

My question is whether or not there is a way to save my custom metadata such that it can be loaded simply as a key value pair like `width` or is it just a limitation of tiff files that one can only save certain key value pairs and the rest has to be stored as xml in the catch-all `image-description` field?

Sorry if this is a super obvious question, I'm new to tiffs and vips in general.

**Comment by jcupitt** [comment]
Hi @TheHuessy,

That's right -- libvips supports arbitrary metadata on images, but TIFF only allows a few fixed tags, unless you get very deep into writing extensions to the libtiff loader.

To get around this limitation, the tiffsave operation in libvips adds a set of key-value pairs to the `IMAGE_DESCRPTION` tag instead, using XML as the container. PhotoShop does more or less the same.

If you want your own metadata format (perhaps for compat with other libraries), you can create it as a string and set the libvips `image-description` field.

**Comment by jcupitt** [comment]
Oh wait, do you want libvips to spot `IMAGEDESCRIPTION` metadata that it wrote and automatically parse it back into the image? Yes, I guess it could do that, though I don't know how useful it'd be outside of libvips itself.

**Comment by TheHuessy** [comment]
First of all, thanks for the first explanation! I kind of figured that's what was going on, but it's good to hear confirmation

> Oh wait, do you want libvips to spot `IMAGEDESCRIPTION` metadata that it wrote and automatically parse it back into the image? Yes, I guess it could do that, though I don't know how useful it'd be outside of libvips itself.

I mean, if you're bored, yes that addition would be great. However, I can see why it may not be a wonderful idea because users might have false expectations of how the metadata is actually stored in the file itself if they don't see the `IMAGEDESCRIPTION` filed when they load the file but then look for the raw metadata outside of pyvips.
