### ISSUE TITLE
`vips_autorot_remove_angle` equivalent for pyvips

### ISSUE THREAD

**Issue by ent1c3d** [libvips/pyvips#267]
Hello, 

Basic flow of my program, seems following:  decoding image, doing some manipulation over image and then encoding it back with original exif.

I am using method `autorot` with images with orientation and it really works fine, when I am calling `image.get_fields()` after `autorot`, I see that there are no more `exif-ifd0-Orientation` and `orientation` fields. 

But, when I am encoding image and passing exif data(which I from original image) back, orieentation works wrongly. 

Then  I found the method `vips_autorot_remove_angle` in which description I read that it can  `Remove the orientation tag on image . Also remove any exif orientation tags.`

That's exactly what I need. Do we have in `pyvips` such kind of method, which removes orientation tags from exif?

**Comment by jcupitt** [comment]
Hi @ent1c3d,

You shouldn't need to reattach the original exif data -- libvips ought to copy that through for you.

For example:

```
$ python3
Python 3.9.5 (default, May 11 2021, 08:20:37) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvips
>>> x = pyvips.Image.new_from_file("Gugg_coloured.jpg")
>>> x.get("orientation")
6
>>> x.get("exif-ifd2-SensingMethod")
'2 (One-chip color area sensor, Short, 1 components, 2 bytes)'
```

So this is orientation 6 and has some typical camera exif. If I now do:

```
>>> x = x.autorot()
>>> x.write_to_file("x.jpg")
>>> y = pyvips.Image.new_from_file("x.jpg")
>>> y.get("orientation")
1
>>> y.get("exif-ifd2-SensingMethod")
'2 (One-chip color area sensor, Short, 1 components, 2 bytes)'
>>> 
```

Autorot has flipped the image upright, but no other exif data is changed.

**Comment by ent1c3d** [comment]
Thanks @jcupitt for your  rapid answer! 

Actually, the  problem is not  with attaching  exif, the problem is that I want to remove `orientation` tag from image, as well as from exif data, as it does `vips_autorot_remove_angle`[Remove the orientation tag on image . Also remove any exif orientation tags.]. 


Process is the following, I strip exif from image, doing  some manipulations, then adding exif back.  During the manipulation I am calling `autorot`, which successfully removes `orientation` tag and if i don't attach back `exif-data`,  orientation looks correct, but  if I attach back `exif-data`, then orientation becomes incorrect, that's why I want to remove `orientation` info from `exif-data` as well.

**Comment by jcupitt** [comment]
But why are you removing and reattaching the exif? If you leave it there, libvips can update the orientation for you.

**Comment by ent1c3d** [comment]
Understanding  your question, but I don't need to have exif data in the image processing pipeline.  

I just want to remove orientation from image as well as from exif-data.  
From image  I am able to do it  with `autorot`. From exif-data I see `vips_autorot_remove_angle` can do it, but do we have any equivalent function in pyvips? or any way out to modify exif-data?

**Comment by jcupitt** [comment]
libvips optimises metadata in the pipeline -- it's all done with copy-on-write and reference counting, so there's almost no runtime cost to having even a very large amount of it. I would not remove the exif.

**Comment by ent1c3d** [comment]
Thanks again @jcupitt, 

I just tried to get `exif` before `autorot` and after `autorot` and getting identical exif binary output:
```
print(image.exif)

image, angle_flip = image.autorot(angle=True, flip=True)

print(image.exif)
```

So, `autorot` really removes `exif-ifd0-Orientation` and `orientation` fields from image, but don't touches `exif-data`.  
Is there  any way to modify `exif-data`?

**Comment by jcupitt** [comment]
The exif data is rebuilt on save.

libvips exif editing works like this (from memory):

1. On load, the exif data is copied out of libjpeg and attached as a binary blob called `exif-data`.
2. libvips uses libexif to parse the exif data and build a set of extra metadata tags like `exif-ifd2-SensingMethod`.
3. Some tags, like orientation, which are supported by other image formats, are also copied to separate tags like `orientation`.
4. During processing, metadata is propagated with a simple pointer copy.
5. You can add / remove / update tags like `exif-ifd2-SensingMethod` and `orientation` with `image.add` and `image.remove`.
6. On save, libvips parses the `exif-data` blob with libexif, then does a merge with the image tags, applying the cumulative effect of any modifications the user made, then reserialises to make a new `exif-data`. 
6a. Changes to `orientation` override changes to `exif-ifd0-Orienation`. xres and yres also work like this.
7. And that new `exif-data` is saved to the output file.

This means you can freely add and alter exif metadata during processing, and changes are fast and all propagate as you'd expect. `autorot` relies on this behaviour.

**Comment by ent1c3d** [comment]
Thank you so much @jcupuitt for your detailed answer!  Really appreciate it!
