### ISSUE TITLE
avif could not be saved in memory!

### ISSUE THREAD

**Issue by kamyar1979** [libvips/pyvips#273]
Using libheif and libx265-dev I can save avif format. When using write_to_file anything is OK, but whne trying to use write_to_buffer or even Custom Target using memory (BytesIO), the file gets corrupted!

**Comment by jcupitt** [comment]
Hi @kamyar1979,

I tried this test program:

```python
#!/usr/bin/python3

import os
import sys
import pyvips

buf = open(sys.argv[1], "rb").read()

im = pyvips.Image.thumbnail_buffer(buf, 128)
ext = os.path.splitext(sys.argv[2])[1]
buf_out = im.write_to_buffer(ext)

open(sys.argv[2], "wb").write(buf_out)
```

And it works for me. If I run:

```

**Comment by jcupitt** [comment]
I'm running libvips 8.11 and libheif 1.11.0 on Ubuntu 21.04.

**Comment by kamyar1979** [comment]
I found the problem: When saving into buffer or memory (Anything other than write_to_file) we have to use ".avif[compression=av1]" as format, whiile when using write_ti_file, using .avif extension is enough!
Your code works since it is jusy a thumbnail. But see my code:

```
import pyvips
from io import BytesIO

image = pyvips.Image.new_from_file('../Downloads/IMG_0548.HEIC', access='sequential')

image.write_to_file('dongle3.avif')


#out = image.write_to_buffer('.avif')



f = open('dongle2.avif', 'wb')

def write_handler(chunk):
    f.write(chunk)

buffer = pyvips.TargetCustom()
buffer.on_write(write_handler)

image.write_to_target(buffer, '.avif[compression=av1]')

f.close()

```

In the above code, dongle3.avif  is right, but if I omit "[compression=av1]", the output would be a heif file with avif extension!

**Comment by jcupitt** [comment]
Ah I remember now, you're right, this has come up before. 

FWIW you don't have to put the option in the format string, you can also write:

```python
image.write_to_target(buffer, '.avif', compression='av1')
```

**Comment by jcupitt** [comment]
I made an enhancement discussion for this: https://github.com/libvips/libvips/discussions/2399
