### ISSUE TITLE
tile 1 bit tiff files

### ISSUE THREAD

**Issue by MAJAQA** [libvips/pyvips#288]
Trying desperately to tile 1 bit tiff images: dzsave only makes jpeg; tiffsave does not tile...

**Comment by jcupitt** [comment]
Hi @MAJAQA,

Use the `--suffix` option to set the file format. For example:

```
vips dzsave mono.jpg x --suffix .tif[bitdepth=1,compression=ccittfax4] --depth one
```

**Comment by MAJAQA** [comment]
I was pretty close ;-) indeed using the suffix got it working. thanks! Using it in pyvips:
MakeTiles = a.dzsave(tmp, suffix='.tif[bitdepth=1,compression=ccittfax4]', tile_size=64, overlap=0, depth='one')
![image](https://user-images.githubusercontent.com/88855628/143539137-8f8a94d7-0733-4630-9592-c3f7884ffe48.png)
