### ISSUE TITLE
Error occurred when doing works on the NumPy array

### ISSUE THREAD

**Issue by SikangSHU** [libvips/pyvips#290]
Dear professor:
    I consider to do some works on the patches which are 512*512, so I make a NumPy array from a vips image for each patch. I am sure that the step which makes a NumPy array from a vips image is correct, but I don't know why an error occurred after I do works on the NumPy array. Can you help me with the code I marked with '@@@@@' that may lead to the mistake. Thank you very much!

`import pyvips
import numpy as np
from numpy import linalg
from skimage.color.colorconv import _prepare_colorarray

img = pyvips.Image.new_from_file('E:\\test4.png', access='sequential')
patch_size = 512
n_across = img.width // patch_size
n_down = img.height // patch_size
x_max = n_across - 1
y_max = n_down - 1

format_to_dtype = {
    'uchar': np.uint8,
    'char': np.int8,
    'ushort': np.uint16,
    'short': np.int16,
    'uint': np.uint32,
    'int': np.int32,
    'float': np.float32,
    'double': np.float64,
    'complex': np.complex64,
    'dpcomplex': np.complex128,
}
dtype_to_format = {
    'uint8': 'uchar',
    'int8': 'char',
    'uint16': 'ushort',
    'int16': 'short',
    'uint32': 'uint',
    'int32': 'int',
    'float32': 'float',
    'float64': 'double',
    'complex64': 'complex',
    'complex128': 'dpcomplex',
}
for y in range(0, n_down):
    print("row {} ...".format(y))
    for x in range(0, n_across):
        patch = img.crop(x * patch_size, y * patch_size,
                         patch_size, patch_size)

        vi_np = np.ndarray(buffer=patch.write_to_memory(),
                           dtype=format_to_dtype[patch.format],
                           shape=[patch.height, patch.width, patch.bands])

        img1 = _prepare_colorarray(vi_np, force_copy=True)          @@@@@
        np.maximum(img1, 1E-6, out=img1)
        X = np.array([[0.468, 0.721, 0.511], [0, 0.141, 0.99], [0.767, 0.576, 0.284]])
        X_inv = linalg.inv(X)
        y = np.log(img1)
        C = y @ X_inv

        null = np.zeros_like(C[:, :, 0])
        C_a = np.stack((C[:, :, 0], null, null), axis=-1)
        C_b = np.stack((null, C[:, :, 1], null), axis=-1)
        C_c = np.stack((null, null, C[:, :, 2]), axis=-1)

        conv_matrix = X
        log_rgb_a = C_a @ conv_matrix
        rgb1 = np.exp(log_rgb_a)
        log_rgb_b = C_b @ conv_matrix
        rgb2 = np.exp(log_rgb_b)
        log_rgb_c = C_c @ conv_matrix
        rgb3 = np.exp(log_rgb_c)

        rgb1[rgb1 < 0] = 0
        rgb1[rgb1 > 1] = 1

        rgb2[rgb2 < 0] = 0
        rgb2[rgb2 > 1] = 1

        rgb3[rgb3 < 0] = 0
        rgb3[rgb3 > 1] = 1

        height, width, bands = rgb1.shape
        linear = rgb1.reshape(width * height * bands)
        vi1 = pyvips.Image.new_from_memory(linear.data, width, height, bands,
                                          dtype_to_format[str(rgb1.dtype)])

        height, width, bands = rgb2.shape
        linear = rgb2.reshape(width * height * bands)
        vi2 = pyvips.Image.new_from_memory(linear.data, width, height, bands,
                                          dtype_to_format[str(rgb2.dtype)])

        height, width, bands = rgb3.shape
        linear = rgb3.reshape(width * height * bands)
        vi3 = pyvips.Image.new_from_memory(linear.data, width, height, bands,
                                          dtype_to_format[str(rgb3.dtype)])

        image_CD8 = pyvips.Image.arrayjoin(vi1, across=img.width)
        image_PanCK = pyvips.Image.arrayjoin(vi2, across=img.width)
        image_Hema = pyvips.Image.arrayjoin(vi3, across=img.width)

image_CD8.tiffsave("CD8.png")   
image_PanCK.tiffsave("PanCK.tif")
image_Hema.tiffsave("Hema.tif")`

**Comment by SikangSHU** [comment]
> Dear professor: I consider to do some works on the patches which are 512*512, so I make a NumPy array from a vips image for each patch. I am sure that the step which makes a NumPy array from a vips image is correct, but I don't know why an error occurred after I do works on the NumPy array. Can you help me with the code I marked with '@@@@@' that may lead to the mistake. Thank you very much!
> 
> `import pyvips import numpy as np from numpy import linalg from skimage.color.colorconv import _prepare_colorarray
> 
> img = pyvips.Image.new_from_file('E:\test4.png', access='sequential') patch_size = 512 n_across = img.width // patch_size n_down = img.height // patch_size x_max = n_across - 1 y_max = n_down - 1
> 
> format_to_dtype = { 'uchar': np.uint8, 'char': np.int8, 'ushort': np.uint16, 'short': np.int16, 'uint': np.uint32, 'int': np.int32, 'float': np.float32, 'double': np.float64, 'complex': np.complex64, 'dpcomplex': np.complex128, } dtype_to_format = { 'uint8': 'uchar', 'int8': 'char', 'uint16': 'ushort', 'int16': 'short', 'uint32': 'uint', 'int32': 'int', 'float32': 'float', 'float64': 'double', 'complex64': 'complex', 'complex128': 'dpcomplex', } for y in range(0, n_down): print("row {} ...".format(y)) for x in range(0, n_across): patch = img.crop(x * patch_size, y * patch_size, patch_size, patch_size)
> 
> ```
>     vi_np = np.ndarray(buffer=patch.write_to_memory(),
>                        dtype=format_to_dtype[patch.format],
>                        shape=[patch.height, patch.width, patch.bands])
> 
>     img1 = _prepare_colorarray(vi_np, force_copy=True)          @@@@@
>     np.maximum(img1, 1E-6, out=img1)
>     X = np.array([[0.468, 0.721, 0.511], [0, 0.141, 0.99], [0.767, 0.576, 0.284]])
>     X_inv = linalg.inv(X)
>     y = np.log(img1)
>     C = y @ X_inv
> 
>     null = np.zeros_like(C[:, :, 0])
>     C_a = np.stack((C[:, :, 0], null, null), axis=-1)
>     C_b = np.stack((null, C[:, :, 1], null), axis=-1)
>     C_c = np.stack((null, null, C[:, :, 2]), axis=-1)
> 
>     conv_matrix = X
>     log_rgb_a = C_a @ conv_matrix
>     rgb1 = np.exp(log_rgb_a)
>     log_rgb_b = C_b @ conv_matrix
>     rgb2 = np.exp(log_rgb_b)
>     log_rgb_c = C_c @ conv_matrix
>     rgb3 = np.exp(log_rgb_c)
> 
>     rgb1[rgb1 < 0] = 0
>     rgb1[rgb1 > 1] = 1
> 
>     rgb2[rgb2 < 0] = 0
>     rgb2[rgb2 > 1] = 1
> 
>     rgb3[rgb3 < 0] = 0
>     rgb3[rgb3 > 1] = 1
> 
>     height, width, bands = rgb1.shape
>     linear = rgb1.reshape(width * height * bands)
>     vi1 = pyvips.Image.new_from_memory(linear.data, width, height, bands,
>                                       dtype_to_format[str(rgb1.dtype)])
> 
>     height, width, bands = rgb2.shape
>     linear = rgb2.reshape(width * height * bands)
>     vi2 = pyvips.Image.new_from_memory(linear.data, width, height, bands,
>                                       dtype_to_format[str(rgb2.dtype)])
> 
>     height, width, bands = rgb3.shape
>     linear = rgb3.reshape(width * height * bands)
>     vi3 = pyvips.Image.new_from_memory(linear.data, width, height, bands,
>                                       dtype_to_format[str(rgb3.dtype)])
> 
>     image_CD8 = pyvips.Image.arrayjoin(vi1, across=img.width)
>     image_PanCK = pyvips.Image.arrayjoin(vi2, across=img.width)
>     image_Hema = pyvips.Image.arrayjoin(vi3, across=img.width)
> ```
> 
> image_CD8.tiffsave("CD8.png") image_PanCK.tiffsave("PanCK.tif") image_Hema.tiffsave("Hema.tif")`

The error is TypeError: 
Traceback (most recent call last):
  File "E:/Learning/Graduate/Python_learning/python_learn/wsi2.py", line 44, in <module>
    patch = img.crop(x * patch_size, y * patch_size,
  File "D:\Download\anaconda\Anaconda3\envs\learn\lib\site-packages\pyvips\vimage.py", line 938, in call_function
    return pyvips.Operation.call(name, self, *args, **kwargs)
  File "D:\Download\anaconda\Anaconda3\envs\learn\lib\site-packages\pyvips\voperation.py", line 282, in call
    op.set(name, intro.details[name]['flags'], match_image, value)
  File "D:\Download\anaconda\Anaconda3\envs\learn\lib\site-packages\pyvips\voperation.py", line 216, in set
    super(Operation, self).set(name, value)
  File "D:\Download\anaconda\Anaconda3\envs\learn\lib\site-packages\pyvips\vobject.py", line 112, in set
    gv.set(value)
  File "D:\Download\anaconda\Anaconda3\envs\learn\lib\site-packages\pyvips\gvalue.py", line 167, in set
    gobject_lib.g_value_set_int(self.gvalue, int(value))
TypeError: only size-1 arrays can be converted to Python scalars

**Comment by jcupitt** [comment]
I'll close this -- I think I answered the question in #289
