### ISSUE TITLE
Unable to install pyvips through conda only by pip, followed by cannot load library 'libgobject-2.0-0.dll' error

### ISSUE THREAD

**Issue by muruga86** [libvips/pyvips#302]
I am unable to install pyvips package through conda, get following error.
conda install --channel conda-forge pyvips
conda install -c conda-forge pyvips

PS D:\templatecode>
PS D:\templatecode> conda install --channel conda-forge pyvips
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - pyvips

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

PS D:\templatecode> conda install -c conda-forge pyvips
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - pyvips

Current channels:

  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by muruga86** [comment]
Able to install only via pip

PS D:\templatecode>
PS D:\templatecode> pip install  pyvips      
Collecting pyvips
  Downloading pyvips-2.1.16.tar.gz (625 kB)
     |████████████████████████████████| 625 kB 6.4 MB/s
Requirement already satisfied: cffi>=1.0.0 in c:\programdata\anaconda3\lib\site-packages (from pyvips) (1.14.5)
Requirement already satisfied: pycparser in c:\programdata\anaconda3\lib\site-packages (from cffi>=1.0.0->pyvips) (2.20)
Building wheels for collected packages: pyvips
  Building wheel for pyvips (setup.py) ... done
  Created wheel for pyvips: filename=pyvips-2.1.16-py2.py3-none-any.whl size=48689 sha256=0eeb2337354d3e948eed969666cd2298d7f0a1e3726b2c271de2ad4b057aef22
  Stored in directory: c:\users\administrator\appdata\local\pip\cache\wheels\e9\f0\fd\467277b686c2dff8b7149c41df7c37ed2c62efbdb1c73779eb
Successfully built pyvips
Installing collected packages: pyvips
Successfully installed pyvips-2.1.16
PS D:\templatecode>

**Comment by jcupitt** [comment]
Hello @muruga86,

I would ask on the pyvips conda repo. They manage the conda package:

https://github.com/conda-forge/libvips-feedstock
