### ISSUE TITLE
Question: Use Image.write_to_target to write a tif

### ISSUE THREAD

**Issue by ap--** [libvips/pyvips#307]
Dear pyvips developers,

I was playing with `Image.write_to_target` and was wondering how to write pyramidal tifs:

```python
import fsspec
import pyvips

with fsspec.open_file("s3://mybucket/file.tif", mode="wb") as buffer:

    target = pyvips.TargetCustom()
    target.on_write(buffer.write)
    target.on_finish(buffer.close)

    image.write_to_target(
        target, ".tif",
        pyramid=True,
        tile=True,
        compression="jpeg",
    )

```

but I get the following error:
```
Error: unable to write to target
  VipsForeignSave: ".tif" is not a known target format
```

Are there plans to create a tiffsave_target extension?

Cheers,
Andreas :smiley:

**Comment by jcupitt** [comment]
Hi @ap--,

TIFF write is a bit more complex since it needs to support things like pyramid creation. It's on the to-do list, but no one's done it yet :(

**Comment by ap--** [comment]
Hi @jcupitt,

So this would need to land in libvips first?
Is there a good example PR or commit for another `<...>save_target` implementation?
I might have some free bandwidth in a few weeks to work on this.
And should we then move this issue to libvips?

Cheers,
Andreas 😃

**Comment by jcupitt** [comment]
I made an enhancement issue with a few notes:

https://github.com/libvips/libvips/issues/2680

It's slightly awkward because we need to design and implement some core API first. And the tiff writer is relatively complex :( 2,500 lines of C.

**Comment by kleisauke** [comment]
https://github.com/libvips/libvips/discussions/2051 also includes some details on how the other loaders/savers were reworked for the source/target API.

**Comment by jcupitt** [comment]
This feature is in libvips 8.13. I'll close.
