### ISSUE TITLE
step value for bandwise slice is silently ignored

### ISSUE THREAD

**Issue by erdmann** [libvips/pyvips#308]
It looks like the syntactic sugar of using `__getitem__`  with a slice to get at bands on  `pyvips.Image` objects is silently ignoring the step part of the slice.

For example:
```python
import pyvips

xy = pyvips.Image.xyz(3, 4)
xyxyxy = xy.bandjoin(xy).bandjoin(xy)

print(f'OK:  {xy[0].max() = }')
print(f'OK:  {xy[1].max() = }')
print(f'OK:  {xyxyxy.bands = }')
print(f'OK:  {xyxyxy[:3].bands = }')
print(f'BUG: {xyxyxy[::2].bands = }')  # step silently ignored
# reversing x,y into row,col via idiomatic [::-1] reversing slice
print(f'BUG: {(xy[::-1] == xy).min() = }')  # These match because step=-1 is silently ignored

# OK:  xy[0].max() = 2.0
# OK:  xy[1].max() = 3.0
# OK:  xyxyxy.bands = 6
# OK:  xyxyxy[:3].bands = 3
# BUG: xyxyxy[::2].bands = 6
# BUG: (xy[::-1] == xy).min() = 255.0

```

Thanks in advance!

**Comment by jcupitt** [comment]
Hi @erdmann,

Yes, I never tried to implement that. Let's tag it as an enhancement.

**Comment by erdmann** [comment]
Hi @jcupitt,

I agree that making slices work is an enhancement.   Silently ignoring them rather than raising an error is the part that seemed like a bug.

**Comment by erdmann** [comment]
I'm going to fix this and make a pull request.

**Comment by jcupitt** [comment]
Argh, we crossed over, I've hacked it in too. Let's combine our patches.

**Comment by erdmann** [comment]
D'oh!  Indeed.  I see that your approach is slightly different, which led me to ask a performance question on a comment on  PR #309.  (If this is a better venue to discuss that question for the benefit of others, please let me know.  I have learned most of what I know about libvips and pyvips by reading the discussions of issues.)

How should we proceed?

**Comment by jcupitt** [comment]
Yes, sorry, I started hacking it in and didn't say.

Yes, `vips_bandjoin()` can join many images in one shot, so especially for large numbers of images, it can be quite a bit quicker. It's good to hit that path if possible.

Python doesn't let you have an object method and a class method with the same name, unfortunately, so in py it appears as `image.bandjoin([images])` and this causes the weird `bands[0].bandjoin(bands[1:])`.

Thinking about it again, the `len(bands) == 0` case should probably be an `IndexError` rather than returning `[]`. I'll fix it.

`image.bandjoin([])` should probably just return `image`. That would make this change a bit less ugly, I'll add that case.

**Comment by erdmann** [comment]
Good to know, thanks.

To clarify, my performance question was about the broader effect of splitting and then re-joining already contiguous bands.  Specifically, I see that in the slicing section you have several lines dealing with keeping track of starts and stops, but this seems equivalent and simpler/more compact:
```python
bands = [ self.extract_band(i) for i in range(self.bands)[arg] ]
return bands[0].bandjoin(bands[1:])
```
So the question is whether, in the case in which `arg.step` is 1 so that the bands we're extracting from `self` are already contiguous, doing the above will cause performance issues downstream in subsequent `libvips` calculations arising from separating once-contiguous bands and then gluing them back together.  In other words, will doing the above cause reduced performance in downstream operations relative to what we would see if we used `self.extract_band(i, n=n)`?

**Comment by jcupitt** [comment]
Yes, `.extract_band()` has a special path for extracting contiguous bands and again it's best to hit that if possible.

**Comment by erdmann** [comment]
I was wondering about this too.  I guess it depends on whether there is such a thing as a zero-band image, since this is kosher with Python lists:

```python
a = [1, 2, 3, 4, 5]
print(a[4:1])
# []
```

I'll fix up #309 to account for these edge cases.

**Comment by jcupitt** [comment]
I think it has to be an error, otherwise `image[x:y]` can return either a list or an image, depending on the values of x and y. It would cause a lot of ugly downstream type checking :(

**Comment by erdmann** [comment]
Definitely.  (The question about zero-band images was a bad joke.)
