### ISSUE TITLE
`getattr(pyvips.Image, anything)` returns `True` when it should raise `AttributeError`

### ISSUE THREAD

**Issue by erdmann** [libvips/pyvips#314]
I'm working on making it more convenient to work with pyvips images with numpy.  Numpy offers a way for foreign objects to be interpreted as arrays:  a class need only define the `__array__` method, whereupon `np.array(im)` will call this.   This is how [Pillow does it](https://github.com/python-pillow/Pillow/blob/77f12cd473701ca460a3cc0a8430e1f3d4679e4b/src/PIL/Image.py#L705), for example.

The problem is that if I define this `__array__` method on `pyvips.Image`, it never gets called because numpy has some complex behavior where it looks for the most efficient ways to turn something into an array (without copying, e.g.), so it first looks up `__array_struct__` to attempt C-struct access and then falls back to trying other things (see [The Array Interface](https://numpy.org/doc/stable/reference/arrays.interface.html)).  Ok, no problem except that the way pyvips is setup, when numpy goes looking for `__array_struct__`, it can't see that it doesn't exist because of this behavior:

```python
import pyvips
print(hasattr(pyvips.Image, 'doesntexist'))
# True  # (wat)
```

So I guess somehow due to the way it interfaces with libvips, pyvips is deferring method resolution until it's actually called, but by then it's too late for numpy to figure out that it should have used `__array__` instead.

```python
im = pyvips.Image.black(4, 4)
ai = im.__array_interface__  #  The bug is here.  Should raise AttributeError immediately but doesn't.
print('Ready to call')
ai() # the **call** is what raises, but not AttributeError

#  Ready to call
#  Error: no such operation __array_interface__
#   VipsOperation: class "__array_interface__" not found
```

I think this is a bug insofar as it violates the usual semantics of how to deal with presence of methods, etc.   As the Python documentation [says](https://docs.python.org/3/library/functions.html#hasattr), `hasattr`

> ... is implemented by calling getattr(object, name) and seeing whether it raises an [AttributeError](https://docs.python.org/3/library/exceptions.html#AttributeError) or not.

If you have any ideas on how to fix this, I'm happy to give it a try, though the various ways that pyvips interfaces with libvips is sort of "here be dragons" territory for me so I doubt I'd be very useful.

Thanks in advance!

**Comment by jcupitt** [comment]
Hi Rob,

Ah I see. Sure, I'll have a quick go in a PR, I think I can see an efficient way to fix this.

**Comment by jcupitt** [comment]
Looking at the PIL `__array__` method, maybe we could have numpy as a run-time (ie. optional) dependency. Would that work?

**Comment by erdmann** [comment]
I was going to suggest that, yes. It's the approach taken by various libraries where there are only a couple of contacts with a 3rd-party library.  The foreign library is then imported in the relevant function(s), so that users who never use them never need the library, and startup times are not affected.  In our case, I think that would be pyvips->numpy and numpy->pyvips.

Shall I implement this?

**Comment by erdmann** [comment]
Or, more usefully for converting an object into a `pyvips.Image`, the ability to ingest anything implementing `__array_interface__`.

**Comment by jcupitt** [comment]
Yes, that sounds extremely useful!

I added `toarray()` a short while ago, but it's terrible. A better `toarray()` method would be great too.

**Comment by erdmann** [comment]
Ok, #316 adds functionality to go to/from numpy and array-like things, and also provides an efficient implementation of what  is now called `.tolist()` to turn single-band images of any type into lists of lists.  Thanks for the help in getting this in!
