### ISSUE TITLE
stack DSMs of different sizes, resolutions and projections in a certain region until all pixels contain data

### ISSUE THREAD

**Issue by Janphr** [libvips/pyvips#324]
Hey,
I try to fuse DSMs from different sources and wanted to ask if you might know an elegant solution for this. 
My idea is to have underlying data e.g. tifs from [here](https://land.copernicus.eu/imagery-in-situ/eu-dem/eu-dem-v1.1) which are 40kx40k and about 5GB each. Since the data is somewhat old and the resolution is low, I generate my own DSMs with a lidar scanner on a drone. Since those are never perfectly square and complete, I thought I could fill the 'nodata' pixels with the underlying tif.

So in the end I'd like to request an area from my geotif database and the script returns a new tif with the most recent data in the highest available resolution for each pixel. I've already got something somewhat working, but it contains a lot of cropping and checks for overlapping out of bounds etc...somewhat error-prone I'd say. I saw [this](https://github.com/libvips/libvips/issues/1438) example here and thought, maybe I could just fuse the tifs in separate bands in a certain order, fill the 'out of bounds' pixels with nodata and then just merge everything back to one band...this way I can use it for trajectory planning etc.

So do you think your approach in the example would work for this? When I drop all the tifs into QGIS, it basically already does just that. From that representation, I'd just need an efficient way of extracting areas

https://user-images.githubusercontent.com/45623010/163041431-54adedef-783a-491b-b890-dd39339580ce.mp4

If you encountered a problem like that before, any help would be much appreciated!

**Comment by jcupitt** [comment]
Hi @Janphr,

libvips can do this reasonably efficiently. You can use `composite` to layer many images over each other, and for each output tile it'll just merge the layers that are visible at that point (ie. it won't loop over all layers). How many images do you need to layer? It should be fine for 1,000 or so. More than that and some extra optimization would probably be useful.

`composite` will only work with rectangular images with an alpha, so you'd need to compute the alpha for each of your DSMs. I expect you have something to do this already.

In python:

```python
#!/usr/bin/python3

import sys
import random
import pyvips

# sigma of the feather we add, and approximate radius in pixels
FEATHER_SIGMA = 4
FEATHER_WIDTH = 7

print("loading images ...")
images = [pyvips.Image.new_from_file(filename) for filename in sys.argv[2:]]

def make_white(width, height):
    white = pyvips.Image.black(width, height) + 255
    white = white.cast('uchar')

    return white

# make a one-band uchar image with a feathered edge
def soft_alpha(width, height):
    black = pyvips.Image.black(width, height)
    white = make_white(width - 2 * FEATHER_WIDTH,
                       height - 2 * FEATHER_WIDTH)
    mask = black.insert(white, FEATHER_WIDTH, FEATHER_WIDTH)
    alpha = mask.gaussblur(FEATHER_SIGMA, precision='integer')
    white = make_white(width - 4 * FEATHER_WIDTH,
                       height - 4 * FEATHER_WIDTH)
    alpha = alpha.insert(white, 2 * FEATHER_WIDTH, 2 * FEATHER_WIDTH)

    return alpha

# add a soft alpha and pad each image out to the final size
print("adding feather ...")
images = [image.bandjoin(soft_alpha(image.width, image.height))
          for image in images]

# composite all the images together at random positions
base = pyvips.Image.black(10000, 10000)
xes = [random.randint(0, base.width) for image in images]
yes = [random.randint(0, base.height) for image in images]
final = base.composite(images, 'over', x=xes, y=yes)

print("starting final write ...")
final.write_to_file(sys.argv[1])
```

Use with eg.:

```
./composeup.py output.tif[compression=jpeg,tile,pyramid] *.jpg
```

And it'll render all the jpgs in the current directory over a 10k x 10k TIFF, with feathered edges. Instead of writing to a file, you can crop out areas of the output and render to a display.

**Comment by Janphr** [comment]
Thank you @jcupitt!
Sorry for closing this prematurely, I had found a way to do this already and though I might save you some time.
The composite will still come in handy when it comes to visualize everything in the GUI!
