### ISSUE TITLE
When Crop Img Happend Error

### ISSUE THREAD

**Issue by gVimer** [libvips/pyvips#329]
![image](https://user-images.githubusercontent.com/6241431/169024456-2a3c88ae-a7c1-4661-b98d-5305cb9e6563.png)

Who Can Help Me?THX

**Comment by jcupitt** [comment]
Hello @gVimer,

Your loop is not requesting tiles from the image in top-to-bottom order. You can only read pixels from sequential sources in order from the start of the file.

Either revise your loop, or don't use sequential mode.
