### ISSUE TITLE
try pyvips openslideload get Error: no such operation openslideload   VipsOperation: class "openslideload" not found

### ISSUE THREAD

**Issue by jasnei** [libvips/pyvips#333]
Hi
greeting!
I tried pyvip.Image.openslideload() method to load a pathology image. And tried this method, because I found it on the docs, it would allow me to read certain level. Instead I got below error, not openslideload operation. It was version 2.2, and changed 2.1.16. Still the same problem.
![image](https://user-images.githubusercontent.com/52853052/173164423-1a45615d-2752-4bb4-913d-db2c6fee8212.png)

here is my vips version, and it's vips-dev-w64-all-8.12.2.zip
and my system is: windows 11 22H2
![image](https://user-images.githubusercontent.com/52853052/173164065-3558585b-bb14-4402-abff-dc737891df07.png)

actually it work when used pyvips.Image.new_from_file(filename), but this could not have level arguement.
and I had tried the ways  from https://github.com/libvips/pyvips/issues/157

but still not work for me.

I hope someone could help me out.

Thanks
Albert

**Comment by jcupitt** [comment]
Hello @jasnei,

I would guess you have two libvips on your PC. You are seeing one with openslide support at the command-line, and one without when you use python.

It looks like you added the libvips bin area to your PATH. I wouldn't do this, it's too dangerous on windows. Instead, set PATH from python before importing pyvips.

(also, if possible, don't post screenshots ... just copy-paste the text)

**Comment by jasnei** [comment]
Hi @jcupitt 

Thanks for you quick reply

I just have a libvips on my PC actually.

I follow your advice not add the PATH, but not work for my PC. I seems I have to add libvips to the PATH which would work on this PC. But never mind.

Your quick answer is much appreciated.

Good luck
