### ISSUE TITLE
Callable for tiffsave

### ISSUE THREAD

**Issue by LionelArn2** [libvips/pyvips#334]
Hello :)

I'm looking for some kind of way to call `tiffsave` on a pseudo image at a point in time when the entirety of the image data is not yet available. As an example, say we have 30% of this pseudo image pixels computed and stored as a numpy array in our own code, and the remaining 70% will be computed in the future, but we would like to start saving the image now to gain some time. The final image size, bit depth and all other metadata is known.

In your documentation, I found that we can already create an image from a custom source (`vips.SourceCustom` and `vips.Image.new_from_source`) and attach our own handler method to the source on_read and on_seek events. This is great and could work of course, but (if I'm not mistaken) this is typically made for cases where you have an input image file from which the handlers can read and seek, which is not the case here. When I tried using this, the handlers tried to access different area of the file to read its metadata at the beginning, and I'm not sure what to return in my custom read and seek handlers.

Is there already another way to do this that I'm missing?

**Comment by jcupitt** [comment]
Hi @LionelArn2,

There has been talk of adding a way to trigger user code during image write (eg. https://github.com/libvips/pyvips/issues/155), but it hasn't happened yet. Maybe in the next version.

It'd look something like:

```python
def on_generate(left, top, width, height):
    # make a buffer object containing the pixels in this rectangle
    data = compute some values
    return data

# make a 10,000 x 10,000 pixel image and call on_generate to make
# pixels on demand ... optional args could set bands, numeric format, etc.
image = pyvips.Image.new_from_function(10000, 10000, on_generate)

# libvips will trigger on_generate whenever the tiff saver needs more 
# pixels to write
image.write_to_file("x.tif")
```

**Comment by LionelArn2** [comment]
Thanks for the clear answer, indeed that would be great 👍
