### ISSUE TITLE
splitting a whole slide image into two

### ISSUE THREAD

**Issue by KVishnuVardhanR** [libvips/pyvips#345]
I'm working on a cell classification problem using whole slide images although only constraint is that I have to utilize no more than 12GB RAM. So I want to split the whole slide image into two and crop the patches of the image which contains the cell and train a deep neural net on it.

The image has a dimensions of (48282, 101406, 3), I have gone through pyvips documentation but couldn't figure out how split an image in two.

```
image = pyvips.Image.new_from_file("cell.tif", access = 'sequential')
image.width, image.height # (48282, 101406)

#split image into 2
image1 = ?
image1.width, image1.height # (24141, 50703)
image2 = ?
image2.width, image2.height # (24141, 50703)
```

Can anyone help me on how to split an image of width 48282 and height of 101406 to 2 images of dimension (24141, 50703, 3), (24141, 50703, 3)?

**Comment by jcupitt** [comment]
Hi @KVishnuVardhanR,

Isn't that 1/4 of the image? You only heed to halve one of the dimensions.

You can do something like this:

```python
image = pyvips.Image.new_from_file("xx.svs")
top_image = image.crop(0, 0, image.width, image.height // 2)
bottom_image = image.crop(0, image.height // 2, image.width, image.height - image.height // 2)
```

**Comment by KVishnuVardhanR** [comment]
Yes, you are correct, Thank you so much, I wanted 2 halves of the image, not 1/4.
