### ISSUE TITLE
Possible to bypass decode encode when writing compressed images to tiff file?

### ISSUE THREAD

**Issue by Klubban** [libvips/pyvips#346]
Hi libvips/pyvips community!

I would like to create a tiled, pyramidal tiff from already compressed images. In my application I don't get all images at once and while waiting for images I could save time by doing jpeg compression on the ones I have. However It appears that pyvips decodes and encodes images when writing it to file. Which in this case is redundant. 

Is it possible to utilize that the images already are compressed? 

Below follows a small test script that generates bytearrays of synthetic images. The mosaic has a much larger amount of tiles than in the test script, in pixels the mosaic is usually around 65000x130000x3 pixels.

```
import cv2
import numpy as np
import pyvips

num_rows = 3
num_cols = 3
tile_shape = (512, 512, 3)
bands = 3
Q = 80
ims = []

# generate num_rows*num_cols tiles. Each tile is jpeg compressed Q=80.
for i in range(0, num_rows * num_cols):
    im = cv2.putText(np.ones(tile_shape, np.uint8) * 255, f'{i}', (50, 300), cv2.FONT_HERSHEY_SIMPLEX, 5,
                     (0, 0, 255), 3, cv2.LINE_AA)
    ims.append(pyvips.Image.new_from_buffer(cv2.imencode('.JPEG', im,
                                                         [int(cv2.IMWRITE_JPEG_QUALITY), Q])[1].tobytes(), ""))

# Array join all jpeg compressed images to get mosaic shape
final_image = pyvips.Image.arrayjoin(ims, across=num_cols)

# what I would like to do
# final_image.write_to_file('testometest.ome.tif', compression='COPY CONTENT FROM BYTEARRAY', subifd=True, pyramid=True)
final_image.write_to_file('testometest.ome.tif', compression='jpeg', subifd=True, pyramid=True)
```

Thank you for a great software package!

**Comment by jcupitt** [comment]
Hi @Klubban,

Sorry, libvips always works with uncompressed images. You'll need to write your own thing if you need to copy compressed tiles losslessly.

We've been talking about adding a pyvips thing to let you generate image tiles with a callback, see: https://github.com/libvips/pyvips/issues/334 It might solve part of your problem.

**Comment by Klubban** [comment]
Looks like #155 #334 could do the trick for me aswell. Thank you for your quick reply and your help!

**Comment by hubutui** [comment]
It seems you're looking for windowed reading and writing, then this https://github.com/libvips/pyvips/issues/155#issuecomment-1981111687 might help.
