### ISSUE TITLE
Update install steps for Python 3.8+

### ISSUE THREAD

**Issue by CristiFati** [libvips/pyvips#351]
*v2.2.1* (latest at issue creation time) doesn't officially support *Python 3.8* (it's not in the list in [\[PyPI\]: pyvips 2.2.1](https://pypi.org/project/pyvips/2.2.1) - although it actually works).
When newer *Python* versions support will be added, the install steps need some changes, which are explained in [\[SO\]: OSError: Cannot find pyvips library (DLLs) (@CristiFati's answer)](https://stackoverflow.com/a/73934513/4788546).

**Comment by jcupitt** [comment]
Hi @CristiFati,

Thanks for reporting this -- you're right, the list of supported pythons hasn't been updated for a while. I use it with 3.10, so I added that too.

I pasted in your code fragment for 3.8+ on windows too. Thanks!

**Comment by jcupitt** [comment]
... oops, fixed the code fragment with https://github.com/libvips/pyvips/commit/de561fd2e4a8ee6e0531c27401b69763c2807e6d

**Comment by CristiFati** [comment]
Just looked over the *SO* answer: it didn't have the error. :)
