### ISSUE TITLE
Thumbnails - fail on down-only

### ISSUE THREAD

**Issue by dreadedhamish** [libvips/pyvips#361]
I'm experimenting with the SIZE variable using Thumbnail.

As I understand it (and I think this could be clearer in the docs), using size="down" restricts the resize from ever upscaling the image, and in the case there the target width is greater than the original image, Thumbnail will proceed with exporting an image, but would keep the original resolution.
I had hoped (maybe expected) that if the condition wasn't met, then the whole thumbnail process would fail. The baove behaviour makes sense when the user is exporting a single image, but I'm making multiple thumbnails at different widths, and currently if a small image sneaks into the workflow I'm going to end up with 6 copies of it all at the same resolution, with no indication that this happened.

Have I missed an argument somewhere?

So in my use case what I'm going to have to do it is:
1. load the original image
2. grab it's width and height
3. add conditionals to each each thumbnail generation call.
(which won't be that troublesome if I can figure out how to pass an array of sizes and arguments to a pyvips.thumbnail loop).

Would some new options be helpful? Like "down-or-die"?

(also I'd suggest adding to the documentation the options for size are "down" and "up", rather than "downsize and "upsize")

**Comment by dreadedhamish** [comment]
I think I've got my use-case figured out:

> thumbs = {
    'sml':{'width':600, 'height':400, 'size':'down'},
    'med':{'width':800, 'height':600, 'size':'down'},
    'lge':{'width':1200, 'height':800, 'size':'down'}
}
> jpeg_out` = { "Q":90, "optimize_coding":1, 'strip':1, "interlace":1, "optimize_scans":1, "trellis_quant":1, "quant_table":3 }

> source = pyvips.Image.new_from_file(filename)
source_width = source.get('width')
source.write_to_file(f"./image-cache/{postID}_orig.jpg", **jpeg_out) #save an original

> for size, args in thumbs.items(): #loop through the variations
    print(size, ' : ', args)
    if args['width'] < source_width:
        thumb = pyvips.Image.thumbnail(filename, args['width'])
        thumb.write_to_file(f"./image-cache/196_{size}.jpg", **jpeg_out)

**Comment by jcupitt** [comment]
```python
source_width = source.get('width')
```

You can just write `source.width`.

**Comment by jcupitt** [comment]
> I had hoped (maybe expected) that if the condition wasn't met, then the whole thumbnail process would fail.

I think the bahaviour is compied from imagemagick -- it's used to implement size specifications like:

```
$ vipsthumbnail image --size "100x100<"
```

For compatibility with `convert`.

**Comment by dreadedhamish** [comment]
@jcupitt yeah, no sweat now that I know it's a method of conversion, not a condition.
(maybe a note in the docs for people like me would be helpful)

**Comment by dreadedhamish** [comment]
All sorted - for width at least. now to incorporate some height checks, and then maybe circle back to my other issue of streaming the file straight from requests rather than saving a local copy. Thanks again.

**Comment by jcupitt** [comment]
> (maybe a note in the docs for people like me would be helpful)

The main docs seem clear to me:

https://www.libvips.org/API/current/libvips-resample.html#vips-thumbnail

Do you think they need expansion?

I agree the python docs are not good :( They are mostly generated automatically, so we don't have a huge amount of control. 

The pyvips doc generator ought to paste in chunks of the main docs, but no one's got around to implementing that yet.
