### ISSUE TITLE
I hope the official can maintain the golang version

### ISSUE THREAD

**Issue by zhanghaidi** [libvips/pyvips#367]
I hope the official can maintain the golang version，Because the use scenarios of go language are very broad, this version is urgently needed to process medical svs image scenarios. Currently, Govips maintained by third parties are not friendly, and many functions are missing, such as the dzsave() method, and many other methods are also missing. Please accept

**Comment by jcupitt** [comment]
Sorry, I don't think I have time to make another binding right now.
