### ISSUE TITLE
Extracting 40x image as bigtiff file from pyramidal wsi tif image 

### ISSUE THREAD

**Issue by andanison** [libvips/pyvips#371]
Hi, I have pyramidal tif image (with highest 40x resolution image of the order of ~100kx100k pixels). 
I would like to
- extract highest resolution 40x image as  bigtiff file format from pyramidal wsi tif image 
- the extracted image should not have any change in image quality / pixel values 
- the extracted image should be <5GB (to be able to run with spaceranger 10x Visium spatial transcriptomics pipeline)

Now, I tried different compression techniques. lzw, deflate, zstd: they keep the pixel values the same but generate large images (~12GB). jp2k generates <5GB image but the pixel values change. 

I use following lines to extract the image

```
img = pyvips.Image.new_from_file(img_path access='sequential')
img.tiffsave(save_path, compression='lzw', pyramid=False, bigtiff=True, Q=100, tile=True, tile_width=2048, tile_height=2048)

```
I also tried with and without tiling but observed similar effect. 
I would really appreciate if you can help me solve the issue.

**Comment by jcupitt** [comment]
Hi @andanison,

libvips won't do what you want -- it always decompresses images on load and recompresses on save, so pixels will always change.

Is this an SVS image? You might be able to make a new tiff without going through a decompress/recompress cycle using tiffcp or tiffsplit.

**Comment by andanison** [comment]
thank you for the quick reply @jcupitt!! 

re libvips: if the pixels change on recompressing on save, would it affect the image quality when used in deep learning pipeline? 

It is not an svs image. It is tiff pyramid wsi. Would tiffcp or tiffsplit still work? Can these tools help extract highest resolution image without any change in pixels and less than <5GB size? If yes, could you maybe point me to their usage?

**Comment by jcupitt** [comment]
> re libvips: if the pixels change on recompressing on save, would it affect the image quality when used in deep learning pipeline?

Your images are already colour-filtered, bayer-reconstructed, smoothed, sharpened, companded and compressed, so an extra decompress/recompress isn't going to make much difference, in my opinion. And an appropriate amount of overtraining should remove any detection of compression artefacts by your network.

> It is tiff pyramid wsi. Would tiffcp or tiffsplit still work?

Sure, should do. They might not be under 5gb, of course, it depends on the image size and how it has been compressed.

First use tiffinfo to see the structure of your file. For example:

```
$ tiffinfo 5-PYR_PAP_48-1.tif
=== TIFF directory 0 ===
TIFF Directory at offset 0xb65b550 (191214928)
  Image Width: 54720 Image Length: 53040
  Tile Width: 128 Tile Length: 128
  Resolution: 10, 10 pixels/cm
  Bits/Sample: 8
  Sample Format: unsigned integer
  Compression Scheme: JPEG
  Photometric Interpretation: YCbCr
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 3
  Planar Configuration: single image plane
  Reference Black/White:
     0:     0   255
     1:   128   255
     2:   128   255
  JPEG Tables: (574 bytes)
=== TIFF directory 1 ===
TIFF Directory at offset 0xe9a976c (245012332)
  Subfile Type: reduced-resolution image (1 = 0x1)
  Image Width: 27360 Image Length: 26520
  Tile Width: 128 Tile Length: 128
  Resolution: 10, 10 pixels/cm
  Bits/Sample: 8
  Compression Scheme: JPEG
  Photometric Interpretation: YCbCr
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 3
  Planar Configuration: single image plane
  Reference Black/White:
     0:     0   255
     1:   128   255
     2:   128   255
  JPEG Tables: (574 bytes)
...
```

This file has 10 directories, with dir0 having the highest resolution layer. The layer is tiled and JPEG compressed, with 128x128 pixel tiles, and YCbCr chroma subsampling.

I can split the file like this:

```
$ mkdir x
$ cd x
$ tiffsplit ../5-PYR_PAP_48-1.tif 
$ ls
xaaa.tif  xaac.tif  xaae.tif  xaag.tif  xaai.tif
xaab.tif  xaad.tif  xaaf.tif  xaah.tif  xaaj.tif
$ tiffinfo xaaa.tif 
=== TIFF directory 0 ===
TIFF Directory at offset 0xb65b550 (191214928)
  Image Width: 54720 Image Length: 53040
  Tile Width: 128 Tile Length: 128
  Resolution: 10, 10 pixels/cm
  Bits/Sample: 8
  Sample Format: unsigned integer
  Compression Scheme: JPEG
  Photometric Interpretation: YCbCr
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 3
  Planar Configuration: single image plane
  JPEG Tables: (574 bytes)
```

dir0 is named as `xaaa.tif`, and you can see it's identical to the high res layer of the pyramid.

**Comment by jcupitt** [comment]
> re libvips: if the pixels change on recompressing on save, would it affect the image quality when used in deep learning pipeline?

Thinking again, I've used libvips to prepare numpy arrays directly for training, so then there's no save/load needed. It depends what kind of network you're trying to train, of course.

**Comment by andanison** [comment]
@jcupitt tiffsplit was useful and worked for my task. 
Thank you very much for your help!!
