### ISSUE TITLE
pyvips.Image.new_from_file fail

### ISSUE THREAD

**Issue by donghuikugou** [libvips/pyvips#379]
import pyvips
image = pyvips.Image.new_from_file("example.png")

(process:34105): GLib-CRITICAL **: 15:00:48.216: g_datalist_id_set_data_full: assertion 'key_id > 0' failed

(process:34105): GLib-GObject-CRITICAL **: 15:00:48.216: g_param_spec_pool_lookup: assertion 'pool != NULL' failed

(process:34105): GLib-GObject-WARNING **: 15:00:48.216: g_object_set_is_valid_property: object class '(NULL)' has no property named 'filename'

**Comment by jcupitt** [comment]
Hello,

This sounds like an install problem. So ... what platform, what libvips version, how did you install it, did you see the install guide, etc.
