### ISSUE TITLE
Image.new_from_file fails: parameter filename not set

### ISSUE THREAD

**Issue by DSLituiev** [libvips/pyvips#38]
I have installed pyvips on Mac by first compiling/installing VIPS from source and then PYVIPS with pip.
Initial module load is successful:
```
Python 3.6.4 |Anaconda, Inc.| (default, Dec 21 2017, 15:39:08)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import logging
   ...: logging.basicConfig(level = logging.DEBUG)
   ...: import pyvips
   ...:
DEBUG:pyvips:Loaded binary module _libvips
DEBUG:pyvips:Inited libvips
DEBUG:pyvips:
```

However when I try to load a JPEG or TIFF image I am getting:

```
In [2]: fn = "./whatever.jpeg"

In [3]: image = pyvips.Image.new_from_file(fn, access='sequential', filename=fn)
DEBUG:pyvips.voperation:VipsOperation.call: operation_name = VipsForeignLoadJpegFile
DEBUG:pyvips.voperation:VipsOperation.call: string_options =
DEBUG:pyvips.voperation:VipsOperation.call: match_image = None
DEBUG:pyvips.vobject:VipsObject.set: name = filename, value = ./whatever.jpeg

(process:99721): GLib-CRITICAL **: g_datalist_id_set_data_full: assertion 'key_id > 0' failed

(process:99721): GLib-GObject-CRITICAL **: g_param_spec_pool_lookup: assertion 'pool != NULL' failed

(process:99721): GLib-GObject-WARNING **: g_object_set_is_valid_property: object class '(null)' has no property named 'filename'
DEBUG:pyvips.vobject:VipsObject.set: name = access, value = sequential

(process:99721): GLib-CRITICAL **: g_datalist_id_set_data_full: assertion 'key_id > 0' failed

(process:99721): GLib-GObject-CRITICAL **: g_param_spec_pool_lookup: assertion 'pool != NULL' failed

(process:99721): GLib-GObject-WARNING **: g_object_set_is_valid_property: object class '(null)' has no property named 'access'
DEBUG:pyvips.vobject:VipsObject.set: name = filename, value = ./whatever.jpeg

(process:99721): GLib-CRITICAL **: g_datalist_id_set_data_full: assertion 'key_id > 0' failed

(process:99721): GLib-GObject-CRITICAL **: g_param_spec_pool_lookup: assertion 'pool != NULL' failed

(process:99721): GLib-GObject-WARNING **: g_object_set_is_valid_property: object class '(null)' has no property named 'filename'
DEBUG:pyvips.error:Error unable to call VipsForeignLoadJpegFile jpegload: parameter filename not set

---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
<ipython-input-3-5d3ba5f3eef3> in <module>()
----> 1 image = pyvips.Image.new_from_file(fn, access='sequential', filename=fn)

/Applications/anaconda3/envs/kidney/lib/python3.6/site-packages/pyvips/vimage.py in new_from_file(vips_filename, **kwargs)
    214                                      string_options=_to_string(
    215                                          ffi.string(options)
--> 216                                      ), **kwargs)
    217
    218     @staticmethod

/Applications/anaconda3/envs/kidney/lib/python3.6/site-packages/pyvips/voperation.py in call(operation_name, *args, **kwargs)
    186         vop = vips_lib.vips_cache_operation_build(op.pointer)
    187         if vop == ffi.NULL:
--> 188             raise Error('unable to call {0}'.format(operation_name))
    189         op = Operation(vop)
    190

Error: unable to call VipsForeignLoadJpegFile
  jpegload: parameter filename not set
```

Any idea what's wrong here?

**Comment by jcupitt** [comment]
Sorry, I don't know :( You could try running in a debugger and stopping on the first critical from glib.

I use it on macOS with vips from homebrew, then `pip install pyvips` and it works well with Apple's Python and with py3 from homebrew. Anaconda have their own package manager unfortunately and there is no libvips package. I've had a go at making one for bioconda, but not had time to finish it.

**Comment by DSLituiev** [comment]
>You could try running in a debugger and stopping on the first critical from glib.

Which debugging commands would you recommend to use?

> Anaconda have their own package manager unfortunately and there is no libvips package. I've had a go at making one for bioconda, but not had time to finish it.

Well, I also first installed vips with brew and then did `pip`. I am NOT installing it with conda.
As `brew` distribution did not bind to the earlier installed openslide, I had to recompile everything. It still seems to be installed alongside with hand-compiled one. How can I see which one the `pyvips` is using?

**Comment by jcupitt** [comment]
I don't think you can mix anaconda and brew -- things will get horribly confused. You need a special vips package for anaconda, which sadly does not exist yet.

I would use brew with either Apple's Python, or the Python from homebrew itself.

My mac is a bit sick at the moment so I can't double-check :( I might be able to get it working later today.

**Comment by DSLituiev** [comment]
Why so? To my understanding `brew` installs VIPS to the system and `pip` installs it within the anaconda environment. Does VIPS installation per se modifies something in python / puts something in python local package repositories?

**Comment by jcupitt** [comment]
Brew will install stuff to /usr/local, but Anaconda won't load anything from there (I think?), and things like libjpeg, which libvips will try to load, will also exist within Anaconda's own binary area, and in the Apple one too. You'll get the wrong versions of almost every library :( 

I think I would install the brew Python and try using pyvips from that. If that works, you'll know the problem in something to do with the way anaconda is doing things.

libvips is already packaged for homebrew, fink and macports, and now it looks like there will have to be an anaconda package as well. I wish Apple had a packaging standard everyone used :( having to maintain four packages on a single platform is an awful waste of time.
