### ISSUE TITLE
pango_layout_set_spacing set spacing fail

### ISSUE THREAD

**Issue by donghuikugou** [libvips/pyvips#382]
https://docs.gtk.org/Pango/method.Layout.set_spacing.html

Sets the amount of spacing in Pango units between the lines of the layout.

When placing lines with spacing, Pango arranges things so that

line2.top = line1.bottom + spacing
Copy
The default value is 0.

Note: Since 1.44, Pango is using the line height (as determined by the font) for placing lines when the line spacing factor is set to a non-zero value with [pango_layout_set_line_spacing()](https://docs.gtk.org/Pango/method.Layout.set_line_spacing.html). In that case, the spacing set with this function is ignored.

Note: for semantics that are closer to the CSS line-height property, see [pango_attr_line_height_new()](https://docs.gtk.org/Pango/func.attr_line_height_new.html).

**Comment by jcupitt** [comment]
Yes, I understand, this feature has been added. 

https://github.com/libvips/libvips/issues/3335

```
 $ vips text x.png 'hello^Mworld' --spacing -30 --dpi 300
```

Makes:

![x](https://user-images.githubusercontent.com/580843/219324304-ae7f5319-e565-4939-9ca9-d6673edca68a.png)

It will be in the next release of libvips, or you can build git master yourself.

**Comment by donghuikugou** [comment]
Thank you!
