### ISSUE TITLE
How to fetch patch from stitched deep zoom?

### ISSUE THREAD

**Issue by ccjjww** [libvips/pyvips#387]
Hi, I am not familiar with pyvips and need your help. I want to select slide window patches from deep zoom type WSI to analyze. Thus, I construct a `Preprocess` Class. There are two functions in this class as follows. The `_stitch_patches()` is called in `__init__()` to get the stitched WSI `self.wsi` and `_get_single_patch` fetches the needed patch according to offset.
```python
def _stitch_patches(self):
    coord = np.array([i.strip('.jpg').split('_') for i in os.listdir(self.last_layer_path)], dtype=np.int16)
    max_w, max_h = np.max(coord,0)
    tiles = [pyvips.Image.new_from_file(f"{self.last_layer_path}/{x}_{y}.jpg", access="sequential")
            for y in range(max_h+1) for x in range(max_w+1)] 
    image = pyvips.Image.arrayjoin(tiles, across=max_w+1)
    return image
```
```python
def _get_single_patch(self, offset):
    reg = pyvips.Region.new(self.wsi)
    data = reg.fetch(offset[0], offset[1], self.input_size[1], self.input_size[0])
    patch = np.ndarray(buffer=data, dtype=np.uint8, shape=self.input_size+[3])
    return patch, offset
```
Error in line `data = reg.fetch(offset[0], offset[1], self.input_size[1], self.input_size[0])` is 
```
pyvips.error.Error: unable to fetch from region
  VipsJpeg: out of order read at line 1024
```

I'm sure that the offset is not out of the boundary. 
`offset` is `array([  384, 10368])`, 
`self.wsi` is `<pyvips.Image 32768x36864 uchar, 3 bands, srgb>`, 
`self.input_size` is `[512, 512]`. 
Besides, the `_stitch_patches()` consumes very little time in the initialization process, this is also confusing. I doubt that the WSI is really stitched completely.
Could you help me solve this problem?
Thank you.

**Comment by jcupitt** [comment]
Hi @ccjjww,

```
    tiles = [pyvips.Image.new_from_file(f"{self.last_layer_path}/{x}_{y}.jpg", access="sequential")
```

Try removing the `access="sequential"`. You need random access to pixels, so you won't be able to stream images. pyvips will need to decode your tiles into memory, so you may see high memory use.

As an alternative, you could stream and stitch to a file (eg. tiled jpeg tiff is very fast), then read patches from that. Memory use would then be low, but you'd need quite a bit of disc space.

Are you fetching 512x512 patches? You'll probably find that plain `crop` is faster. Fetch is only faster for very small things, eg. 32x32.

Try:

```python
def _get_single_patch(self, offset):
    patch = self.wsi.crop(offset[0], offset[1], self.input_size[1], self.input_size[0])
    return patch.numpy(), offset
```

> Besides, the _stitch_patches() consumes very little time in the initialization process, this is also confusing. I doubt that the WSI is really stitched completely.

Yes, pyvips is a "lazy" image processing library: computation only happens on demand. It hasn't stitched it, it's just built an image processing pipeline which will stitch it in sections when you ask for pixels.

**Comment by ccjjww** [comment]
Thank you for your advice. The `access="sequential"` method works, but it's too slow in my situation. I guess many tiles in deep zoom is read repeatedly for the mismatch between the step size and tile size. At last, I decided to load the total WSI into memory by `image.write_to_memory()` and then convert it to numpy array to avoid writing in disk (the memory is enough). At last, I want to know what's the difference between `Image.extract_area` and `Image.crop`? Thanks.
