### ISSUE TITLE
Entry Point Not Found Exceptions When Running Python Script Via Batch File (Windows)

### ISSUE THREAD

**Issue by TheHuessy** [libvips/pyvips#390]
Trying to run a batch script that calls an `argparse` based python script. When the python script tries to load a local class that calls `import pyvips` I get multiple "Entry Point Not Found" errors. This only happens when I call `pyvips` indirectly in this manner. If I open up a python shell in the command line (in the same environment I'm executing the batfile from) and use `pyvips` it's happy.

I've seen some other people have similar issues (#44) but none of the solutions have worked for me thus far. I have a sneaking suspicion that I'm forgetting something about running python from a batch script and venvs, but I'm relatively certain it's executing the python script using the correct venv. My other thought that it might be a version mismatch between pyvips and the underlying extracted libvips, but that also may not be it. 

Any help/direction would be greatly appreciated.

### Details

bat example:
```
@ECHO OFF

D:\vpy\Scripts\activate && python radiation_cli.py --image_id="<image_id>" --analysis_job_id="<analysis_id>" --pk="<pk_value>" --dest_email="<email>" --bat_script_name="THIS ONE TESTING" --rad_type="Tumor"
```

radiation_cli.py beginning:

``` 
...
from rad_image_base import RadAnalysis
...
```

rad_image_base.py:

```
import cv2
import os
import numpy as np
import pandas as pd

import skimage.io as skio

os.environ['PATH'] = os.environ['VIPS_HOME'] + ';' + os.environ['PATH']

import pyvips
...
```

Result of execution in cmd line:

First a slew of popups:

<img width="245" alt="vips_exception1" src="https://user-images.githubusercontent.com/43474783/221967280-55164563-66b5-49ba-b459-239c657a4e33.PNG">
<img width="245" alt="vips_exception2" src="https://user-images.githubusercontent.com/43474783/221967282-7389477e-4a2e-4f80-858d-35f93b23532d.PNG">
<img width="244" alt="vips_exception3" src="https://user-images.githubusercontent.com/43474783/221967283-26eb2484-6cd3-49af-b40c-ae28286c8198.PNG">
<img width="243" alt="vips_exception4" src="https://user-images.githubusercontent.com/43474783/221967285-211c9f64-b022-4bdc-be84-3a03dabd591c.PNG">
<img width="248" alt="vips_exception5" src="https://user-images.githubusercontent.com/43474783/221967286-dccb91a3-09c2-4386-819c-f4741def423f.PNG">
<img width="244" alt="vips_exception6" src="https://user-images.githubusercontent.com/43474783/221967287-fcabafdc-3d1d-48a2-9a71-4e21428cfcf1.PNG">

Then it fails on the command line after I hit 'ok' on all the popups

```
Traceback (most recent call last):
  File "D:\vpy\Lib\site-packages\pyvips\__init__.py", line 19, in <module>
    import _libvips
ModuleNotFoundError: No module named '_libvips'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\repos\algo_app\static\python\radiation_imaging\radiation_cli.py", line 31, in <module>
    from rad_image_base import RadAnalysis
  File "D:\repos\algo_app\static\python\radiation_imaging\rad_image_base.py", line 13, in <module>
    import pyvips
  File "D:\vpy\Lib\site-packages\pyvips\__init__.py", line 71, in <module>
    vips_lib = ffi.dlopen(_vips_libname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\vpy\Lib\site-packages\cffi\api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\vpy\Lib\site-packages\cffi\api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\vpy\Lib\site-packages\cffi\api.py", line 828, in _load_backend_lib
    return backend.load_library(path, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: cannot load library 'D:\extended_path\vips-dev-8.14\bin\libvips-42.dll': error 0x7f
```

`vips` output from command line:
```
>vips
Usage:
  vips [OPTIONâ?▌] [ACTION] [OPTIONS] [PARAMETERS] - VIPS driver program

Help Options:
  -h, --help                     Show help options

Application Options:
  -l, --list=BASE-NAME           list objects
  -p, --plugin=PLUGIN            load PLUGIN
  -v, --version                  print version
  -c, --completion=BASE-NAME     print completions
  --vips-concurrency=N           evaluate with N concurrent threads
  --vips-progress                show progress feedback
  --vips-leak                    leak-check on exit
  --vips-profile                 profile and dump timing on exit
  --vips-disc-threshold=N        images larger than N are decompressed to disc
  --vips-novector                disable vectorised versions of operations
  --vips-cache-max=N             cache at most N operations
  --vips-cache-max-memory=N      cache at most N bytes in memory
  --vips-cache-max-files=N       allow at most N open files
  --vips-cache-trace             trace operation cache
  --vips-cache-dump              dump operation cache on exit
  --vips-version                 print libvips version
  --vips-config                  print libvips config
  --vips-pipe-read-limit         read at most this many bytes from a pipe
```

OS: Windows Server 2016 64bit
Python Version: 3.11
`pyvips` Version: 2.2.1
`libvips` Version: 8.14

**Comment by jcupitt** [comment]
Hi @TheHuessy,

I find Windows a bit mysterious :( So I'm not sure I can help much. 

Just a guess, but perhaps you are seeing DLL conflict? You are depending on a lot of packages and I bet glib and expat are used by more than one of them. If a package that pulls in expat (for example) comes before pyvips, and the expat DLL it loads is older than the one libvips is expecting, I think you could see missing link point errors.

I would try making a test program that **only** used pyvips and check that worked in this context. If it does, then start adding your earlier `imports` back again until it breaks. That should tell you which package is loading an incompatible DLL and needs updating.

**Comment by TheHuessy** [comment]
Hi @jcupitt,

Thanks for the response, you really validated my frustrations :). I was able to get it all to run without throwing the dll exceptions by importing `pyvips` in the CLI file as well as in the file with the class definition that actually uses `pyvips`. It doesn't make much sense to me, but for those that were also utilizing my needlessly elaborate pipeline, here's what fixed it for me.

So, the execution structure is this:

```
Flask app generates .bat file based on inputs
    |_ .bat file is executed via popen()
         |_ .bat file calls CLI-like python file with argparse arguments
             |_ CLI file calls the RadiationAnalysis class defined in a local file (no pyvips import, but openslide import)
                 |_ RadiationAnalysis class generates an image and saves it out via pyvips  (pyvips is imported and used in this file)
```

I think the issue was, as you suggested, another library using the dlls that `pyvips` was going to load. I narrowed it down to `openslide`, which was only called/used in the CLI file, and not in the RadiationAnalysis class file. Additionally, being on python 3.11 [forced me to add the dll folder path](https://openslide.org/api/python/#installing) for `openslide` instead of just calling `import openslide`. What made it all work was importing `pyvips` in BOTH the RadiationAnlaysis class file and the CLI file that calls that class. 

### CLI File
```
import argparse
import os
import pyvips ## NEW, doesn't get used in this script
import sys

from datetime import datetime

## Needed for >=Python 3.8 on windows... it's silly
OPENSLIDE_PATH = r'D:\extended_path\openslide-win64-20221111\bin'
with os.add_dll_directory(OPENSLIDE_PATH):
    import openslide

from rad_image_base import RadAnalysis  ## The RadiationAnalysis class file
```

### RadiationAnalysis Class File
```
import cv2
import os
import numpy as np
import pandas as pd
import pyvips

import skimage.io as skio

class RadAnalysis:
    ...
```

I guess the answer was that since I was calling opensilde before pyvips in the CLI file, it carried that environment down to the `RadAnalysis` object when it tried to run the method that uses `pyvips`, which I did not think would happen. Not sure if that's a Windows thing or a general rule of python programming that I was woefully unaware of. Seems a bit silly to have to import a library just to ensure dlls don't get conflicted in a script that I don't even use it in, but, like you said, Windows is mysterious.

Thanks for the help!

**Comment by jcupitt** [comment]
Ah OK, libvips includes openslide, so you have it loaded twice, probably built against different versions of glib and expat.

Linux-like systems have curated sets of libraries that are built together (generally), but win is much more free-for-all and unless you're very careful it's easy to get different versions of the same library in the same program, sometimes causing intense confusion.
