### ISSUE TITLE
PNG compression

### ISSUE THREAD

**Issue by hdpz** [libvips/pyvips#393]
Set up: ubuntu 20, python 3.10, pyvips 2.2.1 installed with conda forge

I am comparing pyvips with pillow on a few use cases, one of them being writing to a buffer the image in png format.

I ran the following code with compression level set to 1 & 9 respectively on a few images (all rather large images) and the resulting pngs from vips are always much larger than their pillow equivalent and the file size does not decrease when increasing compression level with vips (sometimes it is even bigger :cry: ). I looked at the options available using vips pngsave_buffer but did not see an obvious parameter to play with to fix this. 
![image](https://user-images.githubusercontent.com/35563196/224352132-c3a40496-0a05-4654-9a9f-8b88060f56c8.png)

Performance for compression level 9: 
- Pillow image encoding took 9713.59 ms
- Vips image encoding took 693.47 ms (at least its much faster at this compression level)

Performance for compression level 1:
- Pillow image encoding took 498.25 ms
- Vips image encoding took 479.26 ms

```python
import pyvips
from PIL import Image as ImageModule
import time
import io

pillow_image = ImageModule.open('./input.jpg')
vips_image = pyvips.Image.new_from_array(pillow_image)
compress_level = 1

start = time.perf_counter()
buf = io.BytesIO()
pillow_image.save(buf, 'PNG', compress_level=compress_level)
buf.seek(0)
end = time.perf_counter()
print(f'Pillow image encoding took {(end-start)*1000 } ms')
with open(f'./results/pillow-compression-{compress_level}.png', 'wb') as f:
    f.write(buf.read())


start = time.perf_counter()
data = vips_image.write_to_buffer('.png', compression=compress_level)
end = time.perf_counter()
print(f'Vips image encoding took {(end-start)*1000 } ms')
with open(f'./results/vips-compression-{compress_level}.png', 'wb') as f:
    f.write(data)
```

Here is one of the input images to reproduce: 
![input](https://user-images.githubusercontent.com/35563196/224353646-b88f7e9d-39a1-4503-b26a-bfd8caa3418a.jpg)

Thanks!

**Comment by jcupitt** [comment]
An interesting change is to make it do copy rather just encode. For example:

```python
#!/usr/bin/python3

import time
import io
import sys

from PIL import Image as ImageModule
import pyvips

compress_level = 1

buf = io.BytesIO()

start = time.perf_counter()
pillow_image = ImageModule.open(sys.argv[1])
pillow_image.save(buf, 'PNG', compress_level=compress_level)
end = time.perf_counter()

print(f'Pillow image copy took {(end-start)*1000:.1f} ms')
print(f'image size {buf.tell()} bytes')


NONE = 0x08
SUB = 0x10
UP = 0x20
AVG = 0x40
PAETH = 0x80
ALL = 0xF8

start = time.perf_counter()
vips_image = pyvips.Image.new_from_file(sys.argv[1], access="sequential")
data = vips_image.write_to_buffer('.png', 
                                  compression=compress_level,
                                  filter=ALL)
end = time.perf_counter()

print(f'Vips image copy took {(end-start)*1000:.1f} ms')
print(f'image size {len(data)} bytes')
```

Now it's timing read file + write file, and the `access="sequential"` for libvips load enables streaming mode.

I see:

```
$ vips copy ~/pics/input.jpg x.png
$ ./copy.py x.png
Pillow image copy took 768.8 ms
image size 12843165 bytes
Vips image copy took 634.1 ms
image size 12856394 bytes
```

libvips can execute the PNG load in parallel with the PNG save, so it's maybe 100 ms quicker than pillow.

**Comment by hdpz** [comment]
Thanks @jcupitt for taking the time to clarify the observed discrepancies :+1:
