### ISSUE TITLE
Your latest windows binaries seems has no support of dzsave 8.14.2

### ISSUE THREAD

**Issue by inloveable** [libvips/pyvips#398]
I tried to download an older version,which is 8.14.1,clealy has the support. please check your latest binary.

**Comment by jcupitt** [comment]
Hi @inloveable, yes I see this too. I'll investigate.

**Comment by inloveable** [comment]
Thank you for your reply

**Comment by jcupitt** [comment]
Sorry, I'd forgotten, it's deliberate:

https://github.com/libvips/libvips/issues/3354

We've discovered a licencing issue and we've had to remove the zip library we were using for dzsave. We hope to replace it with something else soon.

In the meantime, you can either build libvips yourself, or keep using an older version.
