### ISSUE TITLE
tiffsave large image saving memory problems

### ISSUE THREAD

**Issue by cihankayacihan** [libvips/pyvips#400]
Hi, 

First of all, thank you for such amazing library. I am working with large WS images using pyvips. I extract and apply icc profile to images and save it as bigtiffs. I am having (presumably memory) errors when I am using tiffsave. I am using the following command 

`tile = 256. 
im.cast("uchar")[0:3].tiffsave('xx.tif', properties=False, compression="jpeg", tile=True, tile_width=int(tile), tile_height=int(tile), bigtiff=True, pyramid=True, subifd=True). `

I change the tile variable depending on scanner but I am getting the following error. 
`pyvips.error.Error: unable to call tiffsave
  TIFFAppendToStrip: Write error at scanline 12799
vips2tiff: TIFF write tile failed\n
wbuffer_write: write failed\n
unix error: Unknown error -1`

My images are about 750 MB to 2 GB and array size is generally around 100kx150k. If I provide about 75-90 GB memory it works fine but if I limit or run anything concurrently it is throwing the same error. Is there any parameter or something else to make this writing process in smaller batches and make a final concat function. Thanks a lot.

**Comment by jcupitt** [comment]
Hi @cihankayacihan, it should work fine, and only need a little memory. It sounds like something has gone badly wrong.

You need to post a complete, runnable program that reproduces the problem.

**Comment by cihankayacihan** [comment]
Hi @jcupitt, Thanks for prompt response. I tested it and it does not look like a memory problem. I am using a cluster and i can run everything on the head node with 90GB of memory. When I went to worker nodes, I have 180 GB of memory and it is still throwing the same error. Here is the program, I am running. 

`
import sys
import os

import pyvips
import tifffile

img_file_path = sys.argv[1]
profile = sys.argv[2]
tile = sys.argv[3]

in_img = pyvips.Image.new_from_file(img_file_path, access='sequential')
im = in_img.icc_transform("srgb", input_profile=profile)
if im.hasalpha():
    im=im[:-1]
im.cast("uchar").tiffsave('x.tif', properties=False, compression="jpeg", tile=True, tile_width=int(tile), tile_height=int(tile), bigtiff=True, pyramid=True, subifd=True)
`

Somehow my code looks weird in preview.

**Comment by jcupitt** [comment]
What kind of source image are you using?

**Comment by jcupitt** [comment]
I see:

```
$ vipsheader test.svs 
test.svs: 211213x87581 uchar, 4 bands, srgb, openslideload
$ /usr/bin/time -f %M:%e vips icc_transform test.svs x.tif[compression=jpeg,tile,pyramid] --input-profile huge.icc srgb
2044172:143.86
```

So 2gb of memory and 143s of real time. 

`huge.svs` is the crazy 13mb profile Leica are using at the moment.

**Comment by jcupitt** [comment]
For code in comments, use eg.:

```
    ```python
    print("hello!")
    ```
```

To render as:

```python
print("hello!")
```

**Comment by jcupitt** [comment]
Huh weird. Sorry, I don't know what's wrong. Can you share a sample SVS that fails for you?

I personally wouldn't use anaconda on linux -- it's not really necessary, and the packages they ship are not as well tested as the standard distro package set. You'd be better off (probably) with just `apt install libvips-dev` or whatever.

**Comment by cihankayacihan** [comment]
Let me see if I can deidentify the image. I use pyvips since I am running multiple operations before I save for some product lines. But on the basic end, it is just read and write with icc profile application. 
I have a simple cluster setup with 1 head and 2 worker nodes. Interestingly, it only fails on one of the workers. It looks like the issue is on my end with something wrong about the cluster. Can you keep this open so that if I have anything new, I will keep sharing?

**Comment by cihankayacihan** [comment]
For a 955 MB file, it is generally running around 10-15 minutes. Is this normal or is there a way to speed it up?

**Comment by jcupitt** [comment]
> For a 955 MB file, it is generally running around 10-15 minutes. Is this normal or is there a way to speed it up?

It depends how many cores you have. If I turn off threading I see:

```
$ VIPS_CONCURRENCY=1 /usr/bin/time -f %M:%e vips icc_transform test.svs x.tif[compression=jpeg,tile,pyramid,subifd] --input-profile huge.icc srgb
1026476:860.94
```

860s is about 15m for a 2.2gb SVS file with 1 CPU. This is a threadripper workstation.

**Comment by cihankayacihan** [comment]
Conda vips is easier to deal with as a regular user. I am trying to get a hold of sys admin to install platform version. What is the suggested library for Centos 7?

**Comment by jcupitt** [comment]
Wow, centos 7 is almost 10 years old now, the platform libvips will not be very useful.

You could use docker and then run something like a recent Debian in that, if your sysadmin allows it. Would that be possible?

**Comment by jcupitt** [comment]
Ah I remembered another solution: 

https://rpms.remirepo.net/

Remi maintains a set of RPMs for libvips for centos7. They are very widely used and seem to work well.

**Comment by cihankayacihan** [comment]
May be this is the right time for us to update our system to something newer. Let me see if we can build from source.

**Comment by jcupitt** [comment]
You'll probably have to build a great many libraries to make a working binary. I think docker, or remi's repo, would be easier.

**Comment by cihankayacihan** [comment]
We will upgrade our os to a debian system and try again.

**Comment by jcupitt** [comment]
I would try remi's repo first, I think. It should work, and would be much simpler than updating your OS.

**Comment by cihankayacihan** [comment]
Hi it has been a while since my last response. We restarted the compute node causing the issue and it works fine now.

**Comment by jcupitt** [comment]
Ah, that's good to hear. I'll close.

**Comment by cihankayacihan** [comment]
Before you close, I would like to add a little more context. The reason is not because of an architecture or specific problem to the node. The TMPDIR was default and it was out of space. That is why it was keep throwing this error. Since I am running a large scale operation our preset 2 GB space was not enough. After specifying the TMPDIR, it is working fine.

**Comment by jcupitt** [comment]
Ah, good tip, thanks for the update.
