### ISSUE TITLE
generate tiff and dzi slowly

### ISSUE THREAD

**Issue by chengdonglin** [libvips/pyvips#412]
I have install lbjpeg-turbo,see below,But I find it slowly compare win
![image](https://github.com/libvips/pyvips/assets/28192795/c0d5b0ff-d63d-424c-bcd4-7f1437209a2a)

next my generate tiff and dzi code 

```
 im = pyvips.Image.arrayjoin(tiles, across=int(across) + 1)
 im.write_to_file(os.path.join(tiff_path, tiff_file_name), compression='jpeg', Q=85, tile=True, pyramid=True)
 image = pyvips.Image.new_from_file(os.path.join(tiff_path, tiff_file_name))
        image.dzsave(dzi_path, tile_size=512)
```

**Comment by chengdonglin** [comment]
my tiles number ![image](https://github.com/libvips/pyvips/assets/28192795/cbec062c-d29e-4281-9d1f-ca9f5b29f985)

and each tile-size 5096 * 5096

**Comment by jcupitt** [comment]
I tried this test program:

```python
#!/usr/bin/env python

import os
vipshome = 'f:\\vips-dev-8.14\\bin'
os.environ['PATH'] = vipshome + ';' + os.environ['PATH']

import pyvips

# make test data with:
#
#   vips crop ~/pics/st-francis.jpg tile.jpg 0 0 5096 5096
#   for x in {0..13}; do
#     for y in {0..12}; do
#       cp ../tile.jpg ${x}_${y}.jpeg
#     done
#   done

across = 14
down = 13

tiles = [pyvips.Image.new_from_file(f"{x}_{y}.jpeg", access="sequential")
         for x in range(across) for y in range(down)]

image = pyvips.Image.arrayjoin(tiles, across=across)

print(f"saving {image.width}x{image.height} pixel DZI pyramid ...")
image.dzsave("x", tile_size=512)
```

On Linux I see:

```
$ vips --version
vips-8.14.3
$ time ../cheng.py 
saving 71344x66248 pixel DZI pyramid ...

real	0m18.038s
user	1m43.778s
sys	1m0.006s
```

Inside a Windows VM on the same hardware (same disc, same CPU, etc.) I see:

```
jcupi@DESKTOP-HGI6HBR MINGW64 ~/try/sample
$ time ../cheng.py
saving 71344x66248 pixel DZI pyramid ...

real    0m51.581s
user    0m0.000s
sys     0m0.030s
```

So linux is about 3x faster. 

Most of this is the speed of the filesystem -- windows is extremely slow at creating files. If I change the program to be:

```python
image.dzsave("x", container="zip", tile_size=512)
```

On windows I now see:

```
jcupi@DESKTOP-HGI6HBR MINGW64 ~/try/sample
$ time ../cheng.py
saving 71344x66248 pixel DZI pyramid ...

real    0m27.672s
user    0m0.061s
sys     0m0.030s
```

Almost twice as quick, since it's not creating all the tiles as separate files.

Summary:

1. On the same hardware and the same libvips version, linux might  be roughly 3x faster than windows at this task.
2. Most of the difference is in the slow Windows filesystem. If you write zip files rather than large directory trees, Windows is closer.
3. You will see speed differences between libvips versions. Perhaps you are using a very old libvips on linux?
4. If you are building libvips yourself, things like optimiser settings can make a 2x speed difference.
5. Differences in CPU and disc hardware will also change execution speed.
6. Virus scanner settings and short filename generation can make a large difference on Windows.

**Comment by jcupitt** [comment]
If I let vips uses more than one thread:

```
$ time ../cheng.py 
saving 71344x66248 pixel DZI pyramid ...

real	0m18.209s
user	1m42.193s
sys	1m2.207s
```

It gets about 3x faster.

This PC is also AMD:

```
$ more /proc/cpuinfo
processor	: 0
vendor_id	: AuthenticAMD
cpu family	: 23
model		: 49
model name	: AMD Ryzen Threadripper PRO 3955WX 16-Cores
stepping	: 0
microcode	: 0x8301055
cpu MHz		: 2195.748
cache size	: 512 KB
...
```

**Comment by chengdonglin** [comment]
> If I let vips uses more than one thread:
> 
> ```
> $ time ../cheng.py 
> saving 71344x66248 pixel DZI pyramid ...
> 
> real	0m18.209s
> user	1m42.193s
> sys	1m2.207s
> ```
> 
> It gets about 3x faster.
> 
> This PC is also AMD:
> 
> ```
> $ more /proc/cpuinfo
> processor	: 0
> vendor_id	: AuthenticAMD
> cpu family	: 23
> model		: 49
> model name	: AMD Ryzen Threadripper PRO 3955WX 16-Cores
> stepping	: 0
> microcode	: 0x8301055
> cpu MHz		: 2195.748
> cache size	: 512 KB
> ...
> ```

I see, it is fast, this work as expected, So what puzzles me is that my code generate tiff so slowly,here is my full code

```
import os
import time
import pyvips
def generate_tiff(path, across, down, md5, task_ID):
    try:
        tiles = [pyvips.Image.new_from_file(f"{path}/tiles/{x}_{y}.jpeg", access="sequential")
                 for y in range(int(down) + 1) for x in range(int(across) + 1)]
        im = pyvips.Image.arrayjoin(tiles, across=int(across) + 1)
        paths = path.split("tiles")
        tiff_path = paths[0]
        tiff_file_name = f'{md5}.tiff'
        tiff_start = get_time_stamp()
        im.write_to_file(os.path.join(tiff_path, tiff_file_name), compression='jpeg', Q=85, tile=True, pyramid=True)
        tiff_end = get_time_stamp()
        dzi_path = os.path.join(tiff_path, "deepzoom")
        if os.path.exists(dzi_path + "_files"):
            os.remove(dzi_path)
        dzi_start = get_time_stamp()
        image = pyvips.Image.new_from_file(os.path.join(tiff_path, tiff_file_name))
        image.dzsave(dzi_path, tile_size=512)
        dzi_end = get_time_stamp()
    except Exception as  e:
        print(e)
```

in linux, I not include like next code
```
vipshome = 'f:\\vips-dev-8.14\\bin'
os.environ['PATH'] = vipshome + ';' + os.environ['PATH']
```

**Comment by jcupitt** [comment]
You don't need to save as tiff first, you can just save directly as DZI.

**Comment by jcupitt** [comment]
... perhaps you have a very old version of libvips on your linux server?

**Comment by chengdonglin** [comment]
> ... perhaps you have a very old version of libvips on your linux server?
the version is 8.14.1
![image](https://github.com/libvips/pyvips/assets/28192795/61c9537d-75aa-456a-87a2-30be8ed68147)

**Comment by jcupitt** [comment]
Where did you get this libvips version? Did you build it yourself? If you did, what commands did you run to do the build?

Please don't post screenshots -- I can't copy-paste from them, so I have to retype everything. Instead, copypaste text and enclose in backticks.

**Comment by chengdonglin** [comment]
@jcupitt Thank you very much for your continued attention. I have found the reason. We use azure file sharing storage, and the IO ability is too poor, which leads to this problem.

**Comment by jcupitt** [comment]
Ah! OK, makes sense.

You could try writing to `/tmp` then copying to the final area, `/tmp` is usually very fast, and probably large enough.

You could also try using `container="zip"`, it should put less stress on the filesystem.

**Comment by chengdonglin** [comment]
> container="zip"

I use the linux command to mv the files, also it slowly to write file share system,So I should confirm the azure file share can able to improve the io wrtiting
