### ISSUE TITLE
pyvips tiffsave() getting killed

### ISSUE THREAD

**Issue by Lemba13** [libvips/pyvips#417]
I am trying to construct a pyramidal tiff from tiles of size 256x256,(named according to their coordinates w.r.t the WSI). The tiffsave() gets killed when the number of tiles in the folder is more than 150000.

```python
tiles = [
    pyvips.Image.new_from_file(
        os.path.join(temp_savepath, f"{x}_{y}.png"), access="sequential"
    )
    for y in range(ymin, ymax, tile_size)
    for x in range(xmin, xmax, tile_size)
]

im = pyvips.Image.arrayjoin(tiles, across=int(xmax / tile_size))

im.tiffsave(
    'output.tiff',
    tile=True,
    pyramid=True,
    compression="jpeg",
    Q=85,
    tile_width=256,
    tile_height=256,
    bigtiff=True,
)
```

**Comment by jcupitt** [comment]
Hi @Lemba13, 

Wow, 150,000 is a lot! 

I would guess you're running out of memory. I would assemble the mosaic in sections.

**Comment by Lemba13** [comment]
Can you give me some pointers on how to proceed with that.

**Comment by jcupitt** [comment]
Sure, arrayjoin rows 1-10 into file a.v, then 11-20 into file b.v, then finally arrayjoin all the strips into your output file.

**Comment by Lemba13** [comment]
Thanks for the input, but joining n columns was giving an issue from the 'across' argument in the arrayjoin function  as the last group does not necessary have the same width. Instead I joined single columns individually and and joined those strips later, now the memory issue has been fixed. I think you can close the issue now.
