### ISSUE TITLE
Image description not written if bigtiff=True

### ISSUE THREAD

**Issue by knoppmyth** [libvips/pyvips#419]
Hi All,

Here is a code snippet:
```
image = pyvips.Image.arrayjoin(tiles, across=tiles_across)
image.set_type(pyvips.GValue.gstr_type, 'image-description', tiff_description)
image.write_to_file(tiff_dir + tiff_name, pyramid=True, bigtiff=True, compression="jpeg", tile=True)
```
Running file foo.tiff, if bigtiff is set to True:
```
foo.tiff: Big TIFF image data, little-endian
```
However if set to False:
```
foo.tiff: TIFF image data, little-endian, direntries=19, height=15840, bps=3556, compression=JPEG, PhotometricInterpretation=YCbCr, description=Aperio Fake |AppMag = 40|MPP = 0.2536, orientation=upper-left, width=9840
```
How can I get the description I want if bigtiff is enabled?
libvips 8.14.2-1
pyvips 2.2.1

Please let me know if any other information is needed.

Thanks,

knoppmyth

**Comment by jcupitt** [comment]
Hi @knoppmyth,

I think that's just a limitation of `file`. The version you are using can't read imagedescription from bigtiff files.

Try this program:

```python
#!/usr/bin/env python

import sys
import pyvips

image = pyvips.Image.new_from_file(sys.argv[1])
image = image.copy()
image.set_type(pyvips.GValue.gstr_type, 'image-description', sys.argv[3])
image.write_to_file(sys.argv[2])
```

Then:

```
$ ./set-description.py ~/pics/k2.jpg x.tif "hello world"
$ vipsheader -f image-description x.tif
hello world
$ ./set-description.py ~/pics/k2.jpg x.tif[bigtiff] "hello world"
$ vipsheader -f image-description x.tif
hello world
```

You can verify with `tiffinfo`:

```
$ tiffinfo x.tif
=== TIFF directory 0 ===
TIFF Directory at offset 0x87f010 (8908816)
  Image Width: 1450 Image Length: 2048
  Resolution: 72.009, 72.009 pixels/inch
  Bits/Sample: 8
  Sample Format: unsigned integer
  Compression Scheme: None
  Photometric Interpretation: RGB color
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 3
  Rows/Strip: 128
  Planar Configuration: single image plane
  ImageDescription: hello world
```

**Comment by knoppmyth** [comment]
Hello @jcupitt , just before I read your response, I wonder if this was a file issue and was going to test it independently of file. I'm processing a huge file at the moment and will test it after that is done. Thanks for the response.

**Comment by knoppmyth** [comment]
@jcupitt ,

vipsheader returned:
```memory: high-water mark 0 bytes```
tiffinfo did return the expected description.

Thanks for your help. 

Not sure about the vipsheader issue. If there is any information you need, please let me know. Else we can close this.

**Comment by jcupitt** [comment]
It sounds like you've built libvips in debug mode. I'd set the `--buildtype release` flag with meson, it should be noticeably quicker.

You'd need to give more information about `vipsheader`. What command did you run, exactly?

**Comment by knoppmyth** [comment]
I recompiled but ```vipsheader -f x.tiff``` didn't return anything. I recompiled with debugging and it returned ```memory: high-water mark 0 bytes```. So clearing the Arch package has debugging enabled by default. However, when release is the buildtype, nothing is being returned.

**Comment by jcupitt** [comment]
`-f` means "fetch field", so you need to give a field name. Try `vipsheader -f image-description x.tif`.

Huh strange that arch are distributing a debug build! We've swapped the default to release for 8.15 so hopefully this issue will vanish.

**Comment by jcupitt** [comment]
I opened a bug on arch here: https://bugs.archlinux.org/task/79527

Perhaps I've done it correctly :(

**Comment by knoppmyth** [comment]
Doh! Sorry, I missed "image-description" in the command.

Your example worked to set the description in a JPEG as you outlined. Using vipsheader does show the description. However it doesn't show the description in a tiff I made:
```
image = pyvips.Image.arrayjoin(tiles, across=tiles_across)
image.set_type(pyvips.GValue.gstr_type, 'image-description', tiff_description)
image.write_to_file(tiff_dir + tiff_name, pyramid=True, bigtiff=True, compression="jpeg", tile=True)
```
```
vipsheader -f image-description 4775.tiff 
vipsheader: vips_image_get: field "image-description" not found
```

Where ```tiffinfo``` does!?
```
tiffinfo 4775.tiff 
=== TIFF directory 0 ===
TIFF Directory at offset 0x5018d36e (1343804270)
  Image Width: 113280 Image Length: 92400
  Tile Width: 128 Tile Length: 128
  Resolution: 28.34, 28.34 pixels/cm
  Bits/Sample: 8
  Sample Format: unsigned integer
  Compression Scheme: JPEG
  Photometric Interpretation: YCbCr
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 3
  Planar Configuration: single image plane
  Reference Black/White:
     0:     0   255
     1:   128   255
     2:   128   255
  ImageDescription: Aperio Fake |AppMag = 40|MPP = 0.2536
```

**Comment by jcupitt** [comment]
Huh strange. If you post a complete, runnable program I could try it here. Did you try the program I wrote?

**Comment by jcupitt** [comment]
It needs to be a small, complete, runnable program I can try. I need to have some way to reproduce the problem you are seeing.

**Comment by jcupitt** [comment]
I thought a bit more and if the program works fine under ubuntu but not under arch, it has to be an arch issue. You should probably ask on the arch forums.

**Comment by knoppmyth** [comment]
To clarify, your sample program works fine under Arch. I can run it, without issue as you prescribed:
```
$ ./set-description.py ~/pics/k2.jpg x.tif "hello world"
$ vipsheader -f image-description x.tif
hello world
$ ./set-description.py ~/pics/k2.jpg x.tif[bigtiff] "hello world"
$ vipsheader -f image-description x.tif
hello world
```

However, the issue I'm seeing is with ```vipsheader -f image-description x.tif``` where ```x.tif``` is a TIFF I created with my above function.

Or, when you say "program", do you mean "vipsheader" working fine under Ubuntu?

BTW, I'm satisfied with the original issue being resolved.

**Comment by knoppmyth** [comment]
@jcupitt Much thanks for your help with this issue. I took a look at the vipsheader manpage and saw the -a flag. Running it, I saw the field name was "tiff.ImageDescription" and not "image-description". Running ```vipsheader -f tiff.ImageDescription" returned the expected information.

Again, thanks for the pointers and your work on the project.

**Comment by knoppmyth** [comment]
No, I'm not using imagemagick loader or save. I've ran vipsheader -a on a few of the SVS that I have and those too show ```tiff.ImageDescription```.

**Comment by jcupitt** [comment]
Ahhhhhh!

SVS is not TIFF. It's a TIFF-like format that Leica use for microscope slides. It's loaded by `openslideload`. You can't save as SVS, and you can't manipulate `image-description`.

**Comment by knoppmyth** [comment]
I'm new to working with WSI. However, I'm aware SVS isn't TIFF. I'm just trying to find a correlation between an SVS and TIFF both having ``` tiff.ImageDescription```. 

Is ```tiff.ImageDescription``` normal for SVS files?

I'm not attempting to save as SVS. The SVS files I have are from an actual scan. I was just looking at the header information to see what it stated.
