### ISSUE TITLE
Issue with icc_transform and pyramidal images

### ISSUE THREAD

**Issue by VisweshK** [libvips/pyvips#434]
Hi @jcupitt 

First off, thanks for making this package!

I'm working with images where I want to 1) apply a icc transform and 2) save out a pyramidal tif with the icc transform applied. I've attached example code below. When I run this for a single test image I get what I'd expect but when I run the same on a large number of images, some of the layers (lower resolution images) do not have the icc profile applied. 

```
tif = pyvips.Image.new_from_file(.....)
tif = tif.icc_transform(icc_target_path, input_profile=icc_source_path)
tif.tiffsave(....., tile=True, tile_width=..., tile_height=..., pyramid=True)
```

What's going on here and how can I fix it?

**Comment by jcupitt** [comment]
Hi @VisweshK,

It should work (obviously). All the pyramid levels in the TIFF are generated from the same base image, so I think it's not possible for some levels to have it and some not. 

Perhaps your image viewer has a bug? Do you have an example of an image where this has happened?

**Comment by jcupitt** [comment]
(also, what version, what platform, and if you can make a complete and runnable reproducer, that helps a lot)

**Comment by VisweshK** [comment]
Hi @jcupitt, 

I was digging into this further and found that the viewer (QuPath) had a bug / was simply using cached image data. Everything looks good now - thanks for the quick response!
