### ISSUE TITLE
Select interpretation when initializing the image

### ISSUE THREAD

**Issue by Zoulinx** [libvips/pyvips#437]
Can **interpretation** be added to pyvips.Image._new_from_file_(src.path, access='sequential') as in _new_from_array_?

If there's an alternative method, please let me know, and I'll be extremely grateful!

**Comment by jcupitt** [comment]
Hi @Zoulinx,

You can set `interpretation` using `copy()`, for example:

```python
image = pyvips.Image.new_from_file(filename).copy(interpretation="xyz")
```

See:

https://libvips.github.io/pyvips/vimage.html?highlight=copy#pyvips.Image.copy

https://www.libvips.org/API/current/libvips-conversion.html#vips-copy
