### ISSUE TITLE
 VipsOperation: class "pdfload" not found

### ISSUE THREAD

**Issue by GalensGan** [libvips/pyvips#438]
where is the method `pdfload`，my code is `pdf = pyvips.Image.pdfload(pdf_path,"")` but throws error ` VipsOperation: class "pdfload" not found`.

> my pyvips version: 2.2.1

how can I convert pdf file to images?

**Comment by jcupitt** [comment]
Hi @GalensGan,

Your libvips has been built without PDF support. What platform and version are you using? Where did you get the libvips binary?

**Comment by GalensGan** [comment]
@jcupitt Thanks for your advice，I solved this error.

my platform is windows 11 and dowloaded the binary [vips-dev-w64-web-8.15.0-rc2.zip](https://github.com/libvips/build-win64-mxe/releases/download/v8.15.0-rc2/vips-dev-w64-web-8.15.0-rc2.zip) from https://github.com/libvips/build-win64-mxe/releases/tag/v8.15.0-rc2 before，but now, I download the [vips-dev-w64-all-8.15.0-rc2.zip](https://github.com/libvips/build-win64-mxe/releases/download/v8.15.0-rc2/vips-dev-w64-all-8.15.0-rc2.zip), it works well.

Thanks much!
