### ISSUE TITLE
JPEG compression resulted in color error.

### ISSUE THREAD

**Issue by sssixty** [libvips/pyvips#440]
I found that when I compressed an image using JPEG compression with Q factor>=90, the pixel values changed a lot, which led to the color's change.
`# pyvips version = 2.2.1`
`image.tiffsave('result.svs', compression="jpeg", Q=100, pyramid=True)`
And I found that the bad results happened when `Q>=90`. Results were normal when `Q<90`.
Another strange phenomenon is that the bad results only happened when` pyramid=True`. Once I set `pyramid=False`, results would be normal even when Q>=90.
How can I achieve the normal results when `pyramid=True` and `Q=100` with JPEG compression?

Normal result is blue(1296px\*2304px):
![1](https://github.com/libvips/pyvips/assets/34131819/4dd6b5c2-b3c6-4b55-b488-31d916c8a555)
Bad result turns green(1296px\*2304px):
![2](https://github.com/libvips/pyvips/assets/34131819/e860f33f-ecfd-48a5-a787-a089a60dcb27)

**Comment by jcupitt** [comment]
Hello @sssixty,

This was fixed last week with https://github.com/libvips/libvips/commit/04819e16a64dc94a7f069b60993dbb90bccaf2c8

The fix should be in 8.15.1, or you can build from source.
