### ISSUE TITLE
draw_rect fill error

### ISSUE THREAD

**Issue by itfarsh** [libvips/pyvips#465]
![image](https://github.com/libvips/pyvips/assets/31433202/39fa2d98-2b38-4461-a60a-2f1e93baa410)

In the manual there is fill, without fill it works fine, but with it it gives an error:
pyvips.error.Error: draw_rect needs 6 arguments, but 1 given

**Comment by jcupitt** [comment]
Hi @itfarsh, the syntax is eg.:

```
$ python
Python 3.11.6 (main, Oct  8 2023, 05:06:43) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvips
>>> im = pyvips.Image.black(100, 100)
>>> im = im.draw_rect(255, 10, 10, 50, 50, fill=True)
<pyvips.Image 100x100 uchar, 1 bands, multiband>
>>> im.write_to_file("x.png")
>>> 
```

... but the draw operations are very slow. I'd find another solution, if possible. What are you trying to achieve?

**Comment by itfarsh** [comment]
Okay, I realize positional arguments are supposed to be, sorry.
