### ISSUE TITLE
Memory problems/out of order read when reading a particular page of a qptiff file 

### ISSUE THREAD

**Issue by dougwood** [libvips/pyvips#493]
I am having trouble working with a vips image that is read from a single page of a multipage qptiff file (a form of tiff).  Here is a example:

    print(pyvips.__version__)
    vips_image = pyvips.Image.new_from_file(
        r"D:\multipage_multichannel_pyramid.qptiff", page=21
    )
    print(vips_image)
    print(vips_image.max())
    # print(vips_image.avg())
    np_image = vips2numpy(vips_image)

When run this I get:

2.2.3
<pyvips.Image 1800x1800 uchar, 1 bands, b-w>
255.0
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2023.1\plugins\python\helpers\pydev\pydevd.py", line 1546, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2023.1\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\dev\uvim\uvim\base\test_read_page.py", line 47, in <module>
    np_image = vips2numpy(vips_image)
  File "C:\dev\uvim\uvim\base\test_read_page.py", line 34, in vips2numpy
    buffer=vi.write_to_memory(),
  File "C:\Users\Doug\AppData\Local\pypoetry\Cache\virtualenvs\uvim-91tdOcio-py3.9\lib\site-packages\pyvips\vimage.py", line 951, in write_to_memory
    raise Error('unable to write to memory')
pyvips.error.Error: unable to write to memory
  tiff2vips: out of order read -- at line 1800, but line 0 requested

python-BaseException

Process finished with exit code 1

Which suggests that the vips 2.2.3 image was created successfully from page 21 and it is of modest size (1800x1800) of uchars with max value of 255 (not sure why it is printed as a float when it should be uchar, however).

But when I try to call vips2numpy or even uncomment out call to avg(), I get the write_to_memory error above.

If I call the avg() function _instead_ of max() I get a value of 5.15809475308642 which is probably correct, but I cant call **both** max() and avg().  Weird

Here is a link to the example image:
https://www.dropbox.com/scl/fi/5n4am40hlldjhwdv7ydxl/multipage_multichannel_pyramid.qptiff?rlkey=w3bt2je02pqbaweidkfeumrkp&st=9qro3p0f&dl=0
which I hope you can download.  let me know if not.

This image displays correctly in QuPath:

![image](https://github.com/user-attachments/assets/f2cc8fc6-8900-47c4-8bff-ed6c3818ebb9)

I am trying to read page 21 because I am trying to create a down-sampled image of one of the channels (DAPI) and page 21 has the DAPI channel image for the level of the pyramid I want to use.

I understand that there could be issues with this specific file, but it does display correctly in QuPath.  

Any help would be very much appreciated.  Thank you!

**Comment by jcupitt** [comment]
Hi @dougwood,

You're right, libvips is opening the image in the wrong mode. Page 0 supports random access, so libvips thinks all pages support random access, but your page 21 is sequential only.

You can work around this by copying the pixels out as soon as you open it. For example:

```
$ python3
Python 3.12.3 (main, Jul 31 2024, 17:43:48) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvips
>>> x = pyvips.Image.new_from_file("multipage_multichannel_pyramid.qptiff", page=21).copy_memory()
>>> x.avg()
5.15809475308642
>>> x.max()
255.0
>>> 
```

Now `x` is a memory image, so everything works.

We should think of a better solution.

**Comment by dougwood** [comment]
Great, thanks @jcupitt but I seem to have an issue with trying to do this twice in a row.  Can you please try this:

    print(pyvips.__version__)
    vips_image = pyvips.Image.new_from_file(
        r"D:\multipage_multichannel_pyramid.qptiff", page=21
    ).copy_memory()
    print(vips_image)
    print(vips_image.max())
    vips_image = vips_image.rot90()
    np_image = vips2numpy(vips_image)
    vips_image2 = pyvips.Image.new_from_file(
        r"D:\multipage_multichannel_pyramid.qptiff", page=21
    ).copy_memory()
    print(vips_image2)
    print(vips_image2.max())
    vips_image2 = vips_image2.rot90()
    np_image = vips2numpy(vips_image2)


Just repeat the same block twice.   I get 

2.2.3
<pyvips.Image 1800x1800 uchar, 1 bands, b-w>
255.0
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2023.1\plugins\python\helpers\pydev\pydevd.py", line 1546, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2023.1\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\dev\uvim\uvim\base\test_read_page.py", line 48, in <module>
    vips_image2 = pyvips.Image.new_from_file(
  File "C:\Users\Doug\AppData\Local\pypoetry\Cache\virtualenvs\uvim-91tdOcio-py3.9\lib\site-packages\pyvips\vimage.py", line 757, in copy_memory
    raise Error('unable to copy to memory')
pyvips.error.Error: unable to copy to memory
  tiff2vips: out of order read -- at line 1800, but line 0 requested

one the second call to new_from_file().copy_to_memory()

**Comment by jcupitt** [comment]
Yes, you can only call it once, it'll be cached and you'll reuse the same result the second time.

You can add `revalidate` to make it go ignore the cache and go back to the file again:

```
>>> x = pyvips.Image.new_from_file("multipage_multichannel_pyramid.qptiff", page=21, revalidate=True).copy_memory()
>>> x = pyvips.Image.new_from_file("multipage_multichannel_pyramid.qptiff", page=21, revalidate=True).copy_memory()
>>> 
```

(but this is just a workaround, we should fix this)

**Comment by dougwood** [comment]
Great that works now.  I had to upgrade my viplib to 8.15 to get the revalidate option.  
Thank you, as always for VIPS and for your help.

**Comment by jcupitt** [comment]
I made an issue for this so it's not lost. Thanks for the report!
