### ISSUE TITLE
referenced memory is not changed.

### ISSUE THREAD

**Issue by sunwoo76** [libvips/pyvips#503]
```
    image = pyvips.Image.new_from_file(svg_path)
    image.write_to_file(os.path.join(png_path)) # first-saving

   ~~ some code for changing the content in svg file from "svg_path" ~~

    image = pyvips.Image.new_from_file(svg_path)
    image.write_to_file(os.path.join(png_path)) # second-saving
```

In this case, the svg contents are changed in the middle of the code.
After changing the content and re-write to the same svg_path and read again with the same svg_path.

However, the first-saving result and second-saving result are the same.

How can I treat this?

Thank you.

**Comment by jcupitt** [comment]
Hello @sunwoo76,

libvips caches many operations to improve speed. You can force a loader to go back to the source and reload the image with:

```python
image = pyvips.Image.new_from_file(svg_path, revalidate=True)
```

**Comment by sunwoo76** [comment]
> Hello @sunwoo76,
> 
> libvips caches many operations to improve speed. You can force a loader to go back to the source and reload the image with:
> 
> ```python
> image = pyvips.Image.new_from_file(svg_path, revalidate=True)
> ```

Thank you for replying :)

However, the new error has occured:
```
pyvips.error.Error: VipsForeignLoadMagickFile does not support optional argument revalidate
```

It seems that the optional argument is not supported.

**Comment by jcupitt** [comment]
`revalidate` was added in libvips 8.15, perhaps you are using an older version?
