### ISSUE TITLE
[Bug report] Openslide integration is broken with the latest version of libvips in conda

### ISSUE THREAD

**Issue by EKami** [libvips/pyvips#519]
I noticed this morning that my code was crashing after updating my dependencies, and the issue pointed to the function `pyvips.Image.openslideload` not being found.
After investigation, it seems the libvips packages were recently updated in Anaconda/conda-forge ([linux-64/libvips-8.16.0-hbdc070c_5.conda](https://anaconda.org/conda-forge/libvips/8.16.0/download/linux-64/libvips-8.16.0-hbdc070c_5.conda)) but the version remained the same (8.16.0).

This new build, however, does not seem to ship with support for OpenSlide.
To reproduce, one can use the following `pixi.toml` ([link to pixi](https://pixi.sh/latest/)):
```
[project]
channels = ["conda-forge"]
description = "Test env"
name = "test"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
python = "3.12.*"
libvips = { version = "8.16.0", build = "hbdc070c_5" }
pyvips = "*"
```
Then run `pixi run python -c 'import pyvips; print(pyvips.type_find("VipsForeignLoad", "openslideload"))'`, you'll get `0`.
However with the following:
```
[project]
channels = ["conda-forge"]
description = "Test env"
name = "test"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
python = "3.12.*"
libvips = { version = "8.16.0", build = "hfd0f9a2_2" }
pyvips = "*"
```
The output will be different from 0.

**Comment by jcupitt** [comment]
Hello @EKami, this should probably be filed as a bug on conda -- I didn't make that package and I don't maintain it.

An alternative would be to install git master pyvips. It has a new feature where it'll automatically download and install the best libvips binary for you. Just use:

```
pip install pyvips[binary]
```

The README has some notes.

**Comment by EKami** [comment]
Indeed, sorry I forgot you weren't the person maintaining those builds @jcupitt . I'll post in the right repo.
