### ISSUE TITLE
How to view real time mosaicing of large image?

### ISSUE THREAD

**Issue by shivamchaubey** [libvips/pyvips#53]
I have built a code which will stitch 100X100 images approx. I want to view this stitiching process in real time. I am using pyvips to create large image. I am saving final image in .DZI format as it will take very less memory footprint to display. Below code is copied just for testing purpose [https://github.com/jcupitt/pyvips/issues/43]().

```
#!/usr/bin/env python

import sys
import pyvips

# overlap joins by this many pixels
H_OVERLAP = 100
V_OVERLAP = 100

# number of images in mosaic
ACROSS = 20
DOWN = 20

if len(sys.argv) < 2 + ACROSS * DOWN:
    print 'usage: %s output-image input1 input2 ..'
    sys.exit(1)
def join_left_right(filenames):
    images = [pyvips.Image.new_from_file(filename) for filename in filenames]
    row = images[0]
    for image in images[1:]:
        row = row.merge(image, 'horizontal', H_OVERLAP - row.width, 0)
    return row
def join_top_bottom(rows):
    image = rows[0]
    for row in rows[1:]:
        image = image.merge(row, 'vertical', 0, V_OVERLAP - image.height)
    return image
rows = []
for y in range(0, DOWN):
    start = 2 + y * ACROSS
    end = start + ACROSS
    rows.append(join_left_right(sys.argv[start:end]))
image = join_top_bottom(rows)
image.write_to_file(sys.argv[1])
```
To run this code:
```
$ export VIPS_DISC_THRESHOLD=100
$ export VIPS_PROGRESS=1
$ export VIPS_CONCURRENCY=1
$ mkdir sample
$ for i in {1..400}; do cp ~/pics/k2.jpg sample/$i.jpg; done
$ time ./mergeup.py x.dz sample/*.jpg
```
here `cp ~/pics/k2.jpg` will copy `k2.jpg` image 400 times from `pics` folder, so change according to your image name and location.

I want to display this process in real time. Right now after creating final mosaiced image I am able to display. Just an idea,I am thinking to make a large image and display it, then insert smaller images. I don't know, how it can be done. I am confused as we also have to make pyramidal structure. So If we create large image first we have to replace each level images with the new images. Creating .DZI image is expensive, so I don't want to create it in every running loop. Replacing images may be a solution. Any suggestion folks??

**Comment by jcupitt** [comment]
You could allocate a 512x512 (or whatever) preview image in memory, then on each load, paste a shrunk version of that image into your memory image and update the display from that.

libvips supports progress bars, so you could also display an animated "x% complete" message during dzsave.

**Comment by shivamchaubey** [comment]
Hello @jcupitt ,
Thanks for your immediate response . 
I am trying to visualize the image in full resolution so that it can be zoomed and analyzed while mosaicing is in progress. Kind of pyramidal structure is required, I think.

**Comment by shivamchaubey** [comment]
This is the link [https://youtu.be/fOiUkui5TL8](url) of WSI system, please go through the video to understand my objective.

**Comment by jcupitt** [comment]
I'm not sure that will work with libvips. It does not mosaic the image in stages in a way you could visualise -- it mosaics in small pieces on demand as the output is generated.

In the same way, dzsave does not generate the layers one after the other. Instead, it writes all the layers simultaneously in a single top-bottom pass.

**Comment by jcupitt** [comment]
I would just display the mosaic I think. For example:

https://github.com/jcupitt/vipsdisp

will display the output of a vips pipeline and let you zoom and pan around.

**Comment by shivamchaubey** [comment]
hello @jcupitt,
I am replying a bit late. [Vipsdisp](https://github.com/jcupitt/vipsdisp) can be used only when the whole image is created and saved right? Can we use this while a pipeline is created?
Also can you please suggest how progress bars can be displayed while saving the result? 
`result.write_to_file('test.tiff',Q=95, compression="lzw", bigtiff=True)`

**Comment by jcupitt** [comment]
Hello again, vipsdisp can display pipeline output directly. There's no need to save.

To get progress feedback, you need to listen for `eval` signals on the output image. That would be a bit tricky from Python, you'd need to extend pyvips a bit.

You can just set the `VIPS_PROGRESS` environment variable for simple text feedback.

**Comment by shivamchaubey** [comment]
Ok, but it will show in the last after the pipeline is linked to a sink right? Can't we see in the mapping phase? Is there any example of `vips_progress` for python script?

**Comment by shivamchaubey** [comment]
Thanks @jcupitt
