### ISSUE TITLE
Can't import pyvips on Windows 10 -- 

### ISSUE THREAD

**Issue by dougwood** [libvips/pyvips#59]
I am trying to install the the pyvips bindings but am having trouble running the simple import test described in the readme.  My system is a MacBook Pro running Windows 10 Pro 10.0.17134 in Parallels.   

I did not have the latest vips, so I downloaded 8.6.5 and edited the system path to point to this release.  I am using Anaconda to manage my python environment so I opened the Anaconda prompt window and tried the following:

(base) C:\Users\dougwood>vips --version
vips-8.6.5-Wed Jul 25 09:46:22 UTC 2018

(base) C:\Users\dougwood>echo %PATH%
C:\Users\dougwood\Anaconda3;C:\Users\dougwood\Anaconda3\Library\mingw-w64\bin;C:\Users\dougwood\Anaconda3\Library\usr\bin;C:\Users\dougwood\Anaconda3\Library\bin;C:\Users\dougwood\Anaconda3\Scripts;C:\Users\dougwood\Anaconda3\bin;C:\Program Files (x86)\Parallels\Parallels Tools\Applications;C:\Program Files\ImageMagick-7.0.6-Q16;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Users\dougwood\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\CMake\bin;C:\dev\qt\Tools\mingw492_32\bin;C:\dev\qt\5.5\mingw492_32\bin;C:\dev\OpenCV-3.1.0\opencv\build\x64\vc14\bin;C:\Program Files\MATLAB\MATLAB Compiler Runtime\v81\runtime\win64;C:\Program Files\MATLAB\MATLAB Runtime\v85\runtime\win64;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\dev\Matlab;C:\dev\bftools;C:\dev\ultivue\UltivueTools\x64\Release;C:\Program Files\BackupClient\CommandLineTool\;C:\Program Files\BackupClient\PyShell\bin\;C:\Program Files (x86)\Common Files\Acronis\SnapAPI\;C:\dev\vips\vips-dev-8.6\bin;C:\dev\vips\vips-dev-8.6\lib;C:\dev\ultivue\MPCoreFinder\x64\Release;C:\dev\OpenCV-3.3.0\opencv\build\x64\vc14\bin;C:\Program Files (x86)\Common Files\Acronis\FileProtector\;C:\Program Files (x86)\Common Files\Acronis\FileProtector64\;C:\dev\ultivue\IFImageSynth\x64\Release\;C:\dev\ultivue\DCEImageSynth\x64\Release\;C:\dev\ultivue\DCDecoder\x64\Release\;C:\Program Files\TortoiseGit\bin;C:\WINDOWS\System32\OpenSSH\;C:\Users\dougwood\AppData\Local\Programs\Python\Python35-32\Scripts\;C:\dev\Qt\5.6\msvc2015_64\bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC;C:\dev\bftools;C:\Users\dougwood\AppData\Local\Microsoft\WindowsApps;

(base) C:\Users\dougwood>python
Python 3.6.3 |Anaconda custom (64-bit)| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import logging
>>> logging.basicConfig(level=logging.DEBUG)
>>> import pyvips
DEBUG:pyvips:Binary module load failed: No module named '_libvips'
DEBUG:pyvips:Falling back to ABI mode
Traceback (most recent call last):
  File "C:\Users\dougwood\AppData\Roaming\Python\Python36\site-packages\pyvips\__init__.py", line 19, in <module>
    import _libvips
ModuleNotFoundError: No module named '_libvips'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\dougwood\AppData\Roaming\Python\Python36\site-packages\pyvips\__init__.py", line 54, in <module>
    vips_lib = ffi.dlopen(_vips_libname)
  File "C:\Users\dougwood\Anaconda3\lib\site-packages\cffi\api.py", line 140, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "C:\Users\dougwood\Anaconda3\lib\site-packages\cffi\api.py", line 786, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "C:\Users\dougwood\Anaconda3\lib\site-packages\cffi\api.py", line 782, in _load_backend_lib
    return backend.load_library(path, flags)
OSError: cannot load library C:\dev\vips\vips-dev-8.6\bin\libvips-42.dll: error 0x7f
>>>

---------

As soon as I type 'import pyvips' I see a series of error alerts appear. A screen shot of the first alert is attached. They all come from python.exe and say they are unable to find an entry point in various dlls.

![python vips lib not found](https://user-images.githubusercontent.com/15988094/43528572-4d2a5258-9577-11e8-91eb-005367f32278.jpg)

Am I doing something wrong with the installation?  Is this an issue with using Anaconda? I have also tried importing pyvips in code written in the python IDE Spyder and it has the same issue with loading the libs.

Thank you for your help with this!  I look forward to using VIPS in python!

-Doug

**Comment by jcupitt** [comment]
Sorry, Anaconda is its own weird thing, it can't use standard pip packages. 

Someone needs to make a special conda package that installs the libvips binary plus the Python part of the binding. There have been a few attempts, but it's not happened yet.

**Comment by jcupitt** [comment]
I meant to say, until there's a conda package the workaround is to install standard Python and use pyvips from that.

**Comment by dougwood** [comment]
Thanks John.  I tried installing on one of our servers as follows:
C:\Users\Doug>pip install pyvips
Collecting pyvips
  Downloading https://files.pythonhosted.org/packages/5c/6e/df4a34a9c8b349e40d6400bd4ac40558b3497732795fa0399596155b18b1/pyvips-2.1.2.tar.gz
Collecting cffi>=1.0.0 (from pyvips)
  Downloading https://files.pythonhosted.org/packages/05/3f/abc53d8f0c7362181d809c913c2b348e41c193eff84c2f0445da2b615f69/cffi-1.11.5-cp36-cp36m-win32.whl (155kB)
    100% |████████████████████████████████| 163kB 3.3MB/s
Collecting pycparser (from cffi>=1.0.0->pyvips)
  Downloading https://files.pythonhosted.org/packages/8c/2d/aad7f16146f4197a11f8e91fb81df177adcc2073d36a17b1491fd09df6ed/pycparser-2.18.tar.gz (245kB)
    100% |████████████████████████████████| 256kB 3.3MB/s
Installing collected packages: pycparser, cffi, pyvips
  Running setup.py install for pycparser ... done
  Running setup.py install for pyvips ... done
Successfully installed cffi-1.11.5 pycparser-2.18 pyvips-2.1.2
You are using pip version 9.0.1, however version 18.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

Note I did not use the --user option because I expect this will be used by all users on this server.

Next, I tried the following:

C:\Users\Doug>python
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import logging
>>> logging.basicConfig(level=logging.DEBUG)
>>> import pyvips
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pyvips'
>>> quit()

C:\Users\Doug>pip search pyvips
pyvips (2.1.2)  - binding for the libvips image processing library, API mode
  INSTALLED: 2.1.2 (latest)
You are using pip version 9.0.1, however version 18.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\Users\Doug>vips --version
vips-8.6.3-Thu Mar  8 15:18:35 UTC 2018

--------

Any idea what is the issue? There may be other versions of python on this machine.  

Thanks again for your help.
Doug

**Comment by dougwood** [comment]
I installed Python 3.7 and tried again in my Windows 10 Pro running in Parallels and this is what happened:

C:\Users\dougwood>pip install --user pyvips
Collecting pyvips
Collecting cffi>=1.0.0 (from pyvips)
  Downloading https://files.pythonhosted.org/packages/2d/9e/9d84a78d4ea3d0fa94f6d0e4bcd88406709312949f48f3853f26f8f52ebe/cffi-1.11.5-cp37-cp37m-win32.whl (154kB)
    100% |████████████████████████████████| 163kB 6.6MB/s
Collecting pycparser (from cffi>=1.0.0->pyvips)
  Using cached https://files.pythonhosted.org/packages/8c/2d/aad7f16146f4197a11f8e91fb81df177adcc2073d36a17b1491fd09df6ed/pycparser-2.18.tar.gz
Installing collected packages: pycparser, cffi, pyvips
  Running setup.py install for pycparser ... done
Successfully installed cffi-1.11.5 pycparser-2.18 pyvips-2.1.2
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\Users\dougwood>
C:\Users\dougwood>vips --version
vips-8.6.5-Wed Jul 25 09:46:22 UTC 2018

C:\Users\dougwood>python
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import  logging
>>> logging.basicConfig(level=logging.DEBUG)
>>> import pyvips
DEBUG:pyvips:Binary module load failed: No module named '_libvips'
DEBUG:pyvips:Falling back to ABI mode
Traceback (most recent call last):
  File "C:\Users\dougwood\AppData\Roaming\Python\Python37\site-packages\pyvips\__init__.py", line 19, in <module>
    import _libvips
ModuleNotFoundError: No module named '_libvips'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\dougwood\AppData\Roaming\Python\Python37\site-packages\pyvips\__init__.py", line 53, in <module>
    gobject_lib = ffi.dlopen(_gobject_libname)
  File "C:\Users\dougwood\AppData\Roaming\Python\Python37\site-packages\cffi\api.py", line 141, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "C:\Users\dougwood\AppData\Roaming\Python\Python37\site-packages\cffi\api.py", line 802, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "C:\Users\dougwood\AppData\Roaming\Python\Python37\site-packages\cffi\api.py", line 798, in _load_backend_lib
    return backend.load_library(path, flags)
OSError: cannot load library 'C:\dev\vips\vips-dev-8.6\bin\libgobject-2.0-0.dll': error 0xc1

-----------

I checked and the path to the DLL referenced is correct:

C:\Users\dougwood>dir c:\dev\vips\vips-dev-8.6\bin\libgobject*.*
 Volume in drive C has no label.
 Volume Serial Number is 5A36-DDB8

 Directory of c:\dev\vips\vips-dev-8.6\bin

07/25/18  10:35 AM           604,659 libgobject-2.0-0.dll
               1 File(s)        604,659 bytes
               0 Dir(s)  165,722,181,632 bytes free

C:\Users\dougwood>

**Comment by jcupitt** [comment]
You probably saw this old issue: https://github.com/jcupitt/pyvips/issues/44#issuecomment-390160980

That was with py3.6. I'll have a go with 3.7.

**Comment by dougwood** [comment]
Well actually, after cleaning up some path issues (more than one install of Python), I think I have it installing:

C:\Program Files\Python36\Scripts>python
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import logging
>>> logging.basicConfig(level=logging.DEBUG)
>>> import pyvips
DEBUG:pyvips:Binary module load failed: No module named '_libvips'
DEBUG:pyvips:Falling back to ABI mode
DEBUG:pyvips:Loaded lib <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x000001A4FF62ACF8>
DEBUG:pyvips:Loaded lib <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x000001A4FF6155C0>
DEBUG:pyvips:Inited libvips
DEBUG:pyvips:

---

Does that look correct given the fall back to ABI mode?  If so, I will mark this closed.

I did not move v3.7, BTW.  I will see if I can start using it in my code.

**Comment by jcupitt** [comment]
Yes, that looks fine. API mode only works if Python can find a working C compiler, which is often tricky on Windows.
