### ISSUE TITLE
pyvips.error.Error: no such operation dzsave

### ISSUE THREAD

**Issue by Frankling** [libvips/pyvips#65]
DEBUG:pyvips.error:Error  image: no property named `dzsave'

DEBUG:pyvips.error:Error no such operation dzsave VipsOperation: class "dzsave" not found

DEBUG:pyvips.voperation:VipsOperation.call: operation_name = dzsave
DEBUG:pyvips.voperation:VipsOperation.call: string_options = 
DEBUG:pyvips.error:Error no such operation dzsave VipsOperation: class "dzsave" not found

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/.local/lib/python3.5/site-packages/pyvips/vimage.py", line 799, in call_function
    return pyvips.Operation.call(name, self, *args, **kwargs)
  File "/root/.local/lib/python3.5/site-packages/pyvips/voperation.py", line 132, in call
    op = Operation.new_from_name(operation_name)
  File "/root/.local/lib/python3.5/site-packages/pyvips/voperation.py", line 60, in new_from_name
    raise Error('no such operation {0}'.format(operation_name))
pyvips.error.Error: no such operation dzsave
  VipsOperation: class "dzsave" not found

**Comment by jcupitt** [comment]
Hello @Frankling,

My guess is your libvips has been built without `dzsave` support. Did you build it yourself? `dzsave` needs `libgsf`, check the summary at the end of configure.

**Comment by Frankling** [comment]
@jcupitt thank you, I had solved it by installing pre-required  libs. 
But now I have met a problem of dzsave, when the file is large, it produce the black pic.....

**Comment by jcupitt** [comment]
It shouldn't make black output. I use it on slides of 200,000 x 200,000 pixels without problems. 

You need to give some more details: what kind of image, what size, what platform, what software versions, etc. etc.

**Comment by Frankling** [comment]
the system detail is below:
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
########################################
vips version:
vips-8.7.0-Fri Aug 31 14:11:19 UTC 2018

########################################
svs file:
https://pan.baidu.com/s/1pcjVRIuZ-kW5yrbzPAzfag

#######################################
when the svs file size is small (1.9Mb)it can work

**Comment by jcupitt** [comment]
Sorry, I can't download your file. I tried in a couple of different browsers. Could you try another file sharing service?

Do you have openslide support enabled? Try entering:

```
$ vips openslideload
load file with OpenSlide
usage:
   openslideload filename out [--option-name option-value ...]
where:
   filename     - Filename to load from, input gchararray
   out          - Output image, output VipsImage
optional arguments:
   flags        - Flags for this file, output VipsForeignFlags
   memory       - Force open via memory, input gboolean
			default: false
   access       - Required access pattern for this file, input VipsAccess
			default: random
			allowed: random, sequential, sequential-unbuffered
   level        - Load this level from the file, input gint
			default: 0
			min: 0, max: 100000
   autocrop     - Crop to image bounds, input gboolean
			default: false
   fail         - Fail on first error, input gboolean
			default: false
   associated   - Load this associated image, input gchararray
```

If you have not enabled openslide, you can get black images from SVS sources.

**Comment by Frankling** [comment]
@jcupitt 
http://openslide.cs.cmu.edu/download/openslide-testdata/Aperio/JP2K-33003-1.svs

####################################

I have try command you provide,the result show below:
vips: unknown action "openslideload"

how to enable openslide

**Comment by Frankling** [comment]
configure: WARNING: OpenSlide >= 3.3.0 not found; disabling virtual slide support
checking for MATIO... no


##############
but I have installed the openslide 3.4.1

**Comment by jcupitt** [comment]
You need the `-devel` package too.
