### ISSUE TITLE
windows error: The program issued a command but the command length is incorrect

### ISSUE THREAD

**Issue by HackersSpirit** [libvips/pyvips#68]
Hello All,
I have written a program in python to  stitch an  15 * 153 images using libvips on windows platfrom.

The program stiches till 13 * 42 images and after that i get the below mentioned error.

```
Traceback (most recent call last):
  File "C:/Users/thermo/PycharmProjects/stiching/code/mosaicing/stitcher.py", line 232, in <module>
    stitch(coor)
  File "C:/Users/thermo/PycharmProjects/stiching/code/mosaicing/stitcher.py", line 202, in stitch
    stitch_img.dzsave(output_path + '/' + output_path.split('/')[-1]) 
  File "C:\Users\thermo\sticher\lib\site-packages\pyvips\vimage.py", line 799, in call_function
    return pyvips.Operation.call(name, self, *args, **kwargs)
  File "C:\Users\thermo\sticher\lib\site-packages\pyvips\voperation.py", line 189, in call
    raise Error('unable to call {0}'.format(operation_name))
pyvips.error.Error: unable to call dzsave
  vips__file_open_read: unable to open file "..\samples\Testing\13_43.jpg" for reading
windows error: The program issued a command but the command length is incorrect.

vips__file_open_read: unable to open file "..\samples\Testing\13_44.jpg" for reading
windows error: The program issued a command but the command length is incorrect.

stitcher.py ..\samples\Testing\13_42.jpg: done in 0.00695s          
stitcher.py temp-18906: done in 149s          

Process finished with exit code 1
```

I tried to search for the problem but could not find any relevant information.

**Comment by jcupitt** [comment]
Hello @HackersSpirit,

Sorry, I don't think this will be possible. Windows has a hard limit of 2000 open files per process, and you can't change it. 15 * 153 is 2295, so you won't be able to open all of your input images. You will need to assemble the image in sections, or change your platform. 

You seem to be failing earlier, which is strange. Perhaps you are opening other files elsewhere? You would need to post a sample program for me to test.

**Comment by HackersSpirit** [comment]
@jcupitt : thanks for the clear explanation on the windows side.
Can you please elaborate on assembling the images in a section part

**Comment by jcupitt** [comment]
I don't know any details about what you are doing, but that's the general idea, yes. You'll need to experiment a bit.

**Comment by HackersSpirit** [comment]
@jcupitt : OK thanks

**Comment by HackersSpirit** [comment]
#Program Starts
import os
import pyvips
# natsort helps with sorting the list logically
from natsort import natsorted

source = r"C:\\Users\\thermo\\Desktop\\ScanSample\\input\\"
output = r"C:\\Users\\thermo\\Desktop\\ScanSample\\output\\"
save_to = output + 'final' + '.tif'

# define list of pictures we are going to get from folder
list_of_pictures = []
# get the
for x in os.listdir(source):
    list_of_pictures.append(source + x)

# list_of_pictures now contains all the images from folder including full path
# since os.listdir will not guarantee proper order of files we use natsorted to do it
list_of_pictures = natsorted(list_of_pictures)

array_images = []
image = None
# lets create array of the images for joining, using sequential so it use less ram
for i in list_of_pictures:
    tile = pyvips.Image.new_from_file(i, access="sequential")
    array_images.append(tile)

# Join them, across is how many pictures there be next to each other, so i just counted all pictures in array with len
out = pyvips.Image.arrayjoin(array_images, across=len(list_of_pictures))
# write it out to file....
out.write_to_file(save_to, Q=95, compression="lzw", bigtiff=True)
#Program Completes

Hi @jcupitt : Here is one of the sample program which reads the imarges and join them.
The program returns the above error when number of file exceed.

Can you please provide sample of what you have mentioned in the comment above:
Just assemble the first 1000 to a temporary file, then the second, then the third. Finally, join the three parts.

**Comment by jcupitt** [comment]
Run the program to insert the first 1000 images and save the result to a temporary file in TIFF format.

Now run a second program that loads the TIFF from above as the background, then inserts another 1000 images on top and saves to s second temporary file.

Finally, run the program again, loading the second temporary as a background and pasting the final 1000 images on top. Save that to your output file and delete the two temporary files.

**Comment by HackersSpirit** [comment]
Thanks for the clarifying the steps. 👍 
One more thing instead of running the above process sequentially can we run it parallely and finally merge temp images one by one.

**Comment by jcupitt** [comment]
Maybe. It depends if your images overlap.
