### ISSUE TITLE
write_to_memory() with thumbnails does not work.

### ISSUE THREAD

**Issue by 9xg** [libvips/pyvips#72]
I have tried a couple of different things now, but I end up with the same issue. I work with whole-slide .svs image and the images load with openslideload expected.

If I create: 
```
demoSlidePath = 'path/to/file.svs'
pvImage = pv.Image.new_from_file(demoSlidePath)
```  
and do
```
roi = pvImage.crop(left, top, width, height) #variables set somewhere else0
pvImgMem = roi.write_to_memory()
```
everything goes fine and I can use ``pvImgMem`` for a creating a NumPy array.

When I try to extract a thumbnail:
```
image = pv.Image.thumbnail(demoSlidePath, 3000) 
thumbnailImgMem = image.write_to_memory()
```
the program gets stuck at ``image.write_to_memory()``.

As cropping out a random region works perfectly fine, I am not sure whether I am doing something wrong with the thumbnail function or the issue sits somewhere else.

**Comment by jcupitt** [comment]
Hello, I think it's working, it just takes ages. 

`thumbnail` has special logic to do shrink-on-load for jpeg, webp, pdf, svg and perhaps some others, but not openslide. Without shrink-on-load, it'll have to decompress and scan the entire slide image to make the thumbnail.

For example, with:

```python
import sys
import pyvips

image = pyvips.Image.thumbnail(sys.argv[1], 3000)
thumbnailImgMem = image.write_to_memory()
```

I see:

```
$ time python thumbmem.py ~/pics/openslide/CMU-1.svs 

real	1m20.531s
user	4m56.518s
sys	0m1.862s
```

And that's with a relatively small slide.

If you ask it to thumbnail a lower-res level, it's quicker:

```
$ time python thumbmem.py ~/pics/openslide/CMU-1.svs[level=2] 

real	0m1.674s
user	0m5.501s
sys	0m0.073s
```

**Comment by jcupitt** [comment]
I added an enhancement for shrink-on-load support for openslide in `thumbnail`.

**Comment by 9xg** [comment]
Thank! Your answer was very ueful!

**Comment by jcupitt** [comment]
OK, implemented in git master, I'll close. Thanks for the suggestion.
