### ISSUE TITLE
Performance of extract_area and write_to_buffer

### ISSUE THREAD

**Issue by MatthiasKohl** [libvips/pyvips#73]
Hi,

this is not really an issue but I need advice:
basically, I'm working with large TIF files (~100 000 x 100 000) and I need to extract patches from them as fast as possible, asynchronously from the main thread. So a naive approach would be this:

```python
full_img = pyvips.Image.new_from_file('large.tif')
# called on many threads
def read_patch(coord):
    patch_img = full_img.extract_area(coord[0], coord[1], size[0], size[1])
    return np.ndarray(patch_img.write_to_memory(), ...)
```

But this is very slow, it takes ~23ms on average for a ~300x300 patch on my system, which is too much for my purposes.
Reading larger areas first and then just slicing them for the patches was about equally slow, so I thought what slowed me down was mostly the decompression time from the TIF (I'm not exactly sure how it is compressed, tiled, etc.).

So I just converted the TIF to binary first and then re-did as above using the VIPS file format.
And it still takes ~20ms on average for a ~300x300 patch.
However, now reading larger areas is much faster, so I can get the speed down to ~3ms by reading 100 000 x 300 rows and then extracting from there.

I suspect that this is an issue with synchronization, these experiments are done with fairly recent hardware (as in last two years) and reading from a SSD, so I don't believe the problem is the disk access speed or RAM/CPU/bus speeds.

Do you have any idea why it could be slow to read many patches from different threads ?

Note:
I also tried experimenting with `vips_cache()` since I know I will be reading patches in regular intervals but the cached image always returned zero-values on subsequent `write_to_memory()` calls (it does work when called from main thread though, so I assume this is an issue with threading as well).

Finally, it's not really an option for me to just keep the file in binary/VIPS format, because the original files are already >1GB and the binaries are >90GB which is hard to keep on a SSD. But if you have a suggestion for a compromise which is not too big but much faster to read for VIPS, it's no problem to convert the files of course. Unfortunately, I don't have much information about how the originals were created and I'm not really an expert on this, so I'm not even sure what the compression is etc.

**Comment by jcupitt** [comment]
Hello, you need JPEG tiled tiff. 

This is a variant of tiff where the image is sliced into a set of 128 x 128 pixel tiles and each tile is JPEG-compressed and indexed separately. It just stores the coefficients for each tile -- the huffman tables etc. are shared between tiles.

It has the nice properties of being barely larger than a regular JPEG-compressed tiff, but you can read out arbitrary regions quickly. libvips does caching and threading for you behind the scenes.

Try:

```
$ vipsheader bild.ndpi 
bild.ndpi: 126976x98304 uchar, 4 bands, rgb, openslideload
$ vips copy bild.ndpi x.tif[tile,compression=jpeg]
$ ls -l x.tif
-rw-r--r-- 1 john john 1018488356 Nov  5 13:44 x.tif
```

So only ~1gb for that huge image.

Now this program:

```python
import sys
import random
import pyvips

image = pyvips.Image.new_from_file(sys.argv[1])
tile_size = 300

for i in range(0, 1000):
    x = random.randint(0, image.width - tile_size)
    y = random.randint(0, image.height - tile_size)
    tile = image.crop(x, y, tile_size, tile_size)
    buf = tile.write_to_memory()
```

Runs like this on my system:

```
$ time python3 randomtile.py ~/pics/openslide/x.tif 
real	0m3.475s
user	0m3.170s
sys	0m0.879s
```

So about 3ms per tile.

**Comment by MatthiasKohl** [comment]
Wow, thank you so much, this was easy and indeed it's much faster ! Single threaded it takes about 5ms on my system now.

But I just checked with multiple threads again and it's still not much faster than single threaded.
You can check this with the following (modified from yours) example:

```python
import sys
import random
import pyvips
from concurrent.futures import ThreadPoolExecutor

image = pyvips.Image.new_from_file(sys.argv[1])
multi_thread = len(sys.argv) > 2 and sys.argv[2]
tile_size = 300

def read():
    x = random.randint(0, image.width - tile_size)
    y = random.randint(0, image.height - tile_size)
    tile = image.crop(x, y, tile_size, tile_size)
    buf = tile.write_to_memory()
    # dummy return
    return buf[0] is None

executor = ThreadPoolExecutor(max_workers=8)
futures = []
for i in range(0, 1000):
    if multi_thread:
        futures.append(executor.submit(read))
    else:
        read()
if multi_thread:
    for future in futures:
        future.result()
```

**Comment by MatthiasKohl** [comment]
I checked some more and the example above scales up as expected with `multiprocessing` (multiple processes) instead of `concurrent.futures` (multiple threads). So I assume it has to do with [global interpretor lock](https://docs.python.org/3.4/glossary.html#term-global-interpreter-lock) in Python. I'm surprised because I thought the call to `write_to_memory` was linked to the C++ library, which should avoid the GIL in Python... but at least I have a good solution now :)

**Comment by jcupitt** [comment]
It won't scale well with threads: libtiff does the per-tile JPEG decompress inside a global mutex, unfortunately :(

**Comment by MatthiasKohl** [comment]
Thank you again for the answer !
