### ISSUE TITLE
pyvips broken?

### ISSUE THREAD

**Issue by kuhnchris** [libvips/pyvips#76]
Hi,

I tried working with some tool yesterday that depended on pyvips, but since yesterday I receive the following error, with the test program:

```
git:(master) ✗ python3 a.py
DEBUG:pyvips:Binary module load failed: No module named '_libvips'
DEBUG:pyvips:Falling back to ABI mode
DEBUG:pyvips:Loaded lib <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7692137a3f28>
DEBUG:pyvips:Loaded lib <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x769213891e80>
DEBUG:pyvips:Inited libvips
Traceback (most recent call last):
  File "a.py", line 3, in <module>
    import pyvips
  File "/usr/lib/python3.6/site-packages/pyvips/__init__.py", line 134, in <module>
    _log_handler_cb = ffi.callback('GLogFunc', _log_handler)
  File "/usr/lib/python3.6/site-packages/cffi/api.py", line 386, in callback
    return callback_decorator_wrap(python_callable)  # direct mode
  File "/usr/lib/python3.6/site-packages/cffi/api.py", line 380, in callback_decorator_wrap
    error, onerror)
SystemError: <built-in function callback> returned NULL without setting an error

git:(master) ✗ cat a.py
import logging
logging.basicConfig(level = logging.DEBUG)
import pyvips
```

Alpine Linux current, and docker-image of python:3.7-slim-stretch so it's cross-platform (python docker image is based of debian)

**Comment by jcupitt** [comment]
Oh dear, that sounds bad, thanks for the report. I'll take a look.

**Comment by jcupitt** [comment]
I made a dockerfile for pyvips on alpine and it seems to work:

https://github.com/jcupitt/docker-builds/tree/master/pyvips-alpine

That's with py2.7, the alpine default. I'll try 3.6.

**Comment by kuhnchris** [comment]
Sorry, forgot to mention: the tool uses 3.6, yeah.

**Comment by jcupitt** [comment]
I tried with 36:

```
(2/3) Installing python3 (3.6.6-r0)
```

and it still seems to work. I'll see if I can get 3.7 installed.

**Comment by jcupitt** [comment]
I added 3.7 to the travis test matrix, and you're right, it seems to fail:

https://travis-ci.org/libvips/pyvips

I'll investigate.

**Comment by jcupitt** [comment]
Oh hehe only because it's broken on Travis, sigh. I'll try locally.

**Comment by jcupitt** [comment]
I built python 3.7.1 and it seems to work:

```
john@yingna ~/GIT/docker-builds (master) $ pip3.7 install --upgrade pip
Collecting pip
  Downloading https://files.pythonhosted.org/packages/c2/d7/90f34cb0d83a6c5631cf71dfe64cc1054598c843a92b400e55675cc2ac37/pip-18.1-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 12.0MB/s 
Installing collected packages: pip
  Found existing installation: pip 10.0.1
    Uninstalling pip-10.0.1:
      Successfully uninstalled pip-10.0.1
Successfully installed pip-18.1
john@yingna ~/GIT/docker-builds (master) $ pip3.7 install pyvips
Collecting pyvips
  Downloading https://files.pythonhosted.org/packages/b3/55/abb37dfddb4907b00b0e55b85cda090aa0704f9a587d62b925b0238e898c/pyvips-2.1.4.tar.gz
Collecting cffi>=1.0.0 (from pyvips)
  Downloading https://files.pythonhosted.org/packages/51/7b/d1014289d0578c3522b2798b9cb87c65e5b36798bd3ae68a75fa1fe09e78/cffi-1.11.5-cp37-cp37m-manylinux1_x86_64.whl (421kB)
    100% |████████████████████████████████| 430kB 9.4MB/s 
Collecting pkgconfig (from pyvips)
  Using cached https://files.pythonhosted.org/packages/e1/8a/c205fad800317a59e8d218981a8a7a3a00ec69c7fd55eca58dd08e6b0a18/pkgconfig-1.4.0-py2.py3-none-any.whl
Collecting pycparser (from cffi>=1.0.0->pyvips)
Installing collected packages: pycparser, cffi, pkgconfig, pyvips
  Running setup.py install for pyvips ... done
Successfully installed cffi-1.11.5 pkgconfig-1.4.0 pycparser-2.19 pyvips-2.1.4
john@yingna ~/GIT/docker-builds (master) $ python3.7
Python 3.7.1 (default, Nov 15 2018, 13:33:31) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvips
>>> 
```

Looking at your error again, you have:

```
  File "/usr/lib/python3.6/site-packages/pyvips/__init__.py", line 134, in <module>
    _log_handler_cb = ffi.callback('GLogFunc', _log_handler)
```

ie. python3.6 pyvips, but you say you are using 3.7. Could there perhaps be a problem with `PYTHONPATH`?

**Comment by kuhnchris** [comment]
Hi there @jcupitt sorry for the late reply I was out medically.

Anyways, the 3.6 you saw was my "local" install, which doesn't work.
the 3.7 is a real 3.7 one that doesn't work aswell:

web_1      | SystemError: <built-in function callback> returned NULL without setting an error
web_1      |   File "manage.py", line 59, in <module>
web_1      |     execute_from_command_line(sys.argv)
web_1      |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
web_1      |     utility.execute()
web_1      |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
web_1      |     django.setup()
web_1      |   File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
web_1      |     apps.populate(settings.INSTALLED_APPS)
web_1      |   File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 112, in populate
web_1      |     app_config.import_models()
web_1      |   File "/usr/local/lib/python3.7/site-packages/django/apps/config.py", line 198, in import_models
web_1      |     self.models_module = import_module(models_module_name)
web_1      |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
web_1      |     return _bootstrap._gcd_import(name[level:], package, level)
web_1      |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
web_1      |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
web_1      |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
web_1      |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
web_1      |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
web_1      |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
web_1      |   File "/code/app/avatar/models.py", line 35, in <module>
web_1      |     from .utils import build_avatar_component, convert_img, get_upload_filename
web_1      |   File "/code/app/avatar/utils.py", line 31, in <module>
web_1      |     import pyvips
web_1      |   File "/usr/local/lib/python3.7/site-packages/pyvips/__init__.py", line 134, in <module>
web_1      |     _log_handler_cb = ffi.callback('GLogFunc', _log_handler)
web_1      |   File "/usr/local/lib/python3.7/site-packages/cffi/api.py", line 386, in callback
web_1      |     return callback_decorator_wrap(python_callable)  # direct mode
web_1      |   File "/usr/local/lib/python3.7/site-packages/cffi/api.py", line 380, in callback_decorator_wrap
web_1      |     error, onerror)
web_1      | SystemError: <built-in function callback> returned NULL without setting an error
^CGracefully stopping... (press Ctrl+C again to force)

The only thing that changed is that I rebooted my server recently, as in last week.
Kernel:
Linux uranus 4.9.65-1-virthardened #2-Alpine SMP Mon Nov 27 15:53:30 GMT 2017 x86_64 Linux

Aside from that I'm kind of against a wall here, since I cannot get the project up anymore...

**Comment by jcupitt** [comment]
Sorry, it works for me in docker, so I think there must be some other issue with your install, unless you can make a test case to reproduce the problem.

I think I would rebuild the stack of packages a component at the time until something broke. Your cffi package is the obvious suspect.

**Comment by kuhnchris** [comment]
That's weird! Your docker file breaks on my system aswell!
```
Step 13/14 : RUN pip3.7 install --upgrade pip   && pip3.7 install pyvips
 ---> Running in 78bc31dc6028Collecting pip
  Downloading https://files.pythonhosted.org/packages/c2/d7/90f34cb0d83a6c5631cf71dfe64cc1054598c843a92b400e55675cc2ac37/pip-18.1-py2.py3-none-any.whl (1.3MB)
Installing collected packages: pip
  Found existing installation: pip 10.0.1    Uninstalling pip-10.0.1:
      Successfully uninstalled pip-10.0.1
Successfully installed pip-18.1
Collecting pyvips  Downloading https://files.pythonhosted.org/packages/b3/55/abb37dfddb4907b00b0e55b85cda090aa0704f9a587d62b925b0238e898c/pyvips-2.1.4.tar.gz
Collecting cffi>=1.0.0 (from pyvips)
  Downloading https://files.pythonhosted.org/packages/e7/a7/4cd50e57cc6f436f1cc3a7e8fa700ff9b8b4d471620629074913e3735fb2/cffi-1.11.5.tar.gz (438kB)
Collecting pycparser (from cffi>=1.0.0->pyvips)  Downloading https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz (158kB)Installing collected packages: pycparser, cffi, pyvips
  Running setup.py install for pycparser: started    Running setup.py install for pycparser: finished with status 'done'  Running setup.py install for cffi: started    Running setup.py install for cffi: finished with status 'done'
  Running setup.py install for pyvips: started
    Running setup.py install for pyvips: finished with status 'done'Successfully installed cffi-1.11.5 pycparser-2.19 pyvips-2.1.4
Removing intermediate container 78bc31dc6028 ---> 8af71eb55052
Step 14/14 : WORKDIR /data ---> Running in 411690c3ac1e
Removing intermediate container 411690c3ac1e
 ---> 9a1dcc3b6e49
Successfully built 9a1dcc3b6e49
Successfully tagged alp:latest
➜  pyvips-python3.7-alpine git:(master) docker run --rm -t -v $PWD:/data alp ./wobble.py test.jpg x.jpg
Traceback (most recent call last):
  File "./wobble.py", line 4, in <module>
    import pyvips
  File "/usr/local/lib/python3.7/site-packages/pyvips/__init__.py", line 134, in <module>
    _log_handler_cb = ffi.callback('GLogFunc', _log_handler)
  File "/usr/local/lib/python3.7/site-packages/cffi/api.py", line 386, in callback
    return callback_decorator_wrap(python_callable)  # direct mode
  File "/usr/local/lib/python3.7/site-packages/cffi/api.py", line 380, in callback_decorator_wrap
    error, onerror)
SystemError: <built-in function callback> returned NULL without setting an error
```

**Comment by kuhnchris** [comment]
OK! Now I know what's going on! It's the grsecurity that's screwing it up.
I couldnt even start any other proper docker container (firefox died on me, that's what made me find that out).
Now it works fine.

_  ~ python3 pytest.py
DEBUG:pyvips:Binary module load failed: No module named '_libvips'
DEBUG:pyvips:Falling back to ABI mode
DEBUG:pyvips:Loaded lib <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7f3d8c85f358>
DEBUG:pyvips:Loaded lib <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7f3d8c857198>
DEBUG:pyvips:Inited libvips

Sorry for the issue!

**Comment by jcupitt** [comment]
Oh heh. Well, I'm glad it's working.

**Comment by EunsungKoh** [comment]
Hello @jcupitt , 
I'm using docker environment and python 3.7.
I' think I'm suffering similar issues.
Can I get a any hint for this issue?

```
~$ docker exec -it 2b14 /bin/bash
root@2b147d09f5d5:/conduit# pip3.7 install --upgrade pip
Requirement already up-to-date: pip in /usr/local/lib/python3.7/site-packages (19.0.1)
root@2b147d09f5d5:/conduit# pip3.7 install pyvips
Requirement already satisfied: pyvips in /usr/local/lib/python3.7/site-packages (2.1.5)
Requirement already satisfied: cffi>=1.0.0 in /usr/local/lib/python3.7/site-packages (from pyvips) (1.11.5)
Requirement already satisfied: pycparser in /usr/local/lib/python3.7/site-packages (from cffi>=1.0.0->pyvips) (2.19)
root@2b147d09f5d5:/conduit#  python3.7
Python 3.7.2 (default, Jan 23 2019, 02:31:57) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvips
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyvips/__init__.py", line 19, in <module>
    import _libvips
ModuleNotFoundError: No module named '_libvips'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/pyvips/__init__.py", line 69, in <module>
    vips_lib = ffi.dlopen(_vips_libname)
  File "/usr/local/lib/python3.7/site-packages/cffi/api.py", line 141, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/usr/local/lib/python3.7/site-packages/cffi/api.py", line 802, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/usr/local/lib/python3.7/site-packages/cffi/api.py", line 797, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library 'libvips.so.42': libvips.so.42: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libvips.so.42'
```

**Comment by jcupitt** [comment]
Have you installed the libvips library? It looks like it can't be found by pyvips.

If you can't fix it, please open a new issue and share your Dockerfile.

**Comment by EunsungKoh** [comment]
Hi there @jcupitt.
I'm feeling sorry for late response, Monday through Wednesday was holidays.

I think I don't have libvips in docker environment as you told.
Though I want to download a libvips in docker env, I can not find easy and precise way.
I downloaded libvips in my local linux(ubuntu) env with just command ```apt install libvips-tools```.

So, Can you please let me know the precise way to download libvips library in docker environment? 

By the way, Its my Dockerfile
```
 FROM python:3
 ENV PYTHONUNBUFFERED 1
 RUN mkdir /backend
 WORKDIR /backend
 ADD requirements.txt /backend/
 RUN pip install -r requirements.txt
 ADD . /backend/
 EXPOSE 8000
```
and requirements.txt
```
Django==1.9.6
django-extensions==1.6.7
djangorestframework==3.3.3
PyJWT==1.4.0
six==1.10.0
django-cors-headers
psycopg2
```

Also using docker-compose
```
  backend:
    build: .
    volumes:
      - ./:/conduit 
    working_dir: /conduit/
    command: sh entrypoint.sh
    ports:
      - 8000:8000
    depends_on:
      - db
```
and entrypoint.sh
```
pip install -r requirements.txt
python manage.py migrate
python manage.py runserver 0.0.0.0:8000
```

Sorry for my broken english.

Sinceley,
Eunsung Sam Koh

**Comment by jcupitt** [comment]
Hello again, please make a new issue, you have a different problem.
