### ISSUE TITLE
pyvips.Image.new_from_memory_copy missing in pyvips bindings?

### ISSUE THREAD

**Issue by erdmann** [libvips/pyvips#77]
Hi John,

It appears that the new pyvips bindings are missing `pyvips.Image.new_from_memory_copy`, which used to be present in the old gobject introspection Vips-8 bindings if I understand correctly:

https://lazka.github.io/pgi-docs/Vips-8.0/classes/Image.html#Vips.Image.new_from_memory_copy

Given that libvips doesn't take ownership of buffers when using `Image.new_from_memory`, this is could be the cause of inadvertent segfaults when constructing an Image from a numpy array.  For example, consider `pyvips.Image.new_from_memory(np.ones((3,3)).data, 3, 3, 1, 'double')`, which will leave the memory allocated by ones with no owner since the ones buffer will be freed by python as soon as it goes out of scope.  The pointer held by vips will not be valid, leading to a segfault later if it tries to read or write there.  Being able to use `pyvips.Image.new_from_memory_copy` would solve this.

Is this an intentional omission?  If not, what is the correct approach to avoid the problem where one constructs a libvips array from a numpy buffer which subsequently gets garbage collected when it goes out of scope but while the pyvips.Image is still in scope?

Thanks in advance.

**Comment by jcupitt** [comment]
Hello again @erdmann,

This should be OK, I think. pyvips keeps a "secret" reference to the data object you pass in (buffer or memoryview), so at least your example should work, I think.

I see:

```
john@yingna ~/try $ python
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> impoty pyvips
>>> import pyvips
>>> x = pyvips.Image.new_from_memory(np.ones((3,3)).data, 3, 3, 1, 'double')
>>> x.avg()
1.0
>>> import gc
>>> gc.collect()
3
>>> gc.collect()
0
>>> x.avg()
1.0
```

To be safe, you could do:

```
x = x.copy_memory()
```

Which will take a complete copy of a vips image, but hopefully it would not be necessary.

**Comment by jcupitt** [comment]
The docs do talk about this, though hidden behind an annoying + button:

https://libvips.github.io/pyvips/vimage.html#pyvips.Image.new_from_memory

**Comment by jcupitt** [comment]
pyvips 2.1.5 has an enhanced version of this: it keeps secret references to all input memory, and copies those references through operations. Hopefully it should all be automatic and uncrashable now.
