### ISSUE TITLE
Resource leak in multiprocessing

### ISSUE THREAD

**Issue by MatthiasKohl** [libvips/pyvips#78]
Hi, this is a follow-up to https://github.com/libvips/pyvips/issues/73

I implemented my patch extraction based on a process pool, as discussed there.
The processes each create a VIPS image from the path (to a large file) and then extract patches from it.

```python
def process_job(i, large_file_path):
    vips_img = pyvips.Image.new_from_file(large_file_path)
    # extract stuff from it
    area = vips_img.extract_area(x, y, width, height)
    a = np.ndarray(area.write_to_buffer(), ...)
    # ...

iterable = ((i, 'large_image.tif') for i in range(1000))
pool.imap_unordered(process_job, iterable)
```

This kind of function is actually called many times for each image, because I'm using the pool to submit jobs to the worker processes, which only extract a few patches at a time.

Now, after running this for about ~25 different images, the extraction silently fails. Basically, the array just gets filled with zeros or random values, probably because somehow the underlying buffer is not allocated. The problem is, it's possible for me to reproduce, but it takes about an hour, and I haven't found a way to shorten that (just extracting from many images works fine, it seems like it's only an issue when calling this job function many many times as well).

This makes me think that this is a problem with synchronization, but I can't really figure out why and the fact that I can reproduce it is strange as well (it fails almost at the same point every time).

So maybe it's an issue with certain resources not being free'd as they should ?

I've looked into the debug logs (set the python logging to debug) and they are very long ofc but nothing really strange seems to happen at the point where the extraction silently fails. The only thing I can use to tell that it fails at all is that every time the job is called, a warning is issued (no resolution info for TIFF image ...), which I think has been removed in recent versions, whereas for the previous images, this warning would only be issued once per process starting.
So something must be different in the underlying access to the images, but I can't figure out what.

If you have a suggestion of how to better my program (possibly sharing the VIPS images as a global inherited by the processes instead of sending the path and creating it every time, etc.), I would be grateful, too, of course !

**Comment by MatthiasKohl** [comment]
I have moved initialization of the VIPS image to the process pool initializer. This still has a bit of a strange effect because after the same number of images, I get the warning about TIFF resolution twice instead of only once per process (so the underlying image is probably opened twice/fails on first time). However, the patches that come out of the operations are now good and everything seems to work as expected.

So my problem is resolved for now, but I'm still wondering what happens after that number of images and whether I'm following best practices concerning multi-processing and reading from the same image...

**Comment by jcupitt** [comment]
Hello again,

I think you'd need to share a complete example before I could say for sure. I've not used process pools and I'm a bit unclear about exactly how Python resources are shared over fork() (if it is forking? I'm not even sure). 

When a process does `import pyvips` for the first time, libvips will be started up. This is a complex operation, takes ~10ms, something like that, and must be single-threaded. You can use pyvips from many threads after that, but init must be single-threaded. 

Could that be the issue?

**Comment by jcupitt** [comment]
The TIFF res warning could be down to libvips caching. It will share images between threads behind your back, and a shared image might warn less.

You could try turning off operation caching with:

```python
pyvips.cache_set_max(0)
```

And see if the behaviour changes.

**Comment by MatthiasKohl** [comment]
In Python multiprocessing, you can choose from different methods for creating processes, but here I'm using fork as you thought. This means ``import pyvips`` is only executed once on the parent process, and everything is inherited for the child processes (including any file descriptors libvips may open, handles to threads etc.).

This could be an issue, if for example libvips relies on global file descriptors (or other handles) that it writes to, since multiple processes would start writing to that same handle, possibly corrupting it. I don't think that's the problem here, though, as I can reproduce the behavior always after a given number of images, whereas corrupting some handle could occur at any time.

I think it could be the caching behavior as you suggested because I guess the cache has a fixed size and so something would change after a certain number of operations. So I'll try to play around with that and see what happens.

I could also initialize libvips only in the child processes (executing ``import pyvips`` only after fork), which should give each child process their own initialized version of libvips.

I'll try to share a stripped down version of my script once I get to it.

Thank you for your help so far!

**Comment by jcupitt** [comment]
Yes, fork() and threads do not  interact well. The usual unix advice is to do one or the other, but not both, eg.:

http://www.linuxprogrammingblog.com/threads-and-fork-think-twice-before-using-them

Since libvips is heavily threaded, I would start it in the child process only.

**Comment by jcupitt** [comment]
Oop, accidental close.

**Comment by MatthiasKohl** [comment]
Thank you for the advice, everything works as expected when starting vips in the child processes only, so I will close this issue.
