### ISSUE TITLE
Cannot locate libvips.so.42

### ISSUE THREAD

**Issue by EKami** [libvips/pyvips#86]
Hello,
I just installed vips from source on my system and here are the relevant outputs after the install:
```
$ ldconfig -p | grep vips
	libvips.so.42 (libc6,x86-64) => /usr/local/lib/libvips.so.42
	libvips.so (libc6,x86-64) => /usr/local/lib/libvips.so
	libvips-cpp.so.42 (libc6,x86-64) => /usr/local/lib/libvips-cpp.so.42
	libvips-cpp.so (libc6,x86-64) => /usr/local/lib/libvips-cpp.so

$ echo $LD_LIBRARY_PATH 
$LD_LIBRARY_PATH:/usr/local/lib/

$ echo $C_INCLUDE_PATH 
$C_INCLUDE_PATH:/usr/local/include/

$ echo $CPLUS_INCLUDE_PATH 
$CPLUS_INCLUDE_PATH:/usr/local/include/

$ ls /usr/local/include/
blosc-export.h  blosc.h  jconfig.h  jerror.h  jmorecfg.h  jpeglib.h  openjpeg-2.3  openslide  vips  zconf.h  zlib.h
```

But after installing pyvips with:
```
pip install -U git+https://github.com/libvips/pyvips.git
```

And doing:
```
import pyvips
```

I get this error:
```
>>> import pyvips
Traceback (most recent call last):
  File "/home/ekami/Programs/anaconda3/envs/dl/lib/python3.7/site-packages/pyvips/__init__.py", line 19, in <module>
    import _libvips
ModuleNotFoundError: No module named '_libvips'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ekami/Programs/anaconda3/envs/dl/lib/python3.7/site-packages/pyvips/__init__.py", line 70, in <module>
    vips_lib = ffi.dlopen(_vips_libname)
  File "/home/ekami/Programs/anaconda3/envs/dl/lib/python3.7/site-packages/cffi/api.py", line 146, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/home/ekami/Programs/anaconda3/envs/dl/lib/python3.7/site-packages/cffi/api.py", line 828, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/home/ekami/Programs/anaconda3/envs/dl/lib/python3.7/site-packages/cffi/api.py", line 823, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library 'libvips.so.42': /usr/lib/librsvg-2.so.2: undefined symbol: cairo_tag_end.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libvips.so.42'
```

I'm on [Manjaro](https://manjaro.org/) (Arch linux) and my conda env is using Python 3.7.2. Any idea how I can solve this? 
Thank you.

**Comment by jcupitt** [comment]
Hello, Anaconda have their own package system and they won't work with standard native binaries. You'll need to make a special libvips package for conda.

A few people have tried, but no success yet, as far as I know.

**Comment by EKami** [comment]
That's really weird, because I have another machine under ubuntu 18.04 where I installed libvips via apt and vips via pip and everything is working well there under Python 3.7 and conda :(

**Comment by EKami** [comment]
So I found a temporary solution. The big issue is that my system was complaining about that `cairo_tag_end` symbol. So what I ended up doing was:
```
$ cp /usr/local/lib/libvips.so.42 ~/anaconda3/envs/<env-name>/lib/
```
where `<env-name>` is the name of the conda environment.
Then:
```
$ scp ubuntu_machine:/usr/lib/x86_64-linux-gnu/librsvg-2.so.2 ~/anaconda3/envs/dl/lib/
```

People can probably copy this lib from a docker image but for convenience, I uploaded it [here](https://drive.google.com/file/d/1q_QzD9lkW-zmUoAAlnshNRzezovyjZQS/view?usp=sharing).

I'll make some tests and come back to you if it work (or if it doesn't).

**Comment by EKami** [comment]
Working perfectly well so far. Feel free to close this discussion @jcupitt if you think it's all you need from me to help other people with the same issue.

**Comment by jcupitt** [comment]
OK, that's good. I would be wary of issues though, it sounds a little fragile.

Anaconda has its own system for making and installing binaries and it's usually not safe to cross the streams. I think the correct solution is to have a proper conda package installed and updated with the conda toolset.

**Comment by EKami** [comment]
@jcupitt Agreed and there is one on the conda repo actually. But the thing is it's for Python 3.6... and I didn't really want to downgrade. For now it's working fine, that's all I'm asking. Finger crossed :crossed_fingers:

**Comment by EKami** [comment]
There is actually a cleaner solution to the ugly one I found.
Just use:
```
conda install -c conda-forge librsvg
```

And you're done :)

**Comment by jcupitt** [comment]
Oh nice. Do you get an API or ABI build?

https://github.com/libvips/pyvips#test-your-install

**Comment by EKami** [comment]
ABI mode it seems, what is the difference exactly?
```
DEBUG:pyvips:Binary module load failed: No module named '_libvips'
DEBUG:pyvips:Falling back to ABI mode
DEBUG:pyvips:Loaded lib <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7f6d63423ac8>
DEBUG:pyvips:Loaded lib <cffi.api._make_ffi_library.<locals>.FFILibrary object at 0x7f6d634239b0>
DEBUG:pyvips:Inited libvips
```

**Comment by EKami** [comment]
Uh I think I'll never be done with these issues, now I get:
```
    main()
  File "/home/ekami/workspace/PathologyWatch/src/main.py", line 607, in main
    parse_args(kwargs)
  File "/home/ekami/workspace/PathologyWatch/src/main.py", line 545, in parse_args
    args.pred_mode, args.tta_count, args.show_reconstruction, output_results_dir)
  File "/home/ekami/workspace/PathologyWatch/src/main.py", line 416, in evaluate
    batch_size, downsample)
  File "/home/ekami/workspace/PathologyWatch/src/main.py", line 351, in get_eval_patch_dataset
    crop_size, downsample, pred_mode)
  File "/home/ekami/workspace/PathologyWatch/src/data/patch_ds.py", line 120, in construct_for_test
    kfolds=None)
  File "/home/ekami/workspace/PathologyWatch/src/data/patch_ds.py", line 95, in __init__
    self._init_dataset()
  File "/home/ekami/workspace/PathologyWatch/src/data/patch_ds.py", line 536, in _init_dataset
    self._num_process, self._pred_mode)
  File "/home/ekami/workspace/PathologyWatch/src/data/extractor.py", line 373, in get_slides
    img, slide_width, slide_height = image.get_wsi(wsi_file, downsample)
  File "/home/ekami/workspace/PathologyWatch/src/utils/image.py", line 161, in get_wsi
    osr = OpenSlide(str(file))
  File "/home/ekami/Programs/anaconda3/envs/dl/lib/python3.7/site-packages/openslide/__init__.py", line 154, in __init__
    self._osr = lowlevel.open(filename)
  File "/home/ekami/Programs/anaconda3/envs/dl/lib/python3.7/site-packages/openslide/lowlevel.py", line 178, in _check_open
    raise OpenSlideError(err)
openslide.lowlevel.OpenSlideError: Can't read macro associated image: Wrong JPEG library version: library is 80, caller expects 90
```

Both libjpeg9 and libjpeg8 are present on my system, I'm afraid if I change manually the softlinks of my system or if I remove libjpeg8 that will cause issues with my other programs :(

**Comment by jcupitt** [comment]
With API mode, it generates some C for the bottom parts of the binding at install time, then builds, then calls the C to communicate with libvips. It needs the libvips headers to be able to do this.

In ABI mode, everything is done in Python (eg. even assembling the stack frame ready to call into the lib) and all it needs is the libvips.so shared library.

If you process big images, the extra call overhead is unimportant. If you are doing lots of operations on smaller images, it can be noticeable.

**Comment by jcupitt** [comment]
Yes that's a classic conda / non-conda problem :-( It's very unfortunate that there are at least four versions of libjpeg in common use, and you (often) can't mix them in one executable.

Wait until you try to load something via libMagick.

**Comment by EKami** [comment]
Thanks a lot for taking the time to explain, greatly appreciated :)

**Comment by EKami** [comment]
Ok so I dunno what exactly I did but I managed to fix the openslide/libjpeg issue by recompiling openslide from source and checking that the right shared libraries are called. At least everything "works" now, maybe I'll try to resolve this API/ABI issue later but for now I'm just happy that my code runs xD . Thanks for everything @jcupitt :)

**Comment by NeelKanwal** [comment]
> There is actually a cleaner solution to the ugly one I found.
> Just use:
> 
> ```
> conda install -c conda-forge librsvg
> conda install -c conda-forge libiconv 
> ```
> 
> And you're done :)

It does not work for me

**Comment by Younger330** [comment]
> guys, if you are on ubuntu, doing everything required for pip and conda is not enough, i had to run `sudo apt install libvips` for it to work

Brilliant, that works for me.

**Comment by edoumazane** [comment]
@jcupitt 
> Hello, Anaconda have their own package system and they won't work with standard native binaries. You'll need to make a special libvips package for conda.
> 
> A few people have tried, but no success yet, as far as I know.

@soykingz 
> guys, if you are on ubuntu, doing everything required for pip and conda is not enough, i had to run `sudo apt install libvips` for it to work

In 2024 `conda install libvips -c conda-forge` did the trick for me
