### ISSUE TITLE
File size

### ISSUE THREAD

**Issue by obruck** [libvips/pyvips#87]
Hi,

I am analyzing ~1 Gb svs-format images with python and exporting modified images as tiff-images. The resolution and image size are the same as before analysis. However, the file size increases 5-10x. As my dataset consists of 1000 images, I was wondering is there any means to compress image size without affecting image quality?

Here is the code to export images
```
output_image = numpy2vips(sourcenorm)
image.tiffsave(output_image,
                        tile=True,
                        compression='lzw',
                        xres=20000,
                        yres=20000,
                        bigtiff=True,
                        pyramid=True,
                        Q=100)
```

Replacing `compression='lzw'` with `compression='jpg'` decreased essentially image quality so is no longer an option. The image file does not necessarily need to be tiff, if image quality can be preserved.

**Comment by jcupitt** [comment]
Hello @obruck,

svs images are compressed with jpeg2000, so you'll need to save as high-quality jpg. Is `Q=100` not good enough? 

You'll find `deflate` is better than `lzw`, but it will still be huge.

libvips 8.8 supports save as heic, which combines excellent quality with high compression, but that won't work for large images.

**Comment by obruck** [comment]
Thanks @jcupitt for the help! I don't know what happened with my first run, but now the jpeg compression looks very sharp. I'll close the issue!

**Comment by jcupitt** [comment]
Hi @mrcolo,

Could you open a new issue, please? Give some more details about image dimensions, what kind of speed you need, etc.
