### ISSUE TITLE
how to get the total levels when using dzsave

### ISSUE THREAD

**Issue by NextGuido** [libvips/pyvips#89]
@jcupitt Hello! Can can tell me how to get the exact number of levels when using dzsave? Cause I wanna get the exact pic from the specified level. 

![aaa](https://user-images.githubusercontent.com/37173179/54668521-0f5d6780-4b2a-11e9-8878-6ecf0acb1b99.jpg)

**Comment by jcupitt** [comment]
Hello, I would just scan the output directory and find the one with the highest number. That would only be a few lines of code.

`log2(smaller-axis)` will mostly work, but will probably miss by one in some cases. If you need a 100% dependable answer, you'll need to reimplement the pyramid building code from dzsave:

https://github.com/libvips/libvips/blob/master/libvips/foreign/dzsave.c#L577

Scanning the directory would be simpler.

**Comment by NextGuido** [comment]
Thx for quick answer. Actually I don't wanna use dzsave to get tiles. But I trully want to get its levels. Thanks, I'll check this out. [https://github.com/libvips/libvips/blob/master/libvips/foreign/dzsave.c#L577](url)

**Comment by NextGuido** [comment]
@jcupitt Hi! I'm back again! Now, I have another question. I need to skip fully black tiles while using dzsave with python. May you help me with this? thx

**Comment by jcupitt** [comment]
That's a feature in libvips 8.8 -- there's a new `skip_blanks` option.

I'll close this issue -- could you open a new one if you have a new question?
