### ISSUE TITLE
pip install fails with fatal error LNK1158

### ISSUE THREAD

**Issue by Daniel-01** [libvips/pyvips#91]
pip install pyvips --user
Fails with:
LINK : fatal error LNK1158: cannot run 'rc.exe'

Windows 10
Visual Studio 2017 Professional 15.9.10
Python 3.6.2

**Comment by jcupitt** [comment]
Hello @Daniel-01,

pyvips uses the standard python build wrapper, so if it's failing, you probably have a problem with that.

I would just use pyvips in ABI mode on Windows, so just use libvips.dll and don't try to build the wrapper. It's a little slower, but much simpler.

**Comment by Daniel-01** [comment]
From the documentation it seems like ABI mode is something pyvips should fall back to automatically.

"If it is unable to build a binary extension, it will use cffi ABI mode instead and only needs the libvips shared library. This takes longer to start up and is typically ~20% slower in execution. You can find out how pyvips installed with pip show pyvips."

But since installing pyvips fails, I cannot use it in any mode. Or what am I missing?

**Comment by jcupitt** [comment]
I agree, it should fall back. I tried removing my python headers (so compile would fail) and installing pyvips, and it fell back to ABI mode correctly. 

Perhaps it's failing outside the `try` block in `setup.py`?

https://github.com/libvips/pyvips/blob/master/setup.py#L111

Could you get a more detailed error message? Try `pip install pyvips --verbose`.

**Comment by Daniel-01** [comment]
The stack trace does not show where in setup.py it is failing it only contains various levels of distutils, but I can see that it happens twice.

First time this happens:

Reading https://pypi.python.org/simple/cffi/
    Downloading https://files.pythonhosted.org/packages/64/7c/27367b38e6cc3e1f49f193deb761fe75cda9f95da37b67b422e62281fcac/cffi-1.12.2.tar.gz#sha256=e113878a446c6228669144ae8a56e268c91b7f1fafae927adc4879d9849e0ea7
    Best match: cffi 1.12.2
    Processing cffi-1.12.2.tar.gz
    Writing C:\Users\DanielH\AppData\Local\Temp\easy_install-gn2zcepp\cffi-1.12.2\setup.cfg
    Running cffi-1.12.2\setup.py -q bdist_egg --dist-dir C:\Users\DanielH\AppData\Local\Temp\easy_install-gn2zcepp\cffi-1.12.2\egg-dist-tmp-evicy4ra

Then it starts compiling, and when compilation is done linking fails with the error I have already described.
It seems like it recovers the first time, but tries the exact same thing again.
It downloads the same package and starts to compile again and the same error happens, but this time there is an exception during the exception handling inside distutils and the whole thing fails.

**Comment by jcupitt** [comment]
It sounds like it's `cffi` failing to install, rather than `pyvips`. Both API and ABI mode need `cffi`, so trying twice is correct.

Try `pip install cffi` and see if that fails. If it does, it's probably a problem with your VS install.

**Comment by Daniel-01** [comment]
"pip install cffi" worked. It did not build anything, just downloaded some stuff and installed it.
So I tried "pip install pyvips" after that, and it worked too!
So I guess the solution is to "pip install cffi" first.

**Comment by jcupitt** [comment]
Huh strange. Well, I'm glad it's working!

**Comment by andreped** [comment]
I had a similar issue that I couldn't `pip install *` on a virtual environment on a server (through ssh). I got SSL errors. Normally, I fix this by `pip install --trusted-host pypi,python.org --trusted-host files.pythonhosted.org *`, but in this case it still didn't install. It seemed like running `pip install cffi` before installing pyvips solved the issue for me. Seems like this solved @Daniel-01s issues as well. Should the install order be adjusted? @jcupitt

**Comment by jcupitt** [comment]
It should do it automatically, I think. `setup.py` lists `cffi` as a dependency, so `pip` ought to install `cffi` before installing `pyvips`.

I don't really understand what's going on :(

**Comment by jcupitt** [comment]
git master pyvips (2.1.13) has better install diagnostics.

If you could try that, it might be able to display a useful error message.
