### ISSUE TITLE
Trouble using custom font from ttf file

### ISSUE THREAD

**Issue by MisterMorden** [libvips/pyvips#94]
Hello again developers,

I'm having difficulty making use of custom fonts with pyvips.  For example the following code:

```
import pyvips
from PIL import Image

image = pyvips.Image.text('this is some text', dpi=300, fontfile='D:/Res/Brassia-Regular.ttf')
mem_image = image.write_to_memory()
pil_image = Image.frombytes('L', (image.width, image.height), mem_image)
pil_image.save('foo.jpg')
```

...yields the following image:
![foo](https://user-images.githubusercontent.com/29239528/56072738-c1b1d480-5d4e-11e9-92b0-4f3cdedc9ce1.jpg)

But the font file specified above is supposed to look like the font on this page:

https://fontlibrary.org/en/font/brassia

I'm not sure what I'm missing.

Thank you,
Alex

**Comment by jcupitt** [comment]
Setting `fontfile` just loads the font --- you have to select it too. Try:

```python
import pyvips

image = pyvips.Image.text('this is some text', dpi=300, font='Brassia', \
                          fontfile='brassia-master/fonts/ttf/Brassia-Regular.ttf')
image.write_to_file('foo.jpg')
```

You can mix fonts, eg.:

```python
import pyvips

image = pyvips.Image.text('this is some <span font="brassia">text</span>', dpi=300, \
                          fontfile='brassia-master/fonts/ttf/Brassia-Regular.ttf')
image.write_to_file('foo.jpg')
```

**Comment by jcupitt** [comment]
Did you find the main docs for `text`, btw?

https://libvips.github.io/libvips/API/current/libvips-create.html#vips-text

**Comment by MisterMorden** [comment]
I'll try this when I get back to work on Monday!

**Comment by MisterMorden** [comment]
But to answer your question, I did not manage to find that piece of documentation.  Even so, is there a reason why the user would load a font file but not want to use the font in the file they just asked to load?

**Comment by jcupitt** [comment]
Fonts are selected by name, and it's not easy to work out the name of a font from the ttf filename.

Good luck on Monday.

**Comment by jcupitt** [comment]
pyvips is a very "thin" binding (it's only a few 100 lines of code for the core), with most of it being generated at runtime from introspection of the libvips shared library. 

The pyvips docs are mostly generated automatically too. The main docs are in libvips itself and you need to look at those for the details. Hopefully it's easy to work out how to drive them from python.

**Comment by MisterMorden** [comment]
It works!  Thank you again!
