### ISSUE TITLE
Error: VipsJpeg: out of order read at line xxxx with rotation

### ISSUE THREAD

**Issue by aflc** [libvips/pyvips#96]
I found an error when reading with access='sequential' mode and rotation.

I used [this image](https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Wikipedia-logo-v2.svg/500px-Wikipedia-logo-v2.svg.png).

I found some details:

* If using [200px png](https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Wikipedia-logo-v2.svg/500px-Wikipedia-logo-v2.svg.png), no error occurred.
* access='random' also OK.
* Both write_to_buffer() and write_to_file() failed.

And thanks for awesome lib :)

Version info:
```
$ vips --version
vips-8.7.4-Fri Jan 18 12:51:47 UTC 2019
$ pip freeze | grep pyvips
pyvips==2.1.5
```

Traceback:
```
n [1]: import pyvips

In [2]: pyvips.cache_set_trace(True)

In [3]: img = pyvips.Image.new_from_file('./500px-Wikipedia-logo-v2.svg.png', access='sequential')
vips cache : pngload filename="./500px-Wikipedia-logo-v2.svg.png" out=((VipsImage*) 0x254f1b0) flags=((VipsForeignFlags) VIPS_FOREIGN_SEQUENTIAL) access=((Vi
psAccess) VIPS_ACCESS_SEQUENTIAL) -

In [4]: img_rot = img.rot90()
vips cache+: rot in=((VipsImage*) 0x254f1b0) out=((VipsImage*) 0x254f340) angle=((VipsAngle) VIPS_ANGLE_D90) -

In [5]: buf = img_rot.write_to_buffer('.jpg')
vips cache+: colourspace in=((VipsImage*) 0x254f340) out=((VipsImage*) 0x254f4d0) space=((VipsInterpretation) VIPS_INTERPRETATION_sRGB) -
vips cache : copy in=((VipsImage*) 0x254f4d0) out=((VipsImage*) 0x254f660) -
vips cache+: flatten in=((VipsImage*) 0x254f4d0) background=0  out=((VipsImage*) 0x254f020) -
vips cache+: cast in=((VipsImage*) 0x254f020) out=((VipsImage*) 0x254f7f0) format=((VipsBandFormat) VIPS_FORMAT_UCHAR) -
vips cache+: linecache in=((VipsImage*) 0x254fe30) out=((VipsImage*) 0x7f28740511a0) tile-height=8 access=((VipsAccess) VIPS_ACCESS_SEQUENTIAL) -
vips cache+: sequential in=((VipsImage*) 0x254fe30) out=((VipsImage*) 0x7f2874051010) tile-height=8 -
---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
<ipython-input-5-2de37a5d6b3e> in <module>
----> 1 buf = img_rot.write_to_buffer('.jpg')

~/xxx/lib/python3.6/site-packages/pyvips/vimage.py in write_to_buffer(self, format_string, **kwargs)
    546
    547         return pyvips.Operation.call(name, self,
--> 548                                      string_options=options, **kwargs)
    549
    550     def write_to_memory(self):

~/xxx/lib/python3.6/site-packages/pyvips/voperation.py in call(operation_name, *args, **kwargs)
    187         vop = vips_lib.vips_cache_operation_build(op.pointer)
    188         if vop == ffi.NULL:
--> 189             raise Error('unable to call {0}'.format(operation_name))
    190         op = Operation(vop)
    191

Error: unable to call VipsForeignSaveJpegBuffer
  vipspng: out of order read at line 456
vipspng: out of order read at line 456
vipspng: out of order read at line 456
vipspng: out of order read at line 456
vipspng: out of order read at line 456
vipspng: out of order read at line 456
vipspng: out of order read at line 456
vipspng: out of order read at line 456
vipspng: out of order read at line 456
```

**Comment by jcupitt** [comment]
Hello @aflc,

This is expected behaviour. The "sequential" access hint means you promise to only ask for pixels from top to bottom. It lets libvips delay decompression until each pixel is needed. Your rotate operation will break this rule.

There's a chapter in the docs explaining how this works:

https://libvips.github.io/libvips/API/current/How-it-opens-files.md.html

The final section talks about sequential mode.

**Comment by aflc** [comment]
@jcupitt thanks for your reply and detailed explanation!

I got about the limitation of "sequential" access, so how could i know which operation supports "sequential" or not?

Or do i have to try with some images first and change the access mode if failed?

I would appreciate it if you add "supported access mode" in docs, or return more easy-to-understand error messages like "rot operation do not support the sequential access".

One more question:

If i switched to "random" access mode, memory consumption grows dramatically?

I tried [vips-bench/vips.py](https://github.com/libvips/vips-bench) on my macbook,  a memory usage of these two modes (random and sequential) has no significant difference.

**Comment by jcupitt** [comment]
Sequential access mode will fail with any operation that does a large coordinate transform, so things like rotate or warp. Convolution, extract, insert, embed, arithmetic etc. should all be fine.

Sequential mode should be faster and need less memory, but it depends on the images. vips-bench uses tiled TIFFs, which will be the same in sequential and random modes.

You're right, the error messages could be better.

**Comment by roy-freee** [comment]
> vips-bench uses tiled TIFFs, which will be the same in sequential and random modes.

Oh, sorry for misunderstanding.

I'll test a memory consumption in my usecase with random access mode.

Thanks☺️

**Comment by aflc** [comment]
> vips-bench uses tiled TIFFs, which will be the same in sequential and random modes.

Oh, sorry for misunderstanding.

I'll test a memory consumption in my usecase with random access mode.

Thanks☺️
